async function Module(moduleArg={}){var moduleRtn;var g=moduleArg,aa=!!globalThis.window,ca=!!globalThis.WorkerGlobalScope,da=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;if(da){const {createRequire:a}=await import("node:module");var require=a(import.meta.url)}var ea=(a,b)=>{throw b;},ha=import.meta.url,ia="",ja,ka;
if(da){var fs=require("node:fs");ha.startsWith("file:")&&(ia=require("node:path").dirname(require("node:url").fileURLToPath(ha))+"/");ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);ea=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ca){try{ia=(new URL(".",ha)).href}catch{}ca&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),p=console.error.bind(console),na,oa=!1,la=a=>a.startsWith("file://"),pa,qa,u,w,y,ra,C,E,sa,ta,F,ua,va=!1;
function wa(){var a=xa.buffer;u=new Int8Array(a);y=new Int16Array(a);w=new Uint8Array(a);ra=new Uint16Array(a);g.HEAP32=C=new Int32Array(a);g.HEAPU32=E=new Uint32Array(a);g.HEAPF32=sa=new Float32Array(a);ta=new Float64Array(a);F=new BigInt64Array(a);ua=new BigUint64Array(a)}function G(a){g.onAbort?.(a);a="Aborted("+a+")";p(a);oa=!0;a+=". Build with -sASSERTIONS for more info.";va&&ya();a=new WebAssembly.RuntimeError(a);qa?.(a);throw a;}var za;
async function Aa(a){if(!na)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==za&&na)a=new Uint8Array(na);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function Ba(a,b){try{var c=await Aa(a);return await WebAssembly.instantiate(c,b)}catch(d){p(`failed to asynchronously prepare wasm: ${d}`),G(d)}}
async function Ca(a){var b=za;if(!na&&!la(b)&&!da)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){p(`wasm streaming compile failed: ${d}`),p("falling back to ArrayBuffer instantiation")}return Ba(b,a)}class Da{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ea=a=>{for(;0<a.length;)a.shift()(g)},Fa=[],Ga=[],Ha=()=>{var a=g.preRun.shift();Ga.push(a)},Ia=!0,Ja=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ka=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ja(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},La=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Ma=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Na=(a,b)=>Ka(a+"/"+b),Oa=()=>{if(da){var a=require("node:crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Pa=a=>{(Pa=Oa())(a)},Qa=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:H.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ja(b.split("/").filter(e=>!!e),!c).join("/");
return(c?"/":"")+b||"."},Ra=(a,b)=>{function c(h){for(var k=0;k<h.length&&""===h[k];k++);for(var m=h.length-1;0<=m&&""===h[m];m--);return k>m?[]:h.slice(k,m-k+1)}a=Qa(a).slice(1);b=Qa(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Sa=globalThis.TextDecoder&&new TextDecoder,Ta=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},
Ua=(a,b=0,c,d)=>{b>>>=0;c=Ta(a,b,c,d);if(16<c-b&&a.buffer&&Sa)return Sa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Va=[],Wa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:
2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Xa=(a,b,c,d)=>{c>>>=0;if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.codePointAt(f);if(127>=h){if(c>=d)break;b[c++>>>0]=h}else if(2047>=h){if(c+1>=d)break;b[c++>>>0]=192|h>>6;b[c++>>>0]=128|h&63}else if(65535>=h){if(c+2>=d)break;b[c++>>>0]=224|h>>12;b[c++>>>0]=128|h>>6&63;b[c++>>>0]=128|h&63}else{if(c+3>=d)break;b[c++>>>0]=240|h>>18;b[c++>>>0]=128|h>>12&63;b[c++>>>0]=128|h>>6&63;b[c++>>>0]=128|h&63;f++}}b[c>>>0]=0;return c-
e},Ya=a=>{var b=Array(Wa(a)+1);a=Xa(a,b,0,b.length);b.length=a;return b},Za=[];function $a(a,b){Za[a]={input:[],output:[],Ua:b};ab(a,bb)}
var bb={open(a){var b=Za[a.node.rdev];if(!b)throw new H.pa(43);a.tty=b;a.seekable=!1},close(a){a.tty.Ua.fsync(a.tty)},fsync(a){a.tty.Ua.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Ua.Ib)throw new H.pa(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.Ua.Ib(a.tty)}catch(k){throw new H.pa(29);}if(void 0===h&&0===e)throw new H.pa(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Ua.zb)throw new H.pa(60);try{for(var e=0;e<d;e++)a.tty.Ua.zb(a.tty,
b[c+e])}catch(f){throw new H.pa(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},cb={Ib(){a:{if(!Va.length){var a=null;if(da){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Va=Ya(a)}a=Va.shift()}return a},zb(a,b){null===b||10===b?(ma(Ua(a.output)),a.output=[]):
0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ma(Ua(a.output)),a.output=[])},kc(){return{Hc:25856,Jc:5,Gc:191,Ic:35387,Fc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},lc(){return 0},mc(){return[24,80]}},db={zb(a,b){null===b||10===b?(p(Ua(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(p(Ua(a.output)),a.output=[])}},J={Pa:null,za(){return J.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||H.isFIFO(c))throw new H.pa(63);
J.Pa||(J.Pa={dir:{node:{Ma:J.ra.Ma,Oa:J.ra.Oa,lookup:J.ra.lookup,Sa:J.ra.Sa,rename:J.ra.rename,unlink:J.ra.unlink,rmdir:J.ra.rmdir,readdir:J.ra.readdir,symlink:J.ra.symlink},stream:{Ia:J.ua.Ia}},file:{node:{Ma:J.ra.Ma,Oa:J.ra.Oa},stream:{Ia:J.ua.Ia,read:J.ua.read,write:J.ua.write,bb:J.ua.bb,ib:J.ua.ib}},link:{node:{Ma:J.ra.Ma,Oa:J.ra.Oa,readlink:J.ra.readlink},stream:{}},Cb:{node:{Ma:J.ra.Ma,Oa:J.ra.Oa},stream:H.Xb}});c=H.createNode(a,b,c,d);K(c.mode)?(c.ra=J.Pa.dir.node,c.ua=J.Pa.dir.stream,c.va=
{}):H.isFile(c.mode)?(c.ra=J.Pa.file.node,c.ua=J.Pa.file.stream,c.Ca=0,c.va=null):40960===(c.mode&61440)?(c.ra=J.Pa.link.node,c.ua=J.Pa.link.stream):8192===(c.mode&61440)&&(c.ra=J.Pa.Cb.node,c.ua=J.Pa.Cb.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.va[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Uc(a){return a.va?a.va.subarray?a.va.subarray(0,a.Ca):new Uint8Array(a.va):new Uint8Array(0)},ra:{Ma(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=
0;b.rdev=a.rdev;K(a.mode)?b.size=4096:H.isFile(a.mode)?b.size=a.Ca:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Oa(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Ca!=b&&(0==b?(a.va=null,a.Ca=0):(c=a.va,a.va=new Uint8Array(b),c&&a.va.set(c.subarray(0,Math.min(b,a.Ca))),a.Ca=b)))},lookup(){J.qb||(J.qb=
new H.pa(44),J.qb.stack="<generic error, no stack>");throw J.qb;},Sa(a,b,c,d){return J.createNode(a,b,c,d)},rename(a,b,c){try{var d=L(b,c)}catch(f){}if(d){if(K(a.mode))for(var e in d.va)throw new H.pa(55);eb(d)}delete a.parent.va[a.name];b.va[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.va[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=L(a,b),d;for(d in c.va)throw new H.pa(55);delete a.va[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.va)]},
symlink(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new H.pa(28);return a.link}},ua:{read(a,b,c,d,e){var f=a.node.va;if(e>=a.node.Ca)return 0;a=Math.min(a.node.Ca-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===u.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.va||a.va.subarray)){if(f)return a.va=b.subarray(c,c+d),a.Ca=d;if(0===a.Ca&&
0===e)return a.va=b.slice(c,c+d),a.Ca=d;if(e+d<=a.Ca)return a.va.set(b.subarray(c,c+d),e),d}f=e+d;var h=a.va?a.va.length:0;h>=f||(f=Math.max(f,h*(1048576>h?2:1.125)>>>0),0!=h&&(f=Math.max(f,256)),h=a.va,a.va=new Uint8Array(f),0<a.Ca&&a.va.set(h.subarray(0,a.Ca),0));if(a.va.subarray&&b.subarray)a.va.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.va[e+f]=b[c+f];a.Ca=Math.max(a.Ca,e+d);return d},Ia(a,b,c){1===c?b+=a.position:2===c&&H.isFile(a.node.mode)&&(b+=a.node.Ca);if(0>b)throw new H.pa(28);return b},
bb(a,b,c,d,e){if(!H.isFile(a.node.mode))throw new H.pa(43);a=a.node.va;if(e&2||!a||a.buffer!==u.buffer){d=!0;G();e=void 0;if(!e)throw new H.pa(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);u.set(a,e>>>0)}}else d=!1,e=a.byteOffset;return{xa:e,Bc:d}},ib(a,b,c,d){J.ua.write(a,b,0,d,c,!1);return 0}}},fb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},gb=async a=>{a=await ja(a);return new Uint8Array(a)},hb=0,ib=null,jb=[],lb=async(a,b)=>{"undefined"!=
typeof Browser&&kb();for(var c of jb)if(c.canHandle(b))return c.handle(a,b);return a},nb=async(a,b,c,d,e,f,h,k)=>{var m=b?Qa(Ka(a+"/"+b)):a;hb++;g.monitorRunDependencies?.(hb);try{var l=c;"string"==typeof c&&(l=await gb(c));l=await lb(l,m);k?.();if(!f){c=b;a&&(a="string"==typeof a?a:mb(a),c=b?Ka(a+"/"+b):a);var n=fb(d,e),r=H.create(c,n);if(l){if("string"==typeof l){var q=Array(l.length);b=0;for(var t=l.length;b<t;++b)q[b]=l.charCodeAt(b);l=q}H.chmod(r,n|146);var v=H.open(r,577);H.write(v,l,0,l.length,
0,h);H.close(v);H.chmod(r,n)}}}finally{hb--,g.monitorRunDependencies?.(hb),0==hb&&ib&&(h=ib,ib=null,h())}};function kb(){var a,b,c;H.sb=!0;a??=g.stdin;b??=g.stdout;c??=g.stderr;a?H.Ya("/dev","stdin",a):H.symlink("/dev/tty","/dev/stdin");b?H.Ya("/dev","stdout",null,b):H.symlink("/dev/tty","/dev/stdout");c?H.Ya("/dev","stderr",null,c):H.symlink("/dev/tty1","/dev/stderr");H.open("/dev/stdin",0);H.open("/dev/stdout",1);H.open("/dev/stderr",1)}function ab(a,b){H.Fb[a]={ua:b}}
function K(a){return 16384===(a&61440)}function L(a,b){var c=K(a.mode)?(c=M(a,"x"))?c:a.ra.lookup?0:2:54;if(c)throw new H.pa(c);for(c=H.Ta[ob(a.id,b)];c;c=c.$a){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return H.lookup(a,b)}function eb(a){var b=ob(a.parent.id,a.name);if(H.Ta[b]===a)H.Ta[b]=a.$a;else for(b=H.Ta[b];b;){if(b.$a===a){b.$a=a.$a;break}b=b.$a}}
function N(a,b={}){if(!a)throw new H.pa(44);b.mb??(b.mb=!0);"/"===a.charAt(0)||(a=H.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=H.root,e="/",f=0;f<a.length;f++){var h=f===a.length-1;if(h&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=La(e),H.vb(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Ka(e+"/"+a[f]);try{d=L(d,a[f])}catch(k){if(44===k?.Da&&h&&b.pc)return{path:e};throw k;}!d.Na||h&&!b.mb||(d=d.Na.root);if(40960===(d.mode&61440)&&(!h||
b.Ka)){if(!d.ra.readlink)throw new H.pa(52);d=d.ra.readlink(d);"/"===d.charAt(0)||(d=La(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new H.pa(32);}function mb(a){for(var b;;){if(H.vb(a))return a=a.za.Lb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function ob(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%H.Ta.length}function pb(a){var b=ob(a.parent.id,a.name);a.$a=H.Ta[b];H.Ta[b]=a}
function M(a,b){return H.Jb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function qb(a,b){if(!K(a.mode))return 54;try{return L(a,b),20}catch(c){}return M(a,"wx")}function rb(a,b,c){try{var d=L(a,b)}catch(e){return e.Da}if(a=M(a,"wx"))return a;if(c){if(!K(d.mode))return 54;if(H.vb(d)||mb(d)===H.cwd())return 10}else if(K(d.mode))return 31;return 0}function sb(a,b){if(!a)throw new H.pa(b);return a}
function O(a){a=H.fc(a);if(!a)throw new H.pa(8);return a}function tb(a,b=-1){a=Object.assign(new H.Vb,a);if(-1==b)a:{for(b=0;b<=H.Wb;b++)if(!H.streams[b])break a;throw new H.pa(33);}a.fd=b;return H.streams[b]=a}function vb(a,b=-1){a=tb(a,b);a.ua?.Oc?.(a);return a}function wb(a,b,c){var d=a?.ua.Oa;a=d?a:b;d??=b.ra.Oa;sb(d,63);d(a,c)}function xb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.hb)}return b}
function yb(a){var b={Ec:4096,Rc:4096,blocks:1E6,Dc:5E5,Cc:5E5,files:H.yb,Pc:H.yb-1,Sc:42,flags:2,Xc:255};a.ra.Qb&&Object.assign(b,a.ra.Qb(a.za.qc.root));return b}function zb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return H.Sa(a,b|8192,c)}function Ab(a,b,c,d){wb(a,b,{mode:c&4095|b.mode&-4096,ctime:Date.now(),Gb:d})}function Bb(a,b,c){if(K(b.mode))throw new H.pa(31);if(!H.isFile(b.mode))throw new H.pa(28);var d=M(b,"w");if(d)throw new H.pa(d);wb(a,b,{size:c,timestamp:Date.now()})}
function Cb(a,b,c,d){a="string"==typeof a?a:mb(a);b=Ka(a+"/"+b);return H.create(b,fb(c,d))}function Db(a){if(!(a.nc||a.oc||a.link||a.va))if(globalThis.XMLHttpRequest)G("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.va=ka(a.url)}catch(b){throw new H.pa(29);}}
var H={root:null,hb:[],Fb:{},streams:[],yb:1,Ta:null,Db:"/",sb:!1,Jb:!0,bc:null,pb:0,pa:class{name="ErrnoError";constructor(a){this.Da=a}},Vb:class{Va={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.Va.flags}set flags(a){this.Va.flags=a}get position(){return this.Va.position}set position(a){this.Va.position=a}},Ub:class{ra={};ua={};Na=null;constructor(a,b,c,d){a||=this;this.parent=a;this.za=a.za;this.id=H.yb++;this.name=b;this.mode=c;this.rdev=d;this.atime=
this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get oc(){return K(this.mode)}get nc(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new H.Ub(a,b,c,d);pb(a);return a},vb(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},Wb:4096,fc:a=>H.streams[a],Xb:{open(a){a.ua=
H.dc(a.node.rdev).ua;a.ua.open?.(a)},Ia(){throw new H.pa(70);}},xb:a=>a>>8,Vc:a=>a&255,Za:(a,b)=>a<<8|b,dc:a=>H.Fb[a],Rb(a,b){function c(k){H.pb--;return b(k)}function d(k){if(k){if(!d.$b)return d.$b=!0,c(k)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);H.pb++;1<H.pb&&p(`warning: ${H.pb} FS.syncfs operations in flight at once, probably just doing extra work`);var e=xb(H.root.za),f=0,h;for(h of e)h.type.Rb?h.type.Rb(h,a,d):d(null)},za(a,b,c){var d="/"===c;if(d&&H.root)throw new H.pa(10);
if(!d&&c){var e=N(c,{mb:!1});c=e.path;e=e.node;if(e.Na)throw new H.pa(10);if(!K(e.mode))throw new H.pa(54);}b={type:a,qc:b,Lb:c,hb:[]};a=a.za(b);a.za=b;b.root=a;d?H.root=a:e&&(e.Na=b,e.za&&e.za.hb.push(b));return a},ad(a){a=N(a,{mb:!1});if(!a.node.Na)throw new H.pa(28);a=a.node;var b=a.Na,c=xb(b);for([,e]of Object.entries(H.Ta))for(;e;){var d=e.$a;c.includes(e.za)&&eb(e);var e=d}a.Na=null;a.za.hb.splice(a.za.hb.indexOf(b),1)},lookup(a,b){return a.ra.lookup(a,b)},Sa(a,b,c){var d=N(a,{parent:!0}).node;
a=Ma(a);if(!a)throw new H.pa(28);if("."===a||".."===a)throw new H.pa(20);var e=qb(d,a);if(e)throw new H.pa(e);if(!d.ra.Sa)throw new H.pa(63);return d.ra.Sa(d,a,b,c)},Qb(a){return yb(N(a,{Ka:!0}).node)},$c(a){return yb(a.node)},create(a,b=438){return H.Sa(a,b&4095|32768,0)},mkdir(a,b=511){return H.Sa(a,b&1023|16384,0)},Wc(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{H.mkdir(d,b)}catch(f){if(20!=f.Da)throw f;}}},symlink(a,b){if(!Qa(a))throw new H.pa(44);var c=
N(b,{parent:!0}).node;if(!c)throw new H.pa(44);b=Ma(b);var d=qb(c,b);if(d)throw new H.pa(d);if(!c.ra.symlink)throw new H.pa(63);return c.ra.symlink(c,b,a)},rename(a,b){var c=La(a),d=La(b),e=Ma(a),f=Ma(b);var h=N(a,{parent:!0});var k=h.node;h=N(b,{parent:!0});h=h.node;if(!k||!h)throw new H.pa(44);if(k.za!==h.za)throw new H.pa(75);var m=L(k,e);a=Ra(a,d);if("."!==a.charAt(0))throw new H.pa(28);a=Ra(b,c);if("."!==a.charAt(0))throw new H.pa(55);try{var l=L(h,f)}catch(n){}if(m!==l){b=K(m.mode);if(e=rb(k,
e,b))throw new H.pa(e);if(e=l?rb(h,f,b):qb(h,f))throw new H.pa(e);if(!k.ra.rename)throw new H.pa(63);if(m.Na||l&&l.Na)throw new H.pa(10);if(h!==k&&(e=M(k,"w")))throw new H.pa(e);eb(m);try{k.ra.rename(m,h,f),m.parent=h}catch(n){throw n;}finally{pb(m)}}},rmdir(a){var b=N(a,{parent:!0}).node;a=Ma(a);var c=L(b,a),d=rb(b,a,!0);if(d)throw new H.pa(d);if(!b.ra.rmdir)throw new H.pa(63);if(c.Na)throw new H.pa(10);b.ra.rmdir(b,a);eb(c)},readdir(a){a=N(a,{Ka:!0}).node;return sb(a.ra.readdir,54)(a)},unlink(a){var b=
N(a,{parent:!0}).node;if(!b)throw new H.pa(44);a=Ma(a);var c=L(b,a),d=rb(b,a,!1);if(d)throw new H.pa(d);if(!b.ra.unlink)throw new H.pa(63);if(c.Na)throw new H.pa(10);b.ra.unlink(b,a);eb(c)},readlink(a){a=N(a).node;if(!a)throw new H.pa(44);if(!a.ra.readlink)throw new H.pa(28);return a.ra.readlink(a)},stat(a,b){a=N(a,{Ka:!b}).node;return sb(a.ra.Ma,63)(a)},fstat(a){var b=O(a);a=b.node;var c=b.ua.Ma;b=c?b:a;c??=a.ra.Ma;sb(c,63);return c(b)},lstat(a){return H.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?
N(a,{Ka:!c}).node:a;Ab(null,a,b,c)},lchmod(a,b){H.chmod(a,b,!0)},fchmod(a,b){a=O(a);Ab(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?N(a,{Ka:!d}).node:a;wb(null,a,{timestamp:Date.now(),Gb:d})},lchown(a,b,c){H.chown(a,b,c,!0)},fchown(a){a=O(a);wb(a,a.node,{timestamp:Date.now(),Gb:!1})},truncate(a,b){if(0>b)throw new H.pa(28);a="string"==typeof a?N(a,{Ka:!0}).node:a;Bb(null,a,b)},Tc(a,b){a=O(a);if(0>b||0===(a.flags&2097155))throw new H.pa(28);Bb(a,a.node,b)},bd(a,b,c){a=N(a,{Ka:!0}).node;sb(a.ra.Oa,
63)(a,{atime:b,mtime:c})},open(a,b,c=438){if(""===a)throw new H.pa(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");var f=N(a,{Ka:!(b&131072),pc:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new H.pa(20);}else{if(e)throw new H.pa(31);d=H.Sa(a,c|511,0);f=!0}if(!d)throw new H.pa(44);8192===(d.mode&61440)&&(b&=-513);
if(b&65536&&!K(d.mode))throw new H.pa(54);if(!f&&(d?40960===(d.mode&61440)?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=K(d.mode)&&("r"!==e||b&576)?31:M(d,e)):e=44,e))throw new H.pa(e);b&512&&!f&&H.truncate(d,0);b&=-131713;b=tb({node:d,path:mb(d),flags:b,seekable:!0,position:0,ua:d.ua,zc:[],error:!1});b.ua.open&&b.ua.open(b);f&&H.chmod(d,c&511);return b},close(a){if(null===a.fd)throw new H.pa(8);a.rb&&(a.rb=null);try{a.ua.close&&a.ua.close(a)}catch(b){throw b;}finally{H.streams[a.fd]=null}a.fd=null},
Ia(a,b,c){if(null===a.fd)throw new H.pa(8);if(!a.seekable||!a.ua.Ia)throw new H.pa(70);if(0!=c&&1!=c&&2!=c)throw new H.pa(28);a.position=a.ua.Ia(a,b,c);a.zc=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new H.pa(28);if(null===a.fd)throw new H.pa(8);if(1===(a.flags&2097155))throw new H.pa(8);if(K(a.node.mode))throw new H.pa(31);if(!a.ua.read)throw new H.pa(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new H.pa(70);b=a.ua.read(a,b,c,d,e);f||(a.position+=b);return b},
write(a,b,c,d,e,f){if(0>d||0>e)throw new H.pa(28);if(null===a.fd)throw new H.pa(8);if(0===(a.flags&2097155))throw new H.pa(8);if(K(a.node.mode))throw new H.pa(31);if(!a.ua.write)throw new H.pa(28);a.seekable&&a.flags&1024&&H.Ia(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new H.pa(70);b=a.ua.write(a,b,c,d,e,f);h||(a.position+=b);return b},bb(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new H.pa(2);if(1===(a.flags&2097155))throw new H.pa(2);if(!a.ua.bb)throw new H.pa(43);
if(!b)throw new H.pa(28);return a.ua.bb(a,b,c,d,e)},ib(a,b,c,d,e){return a.ua.ib?a.ua.ib(a,b,c,d,e):0},tb(a,b,c){if(!a.ua.tb)throw new H.pa(59);return a.ua.tb(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&G(`Invalid encoding type "${b.encoding}"`);var c=H.open(a,b.flags);a=H.stat(a).size;var d=new Uint8Array(a);H.read(c,d,0,a,0);"utf8"===b.encoding&&(d=Ua(d));H.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=H.open(a,
c.flags,c.mode);"string"==typeof b&&(b=new Uint8Array(Ya(b)));ArrayBuffer.isView(b)?H.write(a,b,0,b.byteLength,void 0,c.Kc):G("Unsupported data type");H.close(a)},cwd:()=>H.Db,chdir(a){a=N(a,{Ka:!0});if(null===a.node)throw new H.pa(44);if(!K(a.node.mode))throw new H.pa(54);var b=M(a.node,"x");if(b)throw new H.pa(b);H.Db=a.path},Zc(){H.sb=!1;for(var a of H.streams)a&&H.close(a)},Qc(a,b){try{var c=N(a,{Ka:!b});a=c.path}catch(f){}var d=!1,e=null;try{c=N(a,{parent:!0}),Ma(a),c=N(a,{Ka:!b}),d=!0,e=c.node}catch(f){}return d?
e:null},Mc(a,b){a="string"==typeof a?a:mb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ka(a+"/"+c);try{H.mkdir(d)}catch(e){if(20!=e.Da)throw e;}a=d}}return d},Ya(a,b,c,d){a=Na("string"==typeof a?a:mb(a),b);b=fb(!!c,!!d);var e;(e=H.Ya).xb??(e.xb=64);e=H.Za(H.Ya.xb++,0);ab(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,h,k,m){for(var l=0,n=0;n<m;n++){try{var r=c()}catch(q){throw new H.pa(29);}if(void 0===r&&0===l)throw new H.pa(6);if(null===r||void 0===r)break;
l++;h[k+n]=r}l&&(f.node.atime=Date.now());return l},write(f,h,k,m){for(var l=0;l<m;l++)try{d(h[k+l])}catch(n){throw new H.pa(29);}m&&(f.node.mtime=f.node.ctime=Date.now());return l}});return zb(a,b,e)},Lc(a,b,c,d,e){class f{Ab=!1;Va=[];gb=void 0;Pb=0;Mb=0;get(l){if(!(l>this.length-1||0>l)){var n=l%this.chunkSize;return this.gb(l/this.chunkSize|0)[n]}}yc(l){this.gb=l}Sb(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);200<=l.status&&300>l.status||304===l.status||G("Couldn't load "+c+". Status: "+
l.status);var n=Number(l.getResponseHeader("Content-length")),r,q=(r=l.getResponseHeader("Accept-Ranges"))&&"bytes"===r;l=(r=l.getResponseHeader("Content-Encoding"))&&"gzip"===r;var t=1048576;q||(t=n);var v=this;v.yc(x=>{var B=x*t,A=(x+1)*t-1;A=Math.min(A,n-1);if("undefined"==typeof v.Va[x]){var z=v.Va;B>A&&G("invalid range ("+B+", "+A+") or no bytes requested!");A>n-1&&G("only "+n+" bytes available! programmer error!");var D=new XMLHttpRequest;D.open("GET",c,!1);n!==t&&D.setRequestHeader("Range",
"bytes="+B+"-"+A);D.responseType="arraybuffer";D.overrideMimeType&&D.overrideMimeType("text/plain; charset=x-user-defined");D.send(null);200<=D.status&&300>D.status||304===D.status||G("Couldn't load "+c+". Status: "+D.status);B=void 0!==D.response?new Uint8Array(D.response||[]):Ya(D.responseText||"");z[x]=B}"undefined"==typeof v.Va[x]&&G("doXHR failed!");return v.Va[x]});if(l||!n)t=n=1,t=n=this.gb(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.Pb=
n;this.Mb=t;this.Ab=!0}get length(){this.Ab||this.Sb();return this.Pb}get chunkSize(){this.Ab||this.Sb();return this.Mb}}if(globalThis.XMLHttpRequest){ca||G("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var h=new f;var k=void 0}else k=c,h=void 0;var m=Cb(a,b,d,e);h?m.va=h:k&&(m.va=null,m.url=k);Object.defineProperties(m,{Ca:{get:function(){return this.va.length}}});a={};for(const [l,n]of Object.entries(m.ua))a[l]=(...r)=>{Db(m);
return n(...r)};a.read=(l,n,r,q,t)=>{Db(m);l=l.node.va;if(t>=l.length)n=0;else{q=Math.min(l.length-t,q);if(l.slice)for(var v=0;v<q;v++)n[r+v]=l[t+v];else for(v=0;v<q;v++)n[r+v]=l.get(t+v);n=q}return n};a.bb=()=>{Db(m);G();throw new H.pa(48);};m.ua=a;return m}},P=(a,b,c)=>(a>>>=0)?Ua(w,a,b,c):"";function Eb(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?H.cwd():O(a).path;if(0==b.length){if(!c)throw new H.pa(44);return a}return a+"/"+b}
function Fb(a,b){E[a>>>2>>>0]=b.dev;E[a+4>>>2>>>0]=b.mode;E[a+8>>>2>>>0]=b.nlink;E[a+12>>>2>>>0]=b.uid;E[a+16>>>2>>>0]=b.gid;E[a+20>>>2>>>0]=b.rdev;F[a+24>>>3>>>0]=BigInt(b.size);C[a+32>>>2>>>0]=4096;C[a+36>>>2>>>0]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),e=b.ctime.getTime();F[a+40>>>3>>>0]=BigInt(Math.floor(c/1E3));E[a+48>>>2>>>0]=c%1E3*1E6;F[a+56>>>3>>>0]=BigInt(Math.floor(d/1E3));E[a+64>>>2>>>0]=d%1E3*1E6;F[a+72>>>3>>>0]=BigInt(Math.floor(e/1E3));E[a+80>>>2>>>0]=e%1E3*1E6;F[a+88>>>
3>>>0]=BigInt(b.ino);return 0}var Gb=void 0,Q=()=>{var a=C[+Gb>>>2>>>0];Gb+=4;return a},Hb={},Ib=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Jb(a){return this.wa(E[a>>>2>>>0])}
var Kb={},R={},Lb={},Mb=class extends Error{constructor(a){super(a);this.name="InternalError"}},T=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new Mb("Mismatched type converter count");for(var m=0;m<a.length;++m)S(a[m],k[m])}a.forEach(k=>Lb[k]=b);var e=Array(b.length),f=[],h=0;for(let [k,m]of b.entries())R.hasOwnProperty(m)?e[k]=R[m]:(f.push(m),Kb.hasOwnProperty(m)||(Kb[m]=[]),Kb[m].push(()=>{e[k]=R[m];++h;h===f.length&&d(e)}));0===f.length&&d(e)},U=a=>{a>>>=0;for(var b="";;){var c=
w[a++>>>0];if(!c)return b;b+=String.fromCharCode(c)}},V=class extends Error{constructor(a){super(a);this.name="BindingError"}},Nb=a=>{throw new V(a);};function Ob(a,b,c={}){var d=b.name;if(!a)throw new V(`type "${d}" must have a positive integer typeid pointer`);if(R.hasOwnProperty(a)){if(c.jc)return;throw new V(`Cannot register type '${d}' twice`);}R[a]=b;delete Lb[a];Kb.hasOwnProperty(a)&&(b=Kb[a],delete Kb[a],b.forEach(e=>e()))}function S(a,b,c={}){return Ob(a,b,c)}
var Pb=(a,b,c)=>{switch(b){case 1:return c?d=>u[d>>>0]:d=>w[d>>>0];case 2:return c?d=>y[d>>>1>>>0]:d=>ra[d>>>1>>>0];case 4:return c?d=>C[d>>>2>>>0]:d=>E[d>>>2>>>0];case 8:return c?d=>F[d>>>3>>>0]:d=>ua[d>>>3>>>0];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Qb=a=>{throw new V(a.qa.Aa.ta.name+" instance already deleted");},Rb=!1,Sb=()=>{},Tb=a=>{if(!globalThis.FinalizationRegistry)return Tb=b=>b,a;Rb=new FinalizationRegistry(b=>{b=b.qa;--b.count.value;0===b.count.value&&(b.Ga?
b.La.Qa(b.Ga):b.Aa.ta.Qa(b.xa))});Tb=b=>{var c=b.qa;c.Ga&&Rb.register(b,{qa:c},b);return b};Sb=b=>{Rb.unregister(b)};return Tb(a)},Ub=[];function Vb(){}
var Wb=(a,b)=>Object.defineProperty(b,"name",{value:a}),Xb={},Yb=(a,b,c)=>{if(void 0===a[b].sa){var d=a[b];a[b]=function(...e){if(!a[b].sa.hasOwnProperty(e.length))throw new V(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].sa})!`);return a[b].sa[e.length].apply(this,e)};a[b].sa=[];a[b].sa[d.Ra]=d}},Zb=(a,b)=>{var c="";b.some(d=>d.length!==a.length?!1:d.every((e,f)=>"emscripten::val"===e||"bigint"===typeof a[f]&&"number"===e||"object"===typeof a[f]&&
void 0!==R[e]&&void 0!==R[e].ta&&a[f]instanceof R[e].ta.constructor||typeof a[f]===e)?(c=d.join(", "),!0):!1);return c},$b=(a,b,c,d)=>{Yb(a,b,c);if(void 0!==a[b].sa&&void 0!==a[b].sa[d]&&void 0===a[b].sa[d].Ba){var e=a[b].sa[d];a[b].sa[d]=function(...f){var h=Zb(f,a[b].sa[f.length].Xa);if(!a[b].sa[f.length].Ba.hasOwnProperty(h))throw h=a[b].sa[f.length].Xa.map(k=>"("+k.map(m=>"string"===typeof m?m:R[m].name)+")"),f=f.map(k=>"object"===typeof k&&k.constructor&&k.constructor.name?k.constructor.name:
typeof k),new V(`Function '${c}' called with an invalid signature (${f}) - expects one of (${h})!`);return a[b].sa[f.length].Ba[h].apply(this,f)};a[b].sa[d].Ba={};a[b].sa[d].Ba[e.Wa]=e;a[b].sa[d].Xa=[];e.cb&&a[b].sa[d].Xa.push(e.cb)}},ac=(a,b)=>{if(g.hasOwnProperty(a))throw new V(`Cannot register public name '${a}' twice`);g[a]=b},bc=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};
function cc(a,b,c,d,e,f,h,k){this.name=a;this.constructor=b;this.ab=c;this.Qa=d;this.Ha=e;this.cc=f;this.kb=h;this.Zb=k;this.sc=[]}var dc=(a,b,c)=>{for(;b!==c;){if(!b.kb)throw new V(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.kb(a);b=b.Ha}return a},ec=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function fc(a,b){if(null===b){if(this.ub)throw new V(`null is not a valid ${this.name}`);return 0}if(!b.qa)throw new V(`Cannot pass "${ec(b)}" as a ${this.name}`);if(!b.qa.xa)throw new V(`Cannot pass deleted object as a pointer of type ${this.name}`);return dc(b.qa.xa,b.qa.Aa.ta,this.ta)}
function gc(a,b){if(null===b){if(this.ub)throw new V(`null is not a valid ${this.name}`);if(this.ob){var c=this.Bb();null!==a&&a.push(this.Qa,c);return c}return 0}if(!b||!b.qa)throw new V(`Cannot pass "${ec(b)}" as a ${this.name}`);if(!b.qa.xa)throw new V(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.nb&&b.qa.Aa.nb)throw new V(`Cannot convert argument of type ${b.qa.La?b.qa.La.name:b.qa.Aa.name} to parameter type ${this.name}`);c=dc(b.qa.xa,b.qa.Aa.ta,this.ta);if(this.ob){if(void 0===
b.qa.Ga)throw new V("Passing raw pointer to smart pointer is illegal");switch(this.xc){case 0:if(b.qa.La===this)c=b.qa.Ga;else throw new V(`Cannot convert argument of type ${b.qa.La?b.qa.La.name:b.qa.Aa.name} to parameter type ${this.name}`);break;case 1:c=b.qa.Ga;break;case 2:if(b.qa.La===this)c=b.qa.Ga;else{var d=b.clone();c=this.tc(c,W(()=>d["delete"]()));null!==a&&a.push(this.Qa,c)}break;default:throw new V("Unsupported sharing policy");}}return c}
function hc(a,b){if(null===b){if(this.ub)throw new V(`null is not a valid ${this.name}`);return 0}if(!b.qa)throw new V(`Cannot pass "${ec(b)}" as a ${this.name}`);if(!b.qa.xa)throw new V(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.qa.Aa.nb)throw new V(`Cannot convert argument of type ${b.qa.Aa.name} to parameter type ${this.name}`);return dc(b.qa.xa,b.qa.Aa.ta,this.ta)}
var ic=(a,b,c)=>{if(b===c)return a;if(void 0===c.Ha)return null;a=ic(a,b,c.Ha);return null===a?null:c.Zb(a)},jc={},kc=(a,b)=>{if(void 0===b)throw new V("ptr should not be undefined");for(;a.Ha;)b=a.kb(b),a=a.Ha;return jc[b]},lc=(a,b)=>{if(!b.Aa||!b.xa)throw new Mb("makeClassHandle requires ptr and ptrType");if(!!b.La!==!!b.Ga)throw new Mb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Tb(Object.create(a,{qa:{value:b,writable:!0}}))};
function mc(a,b,c,d,e,f,h,k,m,l,n){this.name=a;this.ta=b;this.ub=c;this.nb=d;this.ob=e;this.rc=f;this.xc=h;this.Nb=k;this.Bb=m;this.tc=l;this.Qa=n;e||void 0!==b.Ha?this.Ea=gc:(this.Ea=d?fc:hc,this.Fa=null)}
var nc=(a,b)=>{if(!g.hasOwnProperty(a))throw new Mb("Replacing nonexistent public symbol");g[a]=b;g[a].Ra=void 0;g[a].Wa=void 0;g[a].cb=void 0},oc=[],qc=a=>{var b=oc[a];b||(oc[a]=b=pc.get(a));return b},rc=(a,b,c=[])=>{b=qc(b)(...c);return"p"==a[0]?b>>>0:b},sc=(a,b)=>(...c)=>rc(a,b,c),X=(a,b)=>{a=U(a);var c=a.includes("p")?sc(a,b):qc(b);if("function"!=typeof c)throw new V(`unknown function pointer with signature ${a}: ${b}`);return c};class tc extends Error{}
var vc=a=>{a=uc(a);var b=U(a);Y(a);return b},wc=(a,b)=>{function c(f){e[f]||R[f]||(Lb[f]?Lb[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new tc(`${a}: `+d.map(vc).join([", "]));};function xc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].Fa)return!0;return!1}
function yc(a,b,c,d,e,f){var h=b.length;if(2>h)throw new V("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,m=xc(b);c=!b[0].Kb;var l=b[0],n=b[1];d=[a,Nb,d,e,Ib,l.wa.bind(l),n?.Ea.bind(n)];for(e=2;e<h;++e)l=b[e],d.push(l.Ea.bind(l));if(!m)for(e=k?1:2;e<b.length;++e)null!==b[e].Fa&&d.push(b[e].Fa);m=xc(b);e=b.length-2;n=[];l=["fn"];k&&l.push("thisWired");for(h=0;h<e;++h)n.push(`arg${h}`),l.push(`arg${h}Wired`);n=n.join(",");l=l.join(",");
n=`return function (${n}) {\n`;m&&(n+="var destructors = [];\n");var r=m?"destructors":"null",q="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");k&&(n+=`var thisWired = toClassParamWire(${r}, this);\n`);for(h=0;h<e;++h){var t=`toArg${h}Wire`;n+=`var arg${h}Wired = ${t}(${r}, arg${h});\n`;q.push(t)}n+=(c||f?"var rv = ":"")+`invoker(${l});\n`;if(m)n+="runDestructors(destructors);\n";else for(h=k?1:2;h<b.length;++h)f=1===h?"thisWired":"arg"+(h-2)+"Wired",
null!==b[h].Fa&&(n+=`${f}_dtor(${f});\n`,q.push(`${f}_dtor`));c&&(n+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(q,n+"}\n"))(...d);return Wb(a,b)}
var zc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(E[b+4*d>>>2>>>0]);return c},Ac=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Bc=a=>{var b=R[a];return"emscripten::val"===b.name?"emscripten::val":"std::string"===b.name||"std::wstring"===b.name?"string":"bool"===b.name?"boolean":"char;signed char;unsigned char;short;unsigned short;int;unsigned int;long;unsigned long;float;double;int64_t;uint64_t".split(";").includes(b.name)?"number":"string"===b.valueType?"string":"number"===b.valueType?
"number":a},Cc=[],Z=[0,1,,1,null,1,!0,1,!1,1];function Dc(a){a>>>=0;9<a&&0===--Z[a+1]&&(Z[a]=void 0,Cc.push(a))}
var Ec=a=>{if(!a)throw new V(`Cannot use deleted val. handle = ${a}`);return Z[a]},W=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Cc.pop()||Z.length;Z[b]=a;Z[b+1]=1;return b}},Fc={name:"emscripten::val",wa:a=>{var b=Ec(a);Dc(a);return b},Ea:(a,b)=>W(b),Ja:Jb,Fa:null},Gc=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.wa(u[d>>>0])}:function(d){return this.wa(w[d>>>0])};case 2:return c?function(d){return this.wa(y[d>>>1>>>0])}:function(d){return this.wa(ra[d>>>
1>>>0])};case 4:return c?function(d){return this.wa(C[d>>>2>>>0])}:function(d){return this.wa(E[d>>>2>>>0])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Hc=(a,b)=>{var c=R[a];if(void 0===c)throw a=`${b} has unknown type ${vc(a)}`,new V(a);return c},Ic=(a,b)=>{switch(b){case 4:return function(c){return this.wa(sa[c>>>2>>>0])};case 8:return function(c){return this.wa(ta[c>>>3>>>0])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Jc=globalThis.TextDecoder?
new TextDecoder("utf-16le"):void 0,Kc=(a,b,c)=>{a>>>=1;b=Ta(ra,a,b/2,c);if(16<b-a&&Jc)return Jc.decode(ra.subarray(a>>>0,b>>>0));for(c="";a<b;++a)c+=String.fromCharCode(ra[a>>>0]);return c},Lc=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)y[b>>>1>>>0]=a.charCodeAt(e),b+=2;y[b>>>1>>>0]=0;return b-d},Mc=a=>2*a.length,Nc=(a,b,c)=>{var d="";a>>>=2;for(var e=0;!(e>=b/4);e++){var f=E[a+e>>>0];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Oc=
(a,b,c)=>{b>>>=0;c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;C[b>>>2>>>0]=f;b+=4;if(b+4>c)break}C[b>>>2>>>0]=0;return b-d},Pc=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Qc=a=>{a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0},Sc=a=>{var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;
if("::"===a)return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(RegExp("[.]","g"),":"),a=a.split(":"),a[a.length-4]=Number(a[a.length-4])+256*Number(a[a.length-3]),a[a.length-3]=Number(a[a.length-2])+256*Number(a[a.length-1]),a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"==typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=Rc(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<
16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]},Tc=1,Uc={},Vc=[],Wc=a=>{var b=Vc.length;Vc.push(a);return b},Xc=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Hc(E[b+4*d>>>2>>>0],`parameter ${d}`);return c},Yc=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(E[b>>>2>>>0]=W(d));return a},Zc={},$c=a=>{var b=Zc[a];return void 0===b?U(a):b},ad=[0,31,60,91,121,152,182,213,244,274,305,335],bd=[0,31,59,90,120,151,181,212,243,273,304,334],ed=a=>{a=a.getArg(cd,0);return dd(a)};
H.Nc=(a,b,c,d,e,f,h,k,m,l)=>{nb(a,b,c,d,e,k,m,l).then(f).catch(h)};H.Yc=nb;H.Ta=Array(4096);H.za(J,{},"/");H.mkdir("/tmp");H.mkdir("/home");H.mkdir("/home/web_user");
(function(){H.mkdir("/dev");ab(H.Za(1,3),{read:()=>0,write:(d,e,f,h)=>h,Ia:()=>0});zb("/dev/null",H.Za(1,3));$a(H.Za(5,0),cb);$a(H.Za(6,0),db);zb("/dev/tty",H.Za(5,0));zb("/dev/tty1",H.Za(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Pa(a),b=a.byteLength);return a[--b]};H.Ya("/dev","random",c);H.Ya("/dev","urandom",c);H.mkdir("/dev/shm");H.mkdir("/dev/shm/tmp")})();
(function(){H.mkdir("/proc");var a=H.mkdir("/proc/self");H.mkdir("/proc/self/fd");H.za({za(){var b=H.createNode(a,"fd",16895,73);b.ua={Ia:J.ua.Ia};b.ra={lookup(c,d){c=+d;var e=O(c);c={parent:null,za:{Lb:"fake"},ra:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(H.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();H.bc={MEMFS:J};
(()=>{let a=Vb.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof Vb&&c instanceof Vb))return!1;var d=this.qa.Aa.ta,e=this.qa.xa;c.qa=c.qa;var f=c.qa.Aa.ta;for(c=c.qa.xa;d.Ha;)e=d.kb(e),d=d.Ha;for(;f.Ha;)c=f.kb(c),f=f.Ha;return d===f&&e===c},clone:function(){this.qa.xa||Qb(this);if(this.qa.jb)return this.qa.count.value+=1,this;var c=Tb,d=Object,e=d.create,f=Object.getPrototypeOf(this),h=this.qa;c=c(e.call(d,f,{qa:{value:{count:h.count,eb:h.eb,jb:h.jb,xa:h.xa,Aa:h.Aa,Ga:h.Ga,La:h.La}}}));
c.qa.count.value+=1;c.qa.eb=!1;return c},["delete"](){this.qa.xa||Qb(this);if(this.qa.eb&&!this.qa.jb)throw new V("Object already scheduled for deletion");Sb(this);var c=this.qa;--c.count.value;0===c.count.value&&(c.Ga?c.La.Qa(c.Ga):c.Aa.ta.Qa(c.xa));this.qa.jb||(this.qa.Ga=void 0,this.qa.xa=void 0)},isDeleted:function(){return!this.qa.xa},deleteLater:function(){this.qa.xa||Qb(this);if(this.qa.eb&&!this.qa.jb)throw new V("Object already scheduled for deletion");Ub.push(this);this.qa.eb=!0;return this}});
const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(mc.prototype,{ec(a){this.Nb&&(a=this.Nb(a));return a},Eb(a){this.Qa?.(a)},Ja:Jb,wa:function(a){function b(){return this.ob?lc(this.ta.ab,{Aa:this.rc,xa:c,La:this,Ga:a}):lc(this.ta.ab,{Aa:this,xa:a})}var c=this.ec(a);if(!c)return this.Eb(a),null;var d=kc(this.ta,c);if(void 0!==d){if(0===d.qa.count.value)return d.qa.xa=c,d.qa.Ga=a,d.clone();d=d.clone();this.Eb(a);return d}d=this.ta.cc(c);d=Xb[d];if(!d)return b.call(this);d=this.nb?d.Yb:d.pointerType;var e=ic(c,this.ta,d.ta);return null===
e?b.call(this):this.ob?lc(d.ta.ab,{Aa:d,xa:e,La:this,Ga:a}):lc(d.ta.ab,{Aa:d,xa:e})}});g.noExitRuntime&&(Ia=g.noExitRuntime);g.preloadPlugins&&(jb=g.preloadPlugins);g.print&&(ma=g.print);g.printErr&&(p=g.printErr);g.wasmBinary&&(na=g.wasmBinary);if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.shift()();g.FS=H;g.incrementExceptionRefcount=a=>{a=ed(a);fd(a)};g.decrementExceptionRefcount=a=>{a=ed(a);gd(a)};
g.getExceptionMessage=a=>{var b=ed(a);a=hd();var c=jd(4),d=jd(4);kd(b,c,d);b=E[c>>>2>>>0];d=E[d>>>2>>>0];c=P(b);Y(b);if(d){var e=P(d);Y(d)}ld(a);return[c,e]};
var uc,md,Y,Rc,ya,ld,jd,hd,gd,fd,dd,kd,cd,xa,pc,nd={_:function(){return g.Ac.length},Z:function(a,b){a>>>=0;try{return a=P(a),H.chmod(a,b),0}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return-c.Da}},Y:function(a,b,c){b>>>=0;try{b=P(b);b=Eb(a,b);if(c&-8)return-28;var d=N(b,{Ka:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&M(d,a)?-2:0}catch(e){if("undefined"==typeof H||"ErrnoError"!==e.name)throw e;return-e.Da}},w:function(a,b,c){Gb=c>>>0;try{var d=
O(a);switch(b){case 0:var e=Q();if(0>e)break;for(;H.streams[e];)e++;return vb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Q(),d.flags|=e,0;case 12:return e=Q(),y[e+0>>>1>>>0]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof H||"ErrnoError"!==f.name)throw f;return-f.Da}},X:function(a,b){try{return Fb(b>>>0,H.fstat(a))}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return-c.Da}},W:function(a,b,c){Gb=c>>>0;try{var d=O(a);switch(b){case 21509:return d.tty?
0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Ua.kc){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Q();C[e>>>2>>>0]=25856;C[e+4>>>2>>>0]=5;C[e+8>>>2>>>0]=191;C[e+12>>>2>>>0]=35387;for(var f=0;32>f;f++)u[e+f+17>>>0]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Ua.lc)for(e=Q(),a=[],f=0;32>f;f++)a.push(u[e+f+17>>>0]);return 0;case 21519:if(!d.tty)return-59;e=Q();return C[e>>>2>>>
0]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:return e=Q(),H.tb(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Ua.mc&&(f=[24,80],e=Q(),y[e>>>1>>>0]=f[0],y[e+2>>>1>>>0]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof H||"ErrnoError"!==h.name)throw h;return-h.Da}},V:function(a,b){a>>>=0;b>>>=0;try{return a=P(a),Fb(b,H.lstat(a))}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return-c.Da}},U:function(a,
b,c,d){b>>>=0;c>>>=0;try{b=P(b);var e=d&256;b=Eb(a,b,d&4096);return Fb(c,e?H.lstat(b):H.stat(b))}catch(f){if("undefined"==typeof H||"ErrnoError"!==f.name)throw f;return-f.Da}},B:function(a,b,c,d){b>>>=0;Gb=d>>>=0;try{b=P(b);b=Eb(a,b);var e=d?Q():0;return H.open(b,c,e).fd}catch(f){if("undefined"==typeof H||"ErrnoError"!==f.name)throw f;return-f.Da}},T:function(a,b){a>>>=0;b>>>=0;try{return a=P(a),Fb(b,H.stat(a))}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return-c.Da}},P:()=>G(""),
f:function(a){a>>>=0;var b=Hb[a];delete Hb[a];var c=b.Bb,d=b.Qa,e=b.Hb,f=e.map(h=>h.ic).concat(e.map(h=>h.vc));T([a],f,h=>{var k={},m,l;for([m,l]of e.entries()){const n=h[m],r=l.gb,q=l.hc,t=h[m+e.length],v=l.uc,x=l.wc;k[l.ac]={read:B=>n.wa(r(q,B)),write:(B,A)=>{var z=[];v(x,B,t.Ea(z,A));Ib(z)},optional:n.optional}}return[{name:b.name,wa:n=>{var r={},q;for(q in k)r[q]=k[q].read(n);d(n);return r},Ea:(n,r)=>{for(var q in k)if(!(q in r||k[q].optional))throw new TypeError(`Missing field: "${q}"`);var t=
c();for(q in k)k[q].write(t,r[q]);null!==n&&n.push(d,t);return t},Ja:Jb,Fa:d}]})},z:function(a,b,c,d,e){a>>>=0;c>>>=0;b=U(b>>>0);d=0n===d;let f=h=>h;if(d){const h=8*c;f=k=>BigInt.asUintN(h,k);e=f(e)}S(a,{name:b,wa:f,Ea:(h,k)=>{"number"==typeof k&&(k=BigInt(k));return k},Ja:Pb(b,c,!d),Fa:null})},O:function(a,b,c,d){b=U(b>>>0);S(a>>>0,{name:b,wa:function(e){return!!e},Ea:function(e,f){return f?c:d},Ja:function(e){return this.wa(w[e>>>0])},Fa:null})},d:function(a,b,c,d,e,f,h,k,m,l,n,r,q){a>>>=0;b>>>=
0;c>>>=0;d>>>=0;f>>>=0;h>>>=0;k>>>=0;m>>>=0;l>>>=0;n>>>=0;r>>>=0;q>>>=0;n=U(n);f=X(e>>>0,f);k&&=X(h,k);l&&=X(m,l);q=X(r,q);var t=bc(n);ac(t,function(){wc(`Cannot construct ${n} due to unbound types`,[d])});T([a,b,c],d?[d]:[],v=>{v=v[0];if(d){var x=v.ta;var B=x.ab}else B=Vb.prototype;v=Wb(n,function(...I){if(Object.getPrototypeOf(this)!==A)throw new V(`Use 'new' to construct ${n}`);if(void 0===z.ya)throw new V(`${n} has no accessible constructor`);var ba=void 0;void 0!==z.ya[I.length]&&(void 0!==z.ya[I.length].fb?
ba=z.ya[I.length].fb:(ba=Zb(I,z.ya[I.length].Xa),ba=z.ya[I.length].Ba[ba]));if(void 0===ba){if(void 0===z.ya[I.length])throw new V(`Tried to invoke ctor of ${n} with invalid number of parameters (${I.length}) - expected (${Object.keys(z.ya).toString()}) parameters instead!`);ba=z.ya[I.length].Xa.map(fa=>"("+fa.map(ub=>"string"===typeof ub?ub:R[ub].name)+")");I=I.map(fa=>"object"===typeof fa&&fa.constructor&&fa.constructor.name?fa.constructor.name:typeof fa);throw new V(`Tried to invoke ctor of ${n} with invalid signature (${I}) - expected [${ba}] parameters instead!`);
}return ba.apply(this,I)});var A=Object.create(B,{constructor:{value:v}});v.prototype=A;var z=new cc(n,v,A,q,x,f,k,l);if(z.Ha){var D;(D=z.Ha).lb??(D.lb=[]);z.Ha.lb.push(z)}x=new mc(n,z,!0,!1,!1);D=new mc(n+"*",z,!1,!1,!1);B=new mc(n+" const*",z,!1,!0,!1);Xb[a]={pointerType:D,Yb:B};nc(t,v);return[x,D,B]})},c:function(a,b,c,d,e,f,h,k){a>>>=0;b>>>=0;e>>>=0;f>>>=0;h>>>=0;var m=zc(c,d>>>0);b=U(b);b=Ac(b);f=X(e,f);T([],[a],l=>{function n(){wc(`Cannot call ${r} due to unbound types`,m)}l=l[0];var r=`${l.name}.${b}`;
b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var q=l.ta.constructor,t=m.slice(1),v=t.join(", ");void 0===q[b]?(n.Ra=c-1,q[b]=n):void 0===q[b].sa&&q[b].Ra!==c-1||void 0!==q[b].sa&&void 0===q[b].sa[c-1]?(Yb(q,b,r),n.Wa=v,q[b].sa[c-1]=n):($b(q,b,r,c-1),q[b].sa[c-1].Ba[v]=n);T([],m,x=>{x=[x[0],null].concat(x.slice(1));x=yc(r,x,null,f,h,k);var B=t.map(z=>Bc(z)),A=B.join(", ");void 0===q[b].sa?(x.Ra=c-1,x.Wa=A,x.cb=B,q[b]=x):void 0===q[b].sa[c-1].Ba?(x.Wa=A,x.cb=B,q[b].sa[c-1]=x):(delete q[b].sa[c-1].Ba[v],
q[b].sa[c-1].Ba[A]=x,q[b].sa[c-1].Xa.push(B));if(l.ta.lb)for(const z of l.ta.lb)z.constructor.hasOwnProperty(b)||(z.constructor[b]=x);return[]});return[]})},b:function(a,b,c,d,e,f){a>>>=0;d>>>=0;e>>>=0;f>>>=0;var h=zc(b,c>>>0);e=X(d,e);T([],[a],k=>{function m(){wc(`Cannot construct ${k.name} due to unbound types`,h)}k=k[0];var l=`constructor ${k.name}`;void 0===k.ta.ya&&(k.ta.ya=[]);var n=h.slice(1),r=n.join(", ");if(void 0!==k.ta.ya[b-1]&&void 0!==k.ta.ya[b-1].Ba[r])throw new V(`Cannot register multiple constructors with identical javascript types of parameters for class '${k.name}'!`);
void 0===k.ta.ya[b-1]?k.ta.ya[b-1]={fb:m,Ba:{},Xa:[]}:delete k.ta.ya[b-1].fb;k.ta.ya[b-1].Ba[r]=m;T([],h,q=>{q.splice(1,0,null);delete k.ta.ya[b-1].Ba[r];q=yc(l,q,null,e,f);var t=n.map(x=>Bc(x)),v=t.join(", ");void 0!==k.ta.ya[b-1].fb&&(k.ta.ya[b-1].fb=q);k.ta.ya[b-1].Ba[v]=q;k.ta.ya[b-1].Xa.push(t);return[]});return[]})},a:function(a,b,c,d,e,f,h,k,m){a>>>=0;b>>>=0;e>>>=0;f>>>=0;h>>>=0;var l=zc(c,d>>>0);b=U(b);b=Ac(b);f=X(e,f);T([],[a],n=>{function r(){wc(`Cannot call ${q} due to unbound types`,l)}
n=n[0];var q=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&n.ta.sc.push(b);var t=n.ta.ab,v=t[b],x=l.slice(2),B=x.join(", ");void 0===v||void 0===v.sa&&v.className!==n.name&&v.Wa===B?(r.Ra=c-2,r.Wa=B,r.className=n.name,t[b]=r):void 0===t[b].sa&&t[b].Ra!==c-2||void 0!==t[b].sa&&void 0===t[b].sa[c-2]?(Yb(t,b,q),r.Wa=B,t[b].sa[c-2]=r):($b(t,b,q,c-2),t[b].sa[c-2].Ba[B]=r);T([],l,A=>{A=yc(q,A,n,f,h,m);var z=x.map(I=>Bc(I)),D=z.join(", ");void 0===t[b].sa?(A.Ra=c-2,A.Wa=D,A.cb=z,t[b]=
A):void 0===t[b].sa[c-2].Ba?(A.Wa=D,A.cb=z,t[b].sa[c-2]=A):(delete t[b].sa[c-2].Ba[B],t[b].sa[c-2].Ba[D]=A,t[b].sa[c-2].Xa.push(z));return[]});return[]})},N:function(a){return S(a>>>0,Fc)},k:function(a,b,c,d,e){a>>>=0;c>>>=0;b=U(b>>>0);e=0===e?"object":1===e?"number":"string";switch(e){case "object":function h(){}h.values={};S(a,{name:b,constructor:h,valueType:e,wa:function(k){return this.constructor.values[k]},Ea:(k,m)=>m.value,Ja:Gc(b,c,d),Fa:null});ac(b,h);break;case "number":var f={};S(a,{name:b,
wb:f,valueType:e,wa:k=>k,Ea:(k,m)=>m,Ja:Gc(b,c,d),Fa:null});ac(b,f);delete g[b].Ra;break;case "string":f={},S(a,{name:b,Tb:{},Ob:{},wb:f,valueType:e,wa:function(k){return this.Ob[k]},Ea:function(k,m){return this.Tb[m]},Ja:Gc(b,c,d),Fa:null}),ac(b,f),delete g[b].Ra}},i:function(a,b,c){b>>>=0;var d=Hc(a>>>0,"enum");b=U(b);switch(d.valueType){case "object":a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Wb(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=
d;break;case "number":d.wb[b]=c;break;case "string":d.Tb[b]=c,d.Ob[c]=b,d.wb[b]=b}},y:function(a,b,c){b=U(b>>>0);S(a>>>0,{name:b,wa:d=>d,Ea:(d,e)=>e,Ja:Ic(b,c>>>0),Fa:null})},s:function(a,b,c,d,e){a>>>=0;c>>>=0;b=U(b>>>0);let f=k=>k;if(0===d){var h=32-8*c;f=k=>k<<h>>>h;e=f(e)}S(a,{name:b,wa:f,Ea:(k,m)=>m,Ja:Pb(b,c,0!==d),Fa:null})},m:function(a,b,c){function d(f){return new e(u.buffer,E[f+4>>>2>>>0],E[f>>>2>>>0])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,
Float64Array,BigInt64Array,BigUint64Array][b];c=U(c>>>0);S(a>>>0,{name:c,wa:d,Ja:d},{jc:!0})},h:function(a,b,c,d,e,f,h,k,m,l,n,r){a>>>=0;b>>>=0;c>>>=0;f>>>=0;h>>>=0;k>>>=0;m>>>=0;l>>>=0;n>>>=0;r>>>=0;c=U(c);f=X(e>>>0,f);k=X(h,k);l=X(m,l);r=X(n,r);T([a],[b],q=>{q=q[0];return[new mc(c,q.ta,!1,!1,!0,q,d,f,k,l,r)]})},M:function(a,b){b=U(b>>>0);S(a>>>0,{name:b,wa(c){var d=P(c+4,E[c>>>2>>>0],!0);Y(c);return d},Ea(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&
1==d.BYTES_PER_ELEMENT))throw new V("Cannot pass non-string to std::string");var f=e?Wa(d):d.length;var h=md(4+f+1),k=h+4;E[h>>>2>>>0]=f;e?Xa(d,w,k,f+1):w.set(d,k>>>0);null!==c&&c.push(Y,h);return h},Ja:Jb,Fa(c){Y(c)}})},u:function(a,b,c){b>>>=0;c>>>=0;c=U(c);if(2===b){var d=Kc;var e=Lc;var f=Mc}else d=Nc,e=Oc,f=Pc;S(a>>>0,{name:c,wa:h=>{var k=d(h+4,E[h>>>2>>>0]*b,!0);Y(h);return k},Ea:(h,k)=>{if("string"!=typeof k)throw new V(`Cannot pass non-string to C++ string type ${c}`);var m=f(k),l=md(4+m+
b);E[l>>>2>>>0]=m/b;e(k,l+4,m+b);null!==h&&h.push(Y,l);return l},Ja:Jb,Fa(h){Y(h)}})},g:function(a,b,c,d,e,f){e>>>=0;f>>>=0;Hb[a>>>0]={name:U(b>>>0),Bb:X(c>>>0,d>>>0),Qa:X(e,f),Hb:[]}},e:function(a,b,c,d,e,f,h,k,m,l){f>>>=0;h>>>=0;k>>>=0;m>>>=0;l>>>=0;Hb[a>>>0].Hb.push({ac:U(b>>>0),ic:c>>>0,gb:X(d>>>0,e>>>0),hc:f,vc:h,uc:X(k,m),wc:l})},L:function(a,b){b=U(b>>>0);S(a>>>0,{Kb:!0,name:b,wa:()=>{},Ea:()=>{}})},K:function(a){a=P(a>>>0);var b=Qc(a);null===b&&(b=Sc(a),null===b&&(Uc[a]?b=Uc[a]:(b=Tc++,b=
"172.29."+(b&255)+"."+(b&65280),Uc[a]=b),a=b));return Qc(a)},q:function(a,b,c){var [d,...e]=Xc(a,b>>>0);b=d.Ea.bind(d);var f=e.map(m=>m.Ja.bind(m));a--;var h={toValue:Ec};a=f.map((m,l)=>{var n=`argFromPtr${l}`;h[n]=m;return`${n}(args${l?"+"+8*l:""})`});switch(c){case 0:var k="toValue(handle)";break;case 2:k="new (toValue(handle))";break;case 3:k="";break;case 1:h.getStringOrSymbol=$c,k="toValue(handle)[getStringOrSymbol(methodName)]"}k+=`(${a})`;d.Kb||(h.toReturnWire=b,h.emval_returnValue=Yc,k=`return emval_returnValue(toReturnWire, destructorsRef, ${k})`);
k=`return function (handle, methodName, destructorsRef, args) {\n${k}\n}`;c=(new Function(Object.keys(h),k))(...Object.values(h));k=`methodCaller<(${e.map(m=>m.name)}) => ${d.name}>`;return Wc(Wb(k,c))},j:Dc,n:function(a){a>>>=0;if(!a)return W(globalThis);a=$c(a);return W(globalThis[a])},t:function(a){a=$c(a>>>0);return W(g[a])},J:function(a,b){b>>>=0;a=Ec(a>>>0);b=Ec(b);return W(a[b])},r:function(a){a>>>=0;9<a&&(Z[a+1]+=1)},x:function(a,b){b>>>=0;a=Ec(a>>>0);b=Ec(b);return a instanceof b},p:function(a,
b,c,d,e){return Vc[a>>>0](b>>>0,c>>>0,d>>>0,e>>>0)},o:function(a){a>>>=0;var b=Ec(a);Ib(b);Dc(a)},l:function(a){a=Ec(a>>>0);return W(typeof a)},I:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);C[b>>>2>>>0]=a.getSeconds();C[b+4>>>2>>>0]=a.getMinutes();C[b+8>>>2>>>0]=a.getHours();C[b+12>>>2>>>0]=a.getDate();C[b+16>>>2>>>0]=a.getMonth();C[b+20>>>2>>>0]=a.getFullYear()-1900;C[b+24>>>2>>>0]=a.getDay();var c=a.getFullYear();C[b+28>>>2>>>0]=(0!==c%4||0===c%
100&&0!==c%400?bd:ad)[a.getMonth()]+a.getDate()-1|0;C[b+36>>>2>>>0]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();C[b+32>>>2>>>0]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},H:function(a,b,c,d){c>>>=0;d>>>=0;var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();E[a>>>0>>>2>>>0]=60*Math.max(f,e);C[b>>>0>>>2>>>0]=Number(f!=e);b=h=>{var k=Math.abs(h);
return`UTC${0<=h?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(Xa(a,w,c,17),Xa(b,w,d,17)):(Xa(a,w,d,17),Xa(b,w,c,17))},S:function(a,b,c){if(!(0<=a&&3>=a))return 28;F[c>>>0>>>3>>>0]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},G:()=>Date.now(),F:function(a,b,c){b>>>=0;var d=Error().stack.toString(),e=d.split("\n");d="";var f=RegExp("\\s*(.*?)@(.*?):([0-9]+):([0-9]+)"),h=RegExp("\\s*at (.*?) \\((.*):(.*):(.*)\\)"),k;
for(k of e){var m=h.exec(k);if(5==m?.length){e=m[1];var l=m[2];var n=m[3];m=m[4]}else if(m=f.exec(k),4<=m?.length)e=m[1],l=m[2],n=m[3],m=m[4]|0;else{d+=k+"\n";continue}"_emscripten_log"==e||"_emscripten_get_callstack"==e?d="":a&24&&(a&64&&(l=l.substring(l.replace(/\\/g,"/").lastIndexOf("/")+1)),d+=`    at ${e} (${l}:${n}:${m})\n`)}a=d=d.replace(/\s+$/,"");return!b||0>=c?Wa(a)+1:Xa(a,w,b,c)+1},E:function(){return 4294901760},D:function(a){a>>>=0;var b=w.length;if(4294901760<a)return!1;for(var c=1;4>=
c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(4294901760,65536*Math.ceil(Math.max(a,d)/65536))-xa.buffer.byteLength+65535)/65536|0;try{xa.grow(d);wa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},C:a=>{Ia||(g.onExit?.(a),oa=!0);ea(a,new Da(a))},v:function(a){try{var b=O(a);H.close(b);return 0}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return c.Da}},R:function(a,b,c,d){b>>>=0;c>>>=0;d>>>=0;try{a:{var e=O(a);a=b;for(var f,h=b=0;h<c;h++){var k=
E[a>>>2>>>0],m=E[a+4>>>2>>>0];a+=8;var l=H.read(e,u,k,m,f);if(0>l){var n=-1;break a}b+=l;if(l<m)break;"undefined"!=typeof f&&(f+=l)}n=b}E[d>>>2>>>0]=n;return 0}catch(r){if("undefined"==typeof H||"ErrnoError"!==r.name)throw r;return r.Da}},Q:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);d>>>=0;try{if(isNaN(b))return 61;var e=O(a);H.Ia(e,b,c);F[d>>>3>>>0]=BigInt(e.position);e.rb&&0===b&&0===c&&(e.rb=null);return 0}catch(f){if("undefined"==typeof H||"ErrnoError"!==f.name)throw f;
return f.Da}},A:function(a,b,c,d){b>>>=0;c>>>=0;d>>>=0;try{a:{var e=O(a);a=b;for(var f,h=b=0;h<c;h++){var k=E[a>>>2>>>0],m=E[a+4>>>2>>>0];a+=8;var l=H.write(e,u,k,m,f);if(0>l){var n=-1;break a}b+=l;if(l<m)break;"undefined"!=typeof f&&(f+=l)}n=b}E[d>>>2>>>0]=n;return 0}catch(r){if("undefined"==typeof H||"ErrnoError"!==r.name)throw r;return r.Da}}};function od(){var a=pd;a=Object.assign({},a);var b=c=>d=>c(d)>>>0;a.ba=b(a.ba);a.da=b(a.da);a.ja=b(a.ja);a.ka=(c=>()=>c()>>>0)(a.ka);return a}
function qd(){function a(){g.calledRun=!0;if(!oa){va=!0;g.noFSInit||H.sb||kb();pd.aa();H.Jb=!1;pa?.(g);g.onRuntimeInitialized?.();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Fa.push(b)}Ea(Fa)}}if(0<hb)ib=qd;else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ha();Ea(Ga);0<hb?ib=qd:g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);a()},1)):a()}}var pd;
pd=await (async function(){function a(c){pd=c.exports;c=pd=od();uc=c.ba;md=c.da;Y=c.ea;Rc=c.ga;ya=c.ha;ld=c.ia;jd=c.ja;hd=c.ka;gd=c.la;fd=c.ma;dd=c.na;kd=c.oa;xa=g.wasmMemory=c.$;pc=c.ca;cd=c.fa;wa();return pd}var b={a:nd};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{c(a(d,e))})});za??=g.locateFile?g.locateFile?g.locateFile("replicad_single.wasm",ia):ia+"replicad_single.wasm":(new URL("replicad_single.wasm",import.meta.url)).href;return a((await Ca(b)).instance)}());
qd();va?moduleRtn=g:moduleRtn=new Promise((a,b)=>{pa=a;qa=b});
;return moduleRtn}export default Module;
