async function Module(moduleArg={}){var moduleRtn;var f=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;if(ca){const {createRequire:a}=await import("node:module");var require=a(import.meta.url)}var da=(a,b)=>{throw b;},ea=import.meta.url,fa="",ha,ia;
if(ca){var fs=require("node:fs");ea.startsWith("file:")&&(fa=require("node:path").dirname(require("node:url").fileURLToPath(ea))+"/");ia=a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a)};ha=async a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);da=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{fa=(new URL(".",ea)).href}catch{}ba&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ha=async a=>{if(ja(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ka=console.log.bind(console),p=console.error.bind(console),la,ma=!1,ja=a=>a.startsWith("file://"),na,oa,u,w,x,pa,y,z,qa,ra,A,sa,ta=!1;
function ua(){var a=va.buffer;u=new Int8Array(a);x=new Int16Array(a);w=new Uint8Array(a);pa=new Uint16Array(a);y=new Int32Array(a);z=new Uint32Array(a);qa=new Float32Array(a);ra=new Float64Array(a);A=new BigInt64Array(a);sa=new BigUint64Array(a)}function D(a){f.onAbort?.(a);a="Aborted("+a+")";p(a);ma=!0;a+=". Build with -sASSERTIONS for more info.";ta&&wa();a=new WebAssembly.RuntimeError(a);oa?.(a);throw a;}var xa;
async function ya(a){if(!la)try{var b=await ha(a);return new Uint8Array(b)}catch{}if(a==xa&&la)a=new Uint8Array(la);else if(ia)a=ia(a);else throw"both async and sync fetching of the wasm failed";return a}async function za(a,b){try{var c=await ya(a);return await WebAssembly.instantiate(c,b)}catch(d){p(`failed to asynchronously prepare wasm: ${d}`),D(d)}}
async function Aa(a){var b=xa;if(!la&&!ja(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){p(`wasm streaming compile failed: ${d}`),p("falling back to ArrayBuffer instantiation")}return za(b,a)}class Ba{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ca=a=>{for(;0<a.length;)a.shift()(f)},Da=[],Ea=[],Fa=()=>{var a=f.preRun.shift();Ea.push(a)},Ga=!0,Ha=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ia=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ha(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ja=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},E=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Ka=(a,b)=>Ia(a+"/"+b),La=()=>{if(ca){var a=require("node:crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Ma=a=>{(Ma=La())(a)},Na=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:H.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ha(b.split("/").filter(e=>!!e),!c).join("/");
return(c?"/":"")+b||"."},Oa=(a,b)=>{function c(h){for(var k=0;k<h.length&&""===h[k];k++);for(var m=h.length-1;0<=m&&""===h[m];m--);return k>m?[]:h.slice(k,m-k+1)}a=Na(a).slice(1);b=Na(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Pa=globalThis.TextDecoder&&new TextDecoder,Qa=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},
Ra=(a,b=0,c,d)=>{b>>>=0;c=Qa(a,b,c,d);if(16<c-b&&a.buffer&&Pa)return Pa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Sa=[],Ta=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:
2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ua=(a,b,c,d)=>{c>>>=0;if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(c>=d)break;b[c++>>>0]=h}else if(2047>=h){if(c+1>=d)break;b[c++>>>0]=192|h>>6;b[c++>>>0]=128|h&63}else if(65535>=h){if(c+2>=d)break;b[c++>>>0]=224|h>>12;b[c++>>>0]=128|h>>6&63;b[c++>>>0]=128|h&63}else{if(c+3>=d)break;b[c++>>>0]=240|h>>18;b[c++>>>0]=128|h>>12&63;b[c++>>>0]=128|h>>6&63;b[c++>>>0]=128|h&63;g++}}b[c>>>0]=0;return c-
e},Va=a=>{var b=Array(Ta(a)+1);a=Ua(a,b,0,b.length);b.length=a;return b},Wa=[];function Xa(a,b){Wa[a]={input:[],output:[],Va:b};Ya(a,Za)}
var Za={open(a){var b=Wa[a.node.rdev];if(!b)throw new H.sa(43);a.tty=b;a.seekable=!1},close(a){a.tty.Va.fsync(a.tty)},fsync(a){a.tty.Va.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Va.Gb)throw new H.sa(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.Va.Gb(a.tty)}catch(k){throw new H.sa(29);}if(void 0===h&&0===e)throw new H.sa(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Va.xb)throw new H.sa(60);try{for(var e=0;e<d;e++)a.tty.Va.xb(a.tty,
b[c+e])}catch(g){throw new H.sa(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},$a={Gb(){a:{if(!Sa.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Sa=Va(a)}a=Sa.shift()}return a},xb(a,b){null===b||10===b?(ka(Ra(a.output)),a.output=[]):
0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ka(Ra(a.output)),a.output=[])},ic(){return{Fc:25856,Hc:5,Ec:191,Gc:35387,Dc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},jc(){return 0},kc(){return[24,80]}},ab={xb(a,b){null===b||10===b?(p(Ra(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(p(Ra(a.output)),a.output=[])}},I={Qa:null,Aa(){return I.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||H.isFIFO(c))throw new H.sa(63);
I.Qa||(I.Qa={dir:{node:{Na:I.ua.Na,Pa:I.ua.Pa,lookup:I.ua.lookup,Ta:I.ua.Ta,rename:I.ua.rename,unlink:I.ua.unlink,rmdir:I.ua.rmdir,readdir:I.ua.readdir,symlink:I.ua.symlink},stream:{Ja:I.va.Ja}},file:{node:{Na:I.ua.Na,Pa:I.ua.Pa},stream:{Ja:I.va.Ja,read:I.va.read,write:I.va.write,bb:I.va.bb,gb:I.va.gb}},link:{node:{Na:I.ua.Na,Pa:I.ua.Pa,readlink:I.ua.readlink},stream:{}},Ab:{node:{Na:I.ua.Na,Pa:I.ua.Pa},stream:H.Vb}});c=H.createNode(a,b,c,d);J(c.mode)?(c.ua=I.Qa.dir.node,c.va=I.Qa.dir.stream,c.wa=
{}):H.isFile(c.mode)?(c.ua=I.Qa.file.node,c.va=I.Qa.file.stream,c.Da=0,c.wa=null):40960===(c.mode&61440)?(c.ua=I.Qa.link.node,c.va=I.Qa.link.stream):8192===(c.mode&61440)&&(c.ua=I.Qa.Ab.node,c.va=I.Qa.Ab.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.wa[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Sc(a){return a.wa?a.wa.subarray?a.wa.subarray(0,a.Da):new Uint8Array(a.wa):new Uint8Array(0)},ua:{Na(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=
0;b.rdev=a.rdev;J(a.mode)?b.size=4096:H.isFile(a.mode)?b.size=a.Da:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Pa(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Da!=b&&(0==b?(a.wa=null,a.Da=0):(c=a.wa,a.wa=new Uint8Array(b),c&&a.wa.set(c.subarray(0,Math.min(b,a.Da))),a.Da=b)))},lookup(){I.ob||(I.ob=
new H.sa(44),I.ob.stack="<generic error, no stack>");throw I.ob;},Ta(a,b,c,d){return I.createNode(a,b,c,d)},rename(a,b,c){try{var d=K(b,c)}catch(g){}if(d){if(J(a.mode))for(var e in d.wa)throw new H.sa(55);bb(d)}delete a.parent.wa[a.name];b.wa[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.wa[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=K(a,b),d;for(d in c.wa)throw new H.sa(55);delete a.wa[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.wa)]},
symlink(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new H.sa(28);return a.link}},va:{read(a,b,c,d,e){var g=a.node.wa;if(e>=a.node.Da)return 0;a=Math.min(a.node.Da-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===u.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.wa||a.wa.subarray)){if(g)return a.wa=b.subarray(c,c+d),a.Da=d;if(0===a.Da&&
0===e)return a.wa=b.slice(c,c+d),a.Da=d;if(e+d<=a.Da)return a.wa.set(b.subarray(c,c+d),e),d}g=e+d;var h=a.wa?a.wa.length:0;h>=g||(g=Math.max(g,h*(1048576>h?2:1.125)>>>0),0!=h&&(g=Math.max(g,256)),h=a.wa,a.wa=new Uint8Array(g),0<a.Da&&a.wa.set(h.subarray(0,a.Da),0));if(a.wa.subarray&&b.subarray)a.wa.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.wa[e+g]=b[c+g];a.Da=Math.max(a.Da,e+d);return d},Ja(a,b,c){1===c?b+=a.position:2===c&&H.isFile(a.node.mode)&&(b+=a.node.Da);if(0>b)throw new H.sa(28);return b},
bb(a,b,c,d,e){if(!H.isFile(a.node.mode))throw new H.sa(43);a=a.node.wa;if(e&2||!a||a.buffer!==u.buffer){d=!0;D();e=void 0;if(!e)throw new H.sa(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);u.set(a,e>>>0)}}else d=!1,e=a.byteOffset;return{za:e,zc:d}},gb(a,b,c,d){I.va.write(a,b,0,d,c,!1);return 0}}},cb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},db=async a=>{a=await ha(a);return new Uint8Array(a)},eb=0,fb=null,gb=[],ib=async(a,b)=>{"undefined"!=
typeof Browser&&hb();for(var c of gb)if(c.canHandle(b))return c.handle(a,b);return a},kb=async(a,b,c,d,e,g,h,k)=>{var m=b?Na(Ia(a+"/"+b)):a;eb++;f.monitorRunDependencies?.(eb);try{var l=c;"string"==typeof c&&(l=await db(c));l=await ib(l,m);k?.();if(!g){c=b;a&&(a="string"==typeof a?a:jb(a),c=b?Ia(a+"/"+b):a);var n=cb(d,e),q=H.create(c,n);if(l){if("string"==typeof l){var r=Array(l.length);b=0;for(var t=l.length;b<t;++b)r[b]=l.charCodeAt(b);l=r}H.chmod(q,n|146);var v=H.open(q,577);H.write(v,l,0,l.length,
0,h);H.close(v);H.chmod(q,n)}}}finally{eb--,f.monitorRunDependencies?.(eb),0==eb&&fb&&(h=fb,fb=null,h())}};function hb(){var a,b,c;H.qb=!0;a??=f.stdin;b??=f.stdout;c??=f.stderr;a?H.Ya("/dev","stdin",a):H.symlink("/dev/tty","/dev/stdin");b?H.Ya("/dev","stdout",null,b):H.symlink("/dev/tty","/dev/stdout");c?H.Ya("/dev","stderr",null,c):H.symlink("/dev/tty1","/dev/stderr");H.open("/dev/stdin",0);H.open("/dev/stdout",1);H.open("/dev/stderr",1)}function Ya(a,b){H.Db[a]={va:b}}
function J(a){return 16384===(a&61440)}function K(a,b){var c=J(a.mode)?(c=M(a,"x"))?c:a.ua.lookup?0:2:54;if(c)throw new H.sa(c);for(c=H.Ua[lb(a.id,b)];c;c=c.$a){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return H.lookup(a,b)}function bb(a){var b=lb(a.parent.id,a.name);if(H.Ua[b]===a)H.Ua[b]=a.$a;else for(b=H.Ua[b];b;){if(b.$a===a){b.$a=a.$a;break}b=b.$a}}
function N(a,b={}){if(!a)throw new H.sa(44);b.kb??(b.kb=!0);"/"===a.charAt(0)||(a=H.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=H.root,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if("."!==a[g])if(".."===a[g])if(e=Ja(e),H.tb(d)){a=e+"/"+a.slice(g+1).join("/");c--;continue a}else d=d.parent;else{e=Ia(e+"/"+a[g]);try{d=K(d,a[g])}catch(k){if(44===k?.Ea&&h&&b.nc)return{path:e};throw k;}!d.Oa||h&&!b.kb||(d=d.Oa.root);if(40960===(d.mode&61440)&&(!h||
b.La)){if(!d.ua.readlink)throw new H.sa(52);d=d.ua.readlink(d);"/"===d.charAt(0)||(d=Ja(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new H.sa(32);}function jb(a){for(var b;;){if(H.tb(a))return a=a.Aa.Jb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function lb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%H.Ua.length}function mb(a){var b=lb(a.parent.id,a.name);a.$a=H.Ua[b];H.Ua[b]=a}
function M(a,b){return H.Hb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function nb(a,b){if(!J(a.mode))return 54;try{return K(a,b),20}catch(c){}return M(a,"wx")}function ob(a,b,c){try{var d=K(a,b)}catch(e){return e.Ea}if(a=M(a,"wx"))return a;if(c){if(!J(d.mode))return 54;if(H.tb(d)||jb(d)===H.cwd())return 10}else if(J(d.mode))return 31;return 0}function pb(a,b){if(!a)throw new H.sa(b);return a}
function O(a){a=H.dc(a);if(!a)throw new H.sa(8);return a}function qb(a,b=-1){a=Object.assign(new H.Tb,a);if(-1==b)a:{for(b=0;b<=H.Ub;b++)if(!H.streams[b])break a;throw new H.sa(33);}a.fd=b;return H.streams[b]=a}function sb(a,b=-1){a=qb(a,b);a.va?.Mc?.(a);return a}function tb(a,b,c){var d=a?.va.Pa;a=d?a:b;d??=b.ua.Pa;pb(d,63);d(a,c)}function ub(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.fb)}return b}
function vb(a){var b={Cc:4096,Pc:4096,blocks:1E6,Bc:5E5,Ac:5E5,files:H.wb,Nc:H.wb-1,Qc:42,flags:2,Vc:255};a.ua.Mb&&Object.assign(b,a.ua.Mb(a.Aa.oc.root));return b}function wb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return H.Ta(a,b|8192,c)}function xb(a,b,c,d){tb(a,b,{mode:c&4095|b.mode&-4096,ctime:Date.now(),Eb:d})}function yb(a,b,c){if(J(b.mode))throw new H.sa(31);if(!H.isFile(b.mode))throw new H.sa(28);var d=M(b,"w");if(d)throw new H.sa(d);tb(a,b,{size:c,timestamp:Date.now()})}
function zb(a,b,c,d){a="string"==typeof a?a:jb(a);b=Ia(a+"/"+b);return H.create(b,cb(c,d))}function Ab(a){if(!(a.lc||a.mc||a.link||a.wa))if(globalThis.XMLHttpRequest)D("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.wa=ia(a.url)}catch(b){throw new H.sa(29);}}
var H={root:null,fb:[],Db:{},streams:[],wb:1,Ua:null,Bb:"/",qb:!1,Hb:!0,$b:null,nb:0,sa:class{name="ErrnoError";constructor(a){this.Ea=a}},Tb:class{Wa={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.Wa.flags}set flags(a){this.Wa.flags=a}get position(){return this.Wa.position}set position(a){this.Wa.position=a}},Sb:class{ua={};va={};Oa=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Aa=a.Aa;this.id=H.wb++;this.name=b;this.mode=c;this.rdev=d;this.atime=
this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get mc(){return J(this.mode)}get lc(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new H.Sb(a,b,c,d);mb(a);return a},tb(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},Ub:4096,dc:a=>H.streams[a],Vb:{open(a){a.va=
H.bc(a.node.rdev).va;a.va.open?.(a)},Ja(){throw new H.sa(70);}},vb:a=>a>>8,Tc:a=>a&255,Za:(a,b)=>a<<8|b,bc:a=>H.Db[a],Nb(a,b){function c(k){H.nb--;return b(k)}function d(k){if(k){if(!d.Yb)return d.Yb=!0,c(k)}else++g>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);H.nb++;1<H.nb&&p(`warning: ${H.nb} FS.syncfs operations in flight at once, probably just doing extra work`);var e=ub(H.root.Aa),g=0,h;for(h of e)h.type.Nb?h.type.Nb(h,a,d):d(null)},Aa(a,b,c){var d="/"===c;if(d&&H.root)throw new H.sa(10);
if(!d&&c){var e=N(c,{kb:!1});c=e.path;e=e.node;if(e.Oa)throw new H.sa(10);if(!J(e.mode))throw new H.sa(54);}b={type:a,oc:b,Jb:c,fb:[]};a=a.Aa(b);a.Aa=b;b.root=a;d?H.root=a:e&&(e.Oa=b,e.Aa&&e.Aa.fb.push(b));return a},Zc(a){a=N(a,{kb:!1});if(!a.node.Oa)throw new H.sa(28);a=a.node;var b=a.Oa,c=ub(b);for([,e]of Object.entries(H.Ua))for(;e;){var d=e.$a;c.includes(e.Aa)&&bb(e);var e=d}a.Oa=null;a.Aa.fb.splice(a.Aa.fb.indexOf(b),1)},lookup(a,b){return a.ua.lookup(a,b)},Ta(a,b,c){var d=N(a,{parent:!0}).node;
a=E(a);if(!a)throw new H.sa(28);if("."===a||".."===a)throw new H.sa(20);var e=nb(d,a);if(e)throw new H.sa(e);if(!d.ua.Ta)throw new H.sa(63);return d.ua.Ta(d,a,b,c)},Mb(a){return vb(N(a,{La:!0}).node)},Yc(a){return vb(a.node)},create(a,b=438){return H.Ta(a,b&4095|32768,0)},mkdir(a,b=511){return H.Ta(a,b&1023|16384,0)},Uc(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{H.mkdir(d,b)}catch(g){if(20!=g.Ea)throw g;}}},symlink(a,b){if(!Na(a))throw new H.sa(44);var c=
N(b,{parent:!0}).node;if(!c)throw new H.sa(44);b=E(b);var d=nb(c,b);if(d)throw new H.sa(d);if(!c.ua.symlink)throw new H.sa(63);return c.ua.symlink(c,b,a)},rename(a,b){var c=Ja(a),d=Ja(b),e=E(a),g=E(b);var h=N(a,{parent:!0});var k=h.node;h=N(b,{parent:!0});h=h.node;if(!k||!h)throw new H.sa(44);if(k.Aa!==h.Aa)throw new H.sa(75);var m=K(k,e);a=Oa(a,d);if("."!==a.charAt(0))throw new H.sa(28);a=Oa(b,c);if("."!==a.charAt(0))throw new H.sa(55);try{var l=K(h,g)}catch(n){}if(m!==l){b=J(m.mode);if(e=ob(k,e,
b))throw new H.sa(e);if(e=l?ob(h,g,b):nb(h,g))throw new H.sa(e);if(!k.ua.rename)throw new H.sa(63);if(m.Oa||l&&l.Oa)throw new H.sa(10);if(h!==k&&(e=M(k,"w")))throw new H.sa(e);bb(m);try{k.ua.rename(m,h,g),m.parent=h}catch(n){throw n;}finally{mb(m)}}},rmdir(a){var b=N(a,{parent:!0}).node;a=E(a);var c=K(b,a),d=ob(b,a,!0);if(d)throw new H.sa(d);if(!b.ua.rmdir)throw new H.sa(63);if(c.Oa)throw new H.sa(10);b.ua.rmdir(b,a);bb(c)},readdir(a){a=N(a,{La:!0}).node;return pb(a.ua.readdir,54)(a)},unlink(a){var b=
N(a,{parent:!0}).node;if(!b)throw new H.sa(44);a=E(a);var c=K(b,a),d=ob(b,a,!1);if(d)throw new H.sa(d);if(!b.ua.unlink)throw new H.sa(63);if(c.Oa)throw new H.sa(10);b.ua.unlink(b,a);bb(c)},readlink(a){a=N(a).node;if(!a)throw new H.sa(44);if(!a.ua.readlink)throw new H.sa(28);return a.ua.readlink(a)},stat(a,b){a=N(a,{La:!b}).node;return pb(a.ua.Na,63)(a)},fstat(a){var b=O(a);a=b.node;var c=b.va.Na;b=c?b:a;c??=a.ua.Na;pb(c,63);return c(b)},lstat(a){return H.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?
N(a,{La:!c}).node:a;xb(null,a,b,c)},lchmod(a,b){H.chmod(a,b,!0)},fchmod(a,b){a=O(a);xb(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?N(a,{La:!d}).node:a;tb(null,a,{timestamp:Date.now(),Eb:d})},lchown(a,b,c){H.chown(a,b,c,!0)},fchown(a){a=O(a);tb(a,a.node,{timestamp:Date.now(),Eb:!1})},truncate(a,b){if(0>b)throw new H.sa(28);a="string"==typeof a?N(a,{La:!0}).node:a;yb(null,a,b)},Rc(a,b){a=O(a);if(0>b||0===(a.flags&2097155))throw new H.sa(28);yb(a,a.node,b)},$c(a,b,c){a=N(a,{La:!0}).node;pb(a.ua.Pa,
63)(a,{atime:b,mtime:c})},open(a,b,c=438){if(""===a)throw new H.sa(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");var g=N(a,{La:!(b&131072),nc:!0});d=g.node;a=g.path}g=!1;if(b&64)if(d){if(b&128)throw new H.sa(20);}else{if(e)throw new H.sa(31);d=H.Ta(a,c|511,0);g=!0}if(!d)throw new H.sa(44);8192===(d.mode&61440)&&(b&=-513);
if(b&65536&&!J(d.mode))throw new H.sa(54);if(!g&&(d?40960===(d.mode&61440)?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=J(d.mode)&&("r"!==e||b&576)?31:M(d,e)):e=44,e))throw new H.sa(e);b&512&&!g&&H.truncate(d,0);b&=-131713;b=qb({node:d,path:jb(d),flags:b,seekable:!0,position:0,va:d.va,wc:[],error:!1});b.va.open&&b.va.open(b);g&&H.chmod(d,c&511);return b},close(a){if(null===a.fd)throw new H.sa(8);a.pb&&(a.pb=null);try{a.va.close&&a.va.close(a)}catch(b){throw b;}finally{H.streams[a.fd]=null}a.fd=null},
Ja(a,b,c){if(null===a.fd)throw new H.sa(8);if(!a.seekable||!a.va.Ja)throw new H.sa(70);if(0!=c&&1!=c&&2!=c)throw new H.sa(28);a.position=a.va.Ja(a,b,c);a.wc=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new H.sa(28);if(null===a.fd)throw new H.sa(8);if(1===(a.flags&2097155))throw new H.sa(8);if(J(a.node.mode))throw new H.sa(31);if(!a.va.read)throw new H.sa(28);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new H.sa(70);b=a.va.read(a,b,c,d,e);g||(a.position+=b);return b},
write(a,b,c,d,e,g){if(0>d||0>e)throw new H.sa(28);if(null===a.fd)throw new H.sa(8);if(0===(a.flags&2097155))throw new H.sa(8);if(J(a.node.mode))throw new H.sa(31);if(!a.va.write)throw new H.sa(28);a.seekable&&a.flags&1024&&H.Ja(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new H.sa(70);b=a.va.write(a,b,c,d,e,g);h||(a.position+=b);return b},bb(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new H.sa(2);if(1===(a.flags&2097155))throw new H.sa(2);if(!a.va.bb)throw new H.sa(43);
if(!b)throw new H.sa(28);return a.va.bb(a,b,c,d,e)},gb(a,b,c,d,e){return a.va.gb?a.va.gb(a,b,c,d,e):0},rb(a,b,c){if(!a.va.rb)throw new H.sa(59);return a.va.rb(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&D(`Invalid encoding type "${b.encoding}"`);var c=H.open(a,b.flags);a=H.stat(a).size;var d=new Uint8Array(a);H.read(c,d,0,a,0);"utf8"===b.encoding&&(d=Ra(d));H.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=H.open(a,
c.flags,c.mode);"string"==typeof b&&(b=new Uint8Array(Va(b)));ArrayBuffer.isView(b)?H.write(a,b,0,b.byteLength,void 0,c.Ic):D("Unsupported data type");H.close(a)},cwd:()=>H.Bb,chdir(a){a=N(a,{La:!0});if(null===a.node)throw new H.sa(44);if(!J(a.node.mode))throw new H.sa(54);var b=M(a.node,"x");if(b)throw new H.sa(b);H.Bb=a.path},Xc(){H.qb=!1;for(var a of H.streams)a&&H.close(a)},Oc(a,b){try{var c=N(a,{La:!b});a=c.path}catch(g){}var d=!1,e=null;try{c=N(a,{parent:!0}),E(a),c=N(a,{La:!b}),d=!0,e=c.node}catch(g){}return d?
e:null},Kc(a,b){a="string"==typeof a?a:jb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ia(a+"/"+c);try{H.mkdir(d)}catch(e){if(20!=e.Ea)throw e;}a=d}}return d},Ya(a,b,c,d){a=Ka("string"==typeof a?a:jb(a),b);b=cb(!!c,!!d);var e;(e=H.Ya).vb??(e.vb=64);e=H.Za(H.Ya.vb++,0);Ya(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,k,m){for(var l=0,n=0;n<m;n++){try{var q=c()}catch(r){throw new H.sa(29);}if(void 0===q&&0===l)throw new H.sa(6);if(null===q||void 0===q)break;
l++;h[k+n]=q}l&&(g.node.atime=Date.now());return l},write(g,h,k,m){for(var l=0;l<m;l++)try{d(h[k+l])}catch(n){throw new H.sa(29);}m&&(g.node.mtime=g.node.ctime=Date.now());return l}});return wb(a,b,e)},Jc(a,b,c,d,e){class g{zb=!1;Wa=[];eb=void 0;Pb=0;Ob=0;get(l){if(!(l>this.length-1||0>l)){var n=l%this.chunkSize;return this.eb(l/this.chunkSize|0)[n]}}xc(l){this.eb=l}Rb(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);200<=l.status&&300>l.status||304===l.status||D("Couldn't load "+c+". Status: "+
l.status);var n=Number(l.getResponseHeader("Content-length")),q,r=(q=l.getResponseHeader("Accept-Ranges"))&&"bytes"===q;l=(q=l.getResponseHeader("Content-Encoding"))&&"gzip"===q;var t=1048576;r||(t=n);var v=this;v.xc(B=>{var F=B*t,L=(B+1)*t-1;L=Math.min(L,n-1);if("undefined"==typeof v.Wa[B]){var G=v.Wa;F>L&&D("invalid range ("+F+", "+L+") or no bytes requested!");L>n-1&&D("only "+n+" bytes available! programmer error!");var C=new XMLHttpRequest;C.open("GET",c,!1);n!==t&&C.setRequestHeader("Range",
"bytes="+F+"-"+L);C.responseType="arraybuffer";C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");C.send(null);200<=C.status&&300>C.status||304===C.status||D("Couldn't load "+c+". Status: "+C.status);F=void 0!==C.response?new Uint8Array(C.response||[]):Va(C.responseText||"");G[B]=F}"undefined"==typeof v.Wa[B]&&D("doXHR failed!");return v.Wa[B]});if(l||!n)t=n=1,t=n=this.eb(0).length,ka("LazyFiles on gzip forces download of the whole file when length is accessed");this.Pb=
n;this.Ob=t;this.zb=!0}get length(){this.zb||this.Rb();return this.Pb}get chunkSize(){this.zb||this.Rb();return this.Ob}}if(globalThis.XMLHttpRequest){ba||D("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var h=new g;var k=void 0}else k=c,h=void 0;var m=zb(a,b,d,e);h?m.wa=h:k&&(m.wa=null,m.url=k);Object.defineProperties(m,{Da:{get:function(){return this.wa.length}}});a={};for(const [l,n]of Object.entries(m.va))a[l]=(...q)=>{Ab(m);
return n(...q)};a.read=(l,n,q,r,t)=>{Ab(m);l=l.node.wa;if(t>=l.length)n=0;else{r=Math.min(l.length-t,r);if(l.slice)for(var v=0;v<r;v++)n[q+v]=l[t+v];else for(v=0;v<r;v++)n[q+v]=l.get(t+v);n=r}return n};a.bb=()=>{Ab(m);D();throw new H.sa(48);};m.va=a;return m}},P=(a,b,c)=>(a>>>=0)?Ra(w,a,b,c):"";function Bb(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?H.cwd():O(a).path;if(0==b.length){if(!c)throw new H.sa(44);return a}return a+"/"+b}
function Cb(a,b){z[a>>>2>>>0]=b.dev;z[a+4>>>2>>>0]=b.mode;z[a+8>>>2>>>0]=b.nlink;z[a+12>>>2>>>0]=b.uid;z[a+16>>>2>>>0]=b.gid;z[a+20>>>2>>>0]=b.rdev;A[a+24>>>3>>>0]=BigInt(b.size);y[a+32>>>2>>>0]=4096;y[a+36>>>2>>>0]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),e=b.ctime.getTime();A[a+40>>>3>>>0]=BigInt(Math.floor(c/1E3));z[a+48>>>2>>>0]=c%1E3*1E6;A[a+56>>>3>>>0]=BigInt(Math.floor(d/1E3));z[a+64>>>2>>>0]=d%1E3*1E6;A[a+72>>>3>>>0]=BigInt(Math.floor(e/1E3));z[a+80>>>2>>>0]=e%1E3*1E6;A[a+88>>>
3>>>0]=BigInt(b.ino);return 0}var Db=void 0,Q=()=>{var a=y[+Db>>>2>>>0];Db+=4;return a},Eb={},Fb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Gb(a){return this.ya(z[a>>>2>>>0])}
var Hb={},Ib={},Jb={},Kb=class extends Error{constructor(a){super(a);this.name="InternalError"}},S=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new Kb("Mismatched type converter count");for(var m=0;m<a.length;++m)R(a[m],k[m])}a.forEach(k=>Jb[k]=b);var e=Array(b.length),g=[],h=0;for(let [k,m]of b.entries())Ib.hasOwnProperty(m)?e[k]=Ib[m]:(g.push(m),Hb.hasOwnProperty(m)||(Hb[m]=[]),Hb[m].push(()=>{e[k]=Ib[m];++h;h===g.length&&d(e)}));0===g.length&&d(e)},T=a=>{a>>>=0;for(var b="";;){var c=
w[a++>>>0];if(!c)return b;b+=String.fromCharCode(c)}},U=class extends Error{constructor(a){super(a);this.name="BindingError"}},Lb=a=>{throw new U(a);};function Mb(a,b,c={}){var d=b.name;if(!a)throw new U(`type "${d}" must have a positive integer typeid pointer`);if(Ib.hasOwnProperty(a)){if(c.hc)return;throw new U(`Cannot register type '${d}' twice`);}Ib[a]=b;delete Jb[a];Hb.hasOwnProperty(a)&&(b=Hb[a],delete Hb[a],b.forEach(e=>e()))}function R(a,b,c={}){return Mb(a,b,c)}
var Nb=(a,b,c)=>{switch(b){case 1:return c?d=>u[d>>>0]:d=>w[d>>>0];case 2:return c?d=>x[d>>>1>>>0]:d=>pa[d>>>1>>>0];case 4:return c?d=>y[d>>>2>>>0]:d=>z[d>>>2>>>0];case 8:return c?d=>A[d>>>3>>>0]:d=>sa[d>>>3>>>0];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ob=a=>{throw new U(a.ta.Ba.xa.name+" instance already deleted");},Pb=!1,Qb=()=>{},Rb=a=>{if(!globalThis.FinalizationRegistry)return Rb=b=>b,a;Pb=new FinalizationRegistry(b=>{b=b.ta;--b.count.value;0===b.count.value&&(b.Ha?
b.Ma.Ra(b.Ha):b.Ba.xa.Ra(b.za))});Rb=b=>{var c=b.ta;c.Ha&&Pb.register(b,{ta:c},b);return b};Qb=b=>{Pb.unregister(b)};return Rb(a)},Sb=[];function Tb(){}
var Ub=(a,b)=>Object.defineProperty(b,"name",{value:a}),Vb={},Wb=(a,b,c)=>{if(void 0===a[b].Ca){var d=a[b];a[b]=function(...e){if(!a[b].Ca.hasOwnProperty(e.length))throw new U(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].Ca})!`);return a[b].Ca[e.length].apply(this,e)};a[b].Ca=[];a[b].Ca[d.Sa]=d}},Xb=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].Ca&&void 0!==f[a].Ca[c])throw new U(`Cannot register public name '${a}' twice`);Wb(f,
a,a);if(f[a].Ca.hasOwnProperty(c))throw new U(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);f[a].Ca[c]=b}else f[a]=b,f[a].Sa=c},Yb=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Zb(a,b,c,d,e,g,h,k){this.name=a;this.constructor=b;this.ab=c;this.Ra=d;this.Ia=e;this.ac=g;this.ib=h;this.Xb=k;this.qc=[]}
var $b=(a,b,c)=>{for(;b!==c;){if(!b.ib)throw new U(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ib(a);b=b.Ia}return a},ac=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function bc(a,b){if(null===b){if(this.sb)throw new U(`null is not a valid ${this.name}`);return 0}if(!b.ta)throw new U(`Cannot pass "${ac(b)}" as a ${this.name}`);if(!b.ta.za)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);return $b(b.ta.za,b.ta.Ba.xa,this.xa)}
function cc(a,b){if(null===b){if(this.sb)throw new U(`null is not a valid ${this.name}`);if(this.mb){var c=this.yb();null!==a&&a.push(this.Ra,c);return c}return 0}if(!b||!b.ta)throw new U(`Cannot pass "${ac(b)}" as a ${this.name}`);if(!b.ta.za)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.lb&&b.ta.Ba.lb)throw new U(`Cannot convert argument of type ${b.ta.Ma?b.ta.Ma.name:b.ta.Ba.name} to parameter type ${this.name}`);c=$b(b.ta.za,b.ta.Ba.xa,this.xa);if(this.mb){if(void 0===
b.ta.Ha)throw new U("Passing raw pointer to smart pointer is illegal");switch(this.vc){case 0:if(b.ta.Ma===this)c=b.ta.Ha;else throw new U(`Cannot convert argument of type ${b.ta.Ma?b.ta.Ma.name:b.ta.Ba.name} to parameter type ${this.name}`);break;case 1:c=b.ta.Ha;break;case 2:if(b.ta.Ma===this)c=b.ta.Ha;else{var d=b.clone();c=this.rc(c,V(()=>d["delete"]()));null!==a&&a.push(this.Ra,c)}break;default:throw new U("Unsupported sharing policy");}}return c}
function dc(a,b){if(null===b){if(this.sb)throw new U(`null is not a valid ${this.name}`);return 0}if(!b.ta)throw new U(`Cannot pass "${ac(b)}" as a ${this.name}`);if(!b.ta.za)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.ta.Ba.lb)throw new U(`Cannot convert argument of type ${b.ta.Ba.name} to parameter type ${this.name}`);return $b(b.ta.za,b.ta.Ba.xa,this.xa)}
var ec=(a,b,c)=>{if(b===c)return a;if(void 0===c.Ia)return null;a=ec(a,b,c.Ia);return null===a?null:c.Xb(a)},fc={},gc=(a,b)=>{if(void 0===b)throw new U("ptr should not be undefined");for(;a.Ia;)b=a.ib(b),a=a.Ia;return fc[b]},hc=(a,b)=>{if(!b.Ba||!b.za)throw new Kb("makeClassHandle requires ptr and ptrType");if(!!b.Ma!==!!b.Ha)throw new Kb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Rb(Object.create(a,{ta:{value:b,writable:!0}}))};
function ic(a,b,c,d,e,g,h,k,m,l,n){this.name=a;this.xa=b;this.sb=c;this.lb=d;this.mb=e;this.pc=g;this.vc=h;this.Kb=k;this.yb=m;this.rc=l;this.Ra=n;e||void 0!==b.Ia?this.Fa=cc:(this.Fa=d?bc:dc,this.Ga=null)}
var jc=(a,b,c)=>{if(!f.hasOwnProperty(a))throw new Kb("Replacing nonexistent public symbol");void 0!==f[a].Ca&&void 0!==c?f[a].Ca[c]=b:(f[a]=b,f[a].Sa=c)},kc=[],mc=a=>{var b=kc[a];b||(kc[a]=b=lc.get(a));return b},nc=(a,b,c=[])=>{b=mc(b)(...c);return"p"==a[0]?b>>>0:b},oc=(a,b)=>(...c)=>nc(a,b,c),W=(a,b)=>{a=T(a);var c=a.includes("p")?oc(a,b):mc(b);if("function"!=typeof c)throw new U(`unknown function pointer with signature ${a}: ${b}`);return c};class pc extends Error{}
var sc=a=>{a=qc(a);var b=T(a);X(a);return b},tc=(a,b)=>{function c(g){e[g]||Ib[g]||(Jb[g]?Jb[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new pc(`${a}: `+d.map(sc).join([", "]));};function uc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].Ga)return!0;return!1}
function vc(a,b,c,d,e,g){var h=b.length;if(2>h)throw new U("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,m=uc(b);c=!b[0].Ib;var l=b[0],n=b[1];d=[a,Lb,d,e,Fb,l.ya.bind(l),n?.Fa.bind(n)];for(e=2;e<h;++e)l=b[e],d.push(l.Fa.bind(l));if(!m)for(e=k?1:2;e<b.length;++e)null!==b[e].Ga&&d.push(b[e].Ga);m=uc(b);e=b.length-2;n=[];l=["fn"];k&&l.push("thisWired");for(h=0;h<e;++h)n.push(`arg${h}`),l.push(`arg${h}Wired`);n=n.join(",");l=l.join(",");
n=`return function (${n}) {\n`;m&&(n+="var destructors = [];\n");var q=m?"destructors":"null",r="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");k&&(n+=`var thisWired = toClassParamWire(${q}, this);\n`);for(h=0;h<e;++h){var t=`toArg${h}Wire`;n+=`var arg${h}Wired = ${t}(${q}, arg${h});\n`;r.push(t)}n+=(c||g?"var rv = ":"")+`invoker(${l});\n`;if(m)n+="runDestructors(destructors);\n";else for(h=k?1:2;h<b.length;++h)g=1===h?"thisWired":"arg"+(h-2)+"Wired",
null!==b[h].Ga&&(n+=`${g}_dtor(${g});\n`,r.push(`${g}_dtor`));c&&(n+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(r,n+"}\n"))(...d);return Ub(a,b)}var wc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(z[b+4*d>>>2>>>0]);return c},xc=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},yc=[],Y=[0,1,,1,null,1,!0,1,!1,1];function zc(a){a>>>=0;9<a&&0===--Y[a+1]&&(Y[a]=void 0,yc.push(a))}
var Z=a=>{if(!a)throw new U(`Cannot use deleted val. handle = ${a}`);return Y[a]},V=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=yc.pop()||Y.length;Y[b]=a;Y[b+1]=1;return b}},Ac={name:"emscripten::val",ya:a=>{var b=Z(a);zc(a);return b},Fa:(a,b)=>V(b),Ka:Gb,Ga:null},Bc=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.ya(u[d>>>0])}:function(d){return this.ya(w[d>>>0])};case 2:return c?function(d){return this.ya(x[d>>>1>>>0])}:function(d){return this.ya(pa[d>>>
1>>>0])};case 4:return c?function(d){return this.ya(y[d>>>2>>>0])}:function(d){return this.ya(z[d>>>2>>>0])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Cc=(a,b)=>{var c=Ib[a];if(void 0===c)throw a=`${b} has unknown type ${sc(a)}`,new U(a);return c},Dc=(a,b)=>{switch(b){case 4:return function(c){return this.ya(qa[c>>>2>>>0])};case 8:return function(c){return this.ya(ra[c>>>3>>>0])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ec=globalThis.TextDecoder?
new TextDecoder("utf-16le"):void 0,Fc=(a,b,c)=>{a>>>=1;b=Qa(pa,a,b/2,c);if(16<b-a&&Ec)return Ec.decode(pa.subarray(a>>>0,b>>>0));for(c="";a<b;++a)c+=String.fromCharCode(pa[a>>>0]);return c},Gc=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)x[b>>>1>>>0]=a.charCodeAt(e),b+=2;x[b>>>1>>>0]=0;return b-d},Hc=a=>2*a.length,Ic=(a,b,c)=>{var d="";a>>>=2;for(var e=0;!(e>=b/4);e++){var g=z[a+e>>>0];if(!g&&!c)break;d+=String.fromCodePoint(g)}return d},Jc=
(a,b,c)=>{b>>>=0;c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.codePointAt(e);65535<g&&e++;y[b>>>2>>>0]=g;b+=4;if(b+4>c)break}y[b>>>2>>>0]=0;return b-d},Kc=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Lc=a=>{a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0},Nc=a=>{var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;
if("::"===a)return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(RegExp("[.]","g"),":"),a=a.split(":"),a[a.length-4]=Number(a[a.length-4])+256*Number(a[a.length-3]),a[a.length-3]=Number(a[a.length-2])+256*Number(a[a.length-1]),a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"==typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=Mc(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<
16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]},Oc=1,Pc={},Qc=[],Rc=a=>{var b=Qc.length;Qc.push(a);return b},Sc=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Cc(z[b+4*d>>>2>>>0],`parameter ${d}`);return c},Tc=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(z[b>>>2>>>0]=V(d));return a},Uc={},Vc=a=>{var b=Uc[a];return void 0===b?T(a):b},Wc=[0,31,60,91,121,152,182,213,244,274,305,335],Xc=[0,31,59,90,120,151,181,212,243,273,304,334],$c=a=>{a=a.getArg(Yc,0);return Zc(a)};
H.Lc=(a,b,c,d,e,g,h,k,m,l)=>{kb(a,b,c,d,e,k,m,l).then(g).catch(h)};H.Wc=kb;H.Ua=Array(4096);H.Aa(I,{},"/");H.mkdir("/tmp");H.mkdir("/home");H.mkdir("/home/web_user");
(function(){H.mkdir("/dev");Ya(H.Za(1,3),{read:()=>0,write:(d,e,g,h)=>h,Ja:()=>0});wb("/dev/null",H.Za(1,3));Xa(H.Za(5,0),$a);Xa(H.Za(6,0),ab);wb("/dev/tty",H.Za(5,0));wb("/dev/tty1",H.Za(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ma(a),b=a.byteLength);return a[--b]};H.Ya("/dev","random",c);H.Ya("/dev","urandom",c);H.mkdir("/dev/shm");H.mkdir("/dev/shm/tmp")})();
(function(){H.mkdir("/proc");var a=H.mkdir("/proc/self");H.mkdir("/proc/self/fd");H.Aa({Aa(){var b=H.createNode(a,"fd",16895,73);b.va={Ja:I.va.Ja};b.ua={lookup(c,d){c=+d;var e=O(c);c={parent:null,Aa:{Jb:"fake"},ua:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(H.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();H.$b={MEMFS:I};
(()=>{let a=Tb.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof Tb&&c instanceof Tb))return!1;var d=this.ta.Ba.xa,e=this.ta.za;c.ta=c.ta;var g=c.ta.Ba.xa;for(c=c.ta.za;d.Ia;)e=d.ib(e),d=d.Ia;for(;g.Ia;)c=g.ib(c),g=g.Ia;return d===g&&e===c},clone:function(){this.ta.za||Ob(this);if(this.ta.hb)return this.ta.count.value+=1,this;var c=Rb,d=Object,e=d.create,g=Object.getPrototypeOf(this),h=this.ta;c=c(e.call(d,g,{ta:{value:{count:h.count,cb:h.cb,hb:h.hb,za:h.za,Ba:h.Ba,Ha:h.Ha,Ma:h.Ma}}}));
c.ta.count.value+=1;c.ta.cb=!1;return c},["delete"](){this.ta.za||Ob(this);if(this.ta.cb&&!this.ta.hb)throw new U("Object already scheduled for deletion");Qb(this);var c=this.ta;--c.count.value;0===c.count.value&&(c.Ha?c.Ma.Ra(c.Ha):c.Ba.xa.Ra(c.za));this.ta.hb||(this.ta.Ha=void 0,this.ta.za=void 0)},isDeleted:function(){return!this.ta.za},deleteLater:function(){this.ta.za||Ob(this);if(this.ta.cb&&!this.ta.hb)throw new U("Object already scheduled for deletion");Sb.push(this);this.ta.cb=!0;return this}});
const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(ic.prototype,{cc(a){this.Kb&&(a=this.Kb(a));return a},Cb(a){this.Ra?.(a)},Ka:Gb,ya:function(a){function b(){return this.mb?hc(this.xa.ab,{Ba:this.pc,za:c,Ma:this,Ha:a}):hc(this.xa.ab,{Ba:this,za:a})}var c=this.cc(a);if(!c)return this.Cb(a),null;var d=gc(this.xa,c);if(void 0!==d){if(0===d.ta.count.value)return d.ta.za=c,d.ta.Ha=a,d.clone();d=d.clone();this.Cb(a);return d}d=this.xa.ac(c);d=Vb[d];if(!d)return b.call(this);d=this.lb?d.Wb:d.pointerType;var e=ec(c,this.xa,d.xa);return null===
e?b.call(this):this.mb?hc(d.xa.ab,{Ba:d,za:e,Ma:this,Ha:a}):hc(d.xa.ab,{Ba:d,za:e})}});f.noExitRuntime&&(Ga=f.noExitRuntime);f.preloadPlugins&&(gb=f.preloadPlugins);f.print&&(ka=f.print);f.printErr&&(p=f.printErr);f.wasmBinary&&(la=f.wasmBinary);if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();f.FS=H;f.incrementExceptionRefcount=a=>{a=$c(a);ad(a)};f.decrementExceptionRefcount=a=>{a=$c(a);bd(a)};
f.getExceptionMessage=a=>{var b=$c(a);a=cd();var c=dd(4),d=dd(4);ed(b,c,d);b=z[c>>>2>>>0];d=z[d>>>2>>>0];c=P(b);X(b);if(d){var e=P(d);X(d)}fd(a);return[c,e]};
var qc,gd,X,Mc,wa,fd,dd,cd,bd,ad,Zc,ed,Yc,va,lc,hd={ba:function(){return f.yc.length},aa:function(a,b){a>>>=0;try{return a=P(a),H.chmod(a,b),0}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return-c.Ea}},$:function(a,b,c){b>>>=0;try{b=P(b);b=Bb(a,b);if(c&-8)return-28;var d=N(b,{La:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&M(d,a)?-2:0}catch(e){if("undefined"==typeof H||"ErrnoError"!==e.name)throw e;return-e.Ea}},y:function(a,b,c){Db=c>>>0;
try{var d=O(a);switch(b){case 0:var e=Q();if(0>e)break;for(;H.streams[e];)e++;return sb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Q(),d.flags|=e,0;case 12:return e=Q(),x[e+0>>>1>>>0]=2,0;case 13:case 14:return 0}return-28}catch(g){if("undefined"==typeof H||"ErrnoError"!==g.name)throw g;return-g.Ea}},_:function(a,b){try{return Cb(b>>>0,H.fstat(a))}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return-c.Ea}},Z:function(a,b,c){Db=c>>>0;try{var d=O(a);switch(b){case 21509:return d.tty?
0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Va.ic){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Q();y[e>>>2>>>0]=25856;y[e+4>>>2>>>0]=5;y[e+8>>>2>>>0]=191;y[e+12>>>2>>>0]=35387;for(var g=0;32>g;g++)u[e+g+17>>>0]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Va.jc)for(e=Q(),a=[],g=0;32>g;g++)a.push(u[e+g+17>>>0]);return 0;case 21519:if(!d.tty)return-59;e=Q();return y[e>>>2>>>
0]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:return e=Q(),H.rb(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Va.kc&&(g=[24,80],e=Q(),x[e>>>1>>>0]=g[0],x[e+2>>>1>>>0]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof H||"ErrnoError"!==h.name)throw h;return-h.Ea}},Y:function(a,b){a>>>=0;b>>>=0;try{return a=P(a),Cb(b,H.lstat(a))}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return-c.Ea}},X:function(a,
b,c,d){b>>>=0;c>>>=0;try{b=P(b);var e=d&256;b=Bb(a,b,d&4096);return Cb(c,e?H.lstat(b):H.stat(b))}catch(g){if("undefined"==typeof H||"ErrnoError"!==g.name)throw g;return-g.Ea}},E:function(a,b,c,d){b>>>=0;Db=d>>>=0;try{b=P(b);b=Bb(a,b);var e=d?Q():0;return H.open(b,c,e).fd}catch(g){if("undefined"==typeof H||"ErrnoError"!==g.name)throw g;return-g.Ea}},W:function(a,b){a>>>=0;b>>>=0;try{return a=P(a),Cb(b,H.stat(a))}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return-c.Ea}},S:()=>D(""),
h:function(a){a>>>=0;var b=Eb[a];delete Eb[a];var c=b.yb,d=b.Ra,e=b.Fb,g=e.map(h=>h.fc).concat(e.map(h=>h.tc));S([a],g,h=>{var k={},m,l;for([m,l]of e.entries()){const n=h[m],q=l.eb,r=l.ec,t=h[m+e.length],v=l.sc,B=l.uc;k[l.Zb]={read:F=>n.ya(q(r,F)),write:(F,L)=>{var G=[];v(B,F,t.Fa(G,L));Fb(G)},optional:n.optional}}return[{name:b.name,ya:n=>{var q={},r;for(r in k)q[r]=k[r].read(n);d(n);return q},Fa:(n,q)=>{for(var r in k)if(!(r in q||k[r].optional))throw new TypeError(`Missing field: "${r}"`);var t=
c();for(r in k)k[r].write(t,q[r]);null!==n&&n.push(d,t);return t},Ka:Gb,Ga:d}]})},C:function(a,b,c,d,e){a>>>=0;c>>>=0;b=T(b>>>0);d=0n===d;let g=h=>h;if(d){const h=8*c;g=k=>BigInt.asUintN(h,k);e=g(e)}R(a,{name:b,ya:g,Fa:(h,k)=>{"number"==typeof k&&(k=BigInt(k));return k},Ka:Nb(b,c,!d),Ga:null})},R:function(a,b,c,d){b=T(b>>>0);R(a>>>0,{name:b,ya:function(e){return!!e},Fa:function(e,g){return g?c:d},Ka:function(e){return this.ya(w[e>>>0])},Ga:null})},j:function(a,b,c,d,e,g,h,k,m,l,n,q,r){a>>>=0;b>>>=
0;c>>>=0;d>>>=0;g>>>=0;h>>>=0;k>>>=0;m>>>=0;l>>>=0;n>>>=0;q>>>=0;r>>>=0;n=T(n);g=W(e>>>0,g);k&&=W(h,k);l&&=W(m,l);r=W(q,r);var t=Yb(n);Xb(t,function(){tc(`Cannot construct ${n} due to unbound types`,[d])});S([a,b,c],d?[d]:[],v=>{v=v[0];if(d){var B=v.xa;var F=B.ab}else F=Tb.prototype;v=Ub(n,function(...rb){if(Object.getPrototypeOf(this)!==L)throw new U(`Use 'new' to construct ${n}`);if(void 0===G.Xa)throw new U(`${n} has no accessible constructor`);var rc=G.Xa[rb.length];if(void 0===rc)throw new U(`Tried to invoke ctor of ${n} with invalid number of parameters (${rb.length}) - expected (${Object.keys(G.Xa).toString()}) parameters instead!`);
return rc.apply(this,rb)});var L=Object.create(F,{constructor:{value:v}});v.prototype=L;var G=new Zb(n,v,L,r,B,g,k,l);if(G.Ia){var C;(C=G.Ia).jb??(C.jb=[]);G.Ia.jb.push(G)}B=new ic(n,G,!0,!1,!1);C=new ic(n+"*",G,!1,!1,!1);F=new ic(n+" const*",G,!1,!0,!1);Vb[a]={pointerType:C,Wb:F};jc(t,v);return[B,C,F]})},e:function(a,b,c,d,e,g,h,k){a>>>=0;b>>>=0;e>>>=0;g>>>=0;h>>>=0;var m=wc(c,d>>>0);b=T(b);b=xc(b);g=W(e,g);S([],[a],l=>{function n(){tc(`Cannot call ${q} due to unbound types`,m)}l=l[0];var q=`${l.name}.${b}`;
b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var r=l.xa.constructor;void 0===r[b]?(n.Sa=c-1,r[b]=n):(Wb(r,b,q),r[b].Ca[c-1]=n);S([],m,t=>{t=[t[0],null].concat(t.slice(1));t=vc(q,t,null,g,h,k);void 0===r[b].Ca?(t.Sa=c-1,r[b]=t):r[b].Ca[c-1]=t;if(l.xa.jb)for(const v of l.xa.jb)v.constructor.hasOwnProperty(b)||(v.constructor[b]=t);return[]});return[]})},d:function(a,b,c,d,e,g){a>>>=0;d>>>=0;e>>>=0;g>>>=0;var h=wc(b,c>>>0);e=W(d,e);S([],[a],k=>{k=k[0];var m=`constructor ${k.name}`;void 0===k.xa.Xa&&
(k.xa.Xa=[]);if(void 0!==k.xa.Xa[b-1])throw new U(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);k.xa.Xa[b-1]=()=>{tc(`Cannot construct ${k.name} due to unbound types`,h)};S([],h,l=>{l.splice(1,0,null);k.xa.Xa[b-1]=vc(m,l,null,e,g);return[]});return[]})},a:function(a,b,c,d,e,g,h,k,m){a>>>=0;b>>>=0;e>>>=0;g>>>=0;h>>>=0;var l=wc(c,d>>>0);b=T(b);
b=xc(b);g=W(e,g);S([],[a],n=>{function q(){tc(`Cannot call ${r} due to unbound types`,l)}n=n[0];var r=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&n.xa.qc.push(b);var t=n.xa.ab,v=t[b];void 0===v||void 0===v.Ca&&v.className!==n.name&&v.Sa===c-2?(q.Sa=c-2,q.className=n.name,t[b]=q):(Wb(t,b,r),t[b].Ca[c-2]=q);S([],l,B=>{B=vc(r,B,n,g,h,m);void 0===t[b].Ca?(B.Sa=c-2,t[b]=B):t[b].Ca[c-2]=B;return[]});return[]})},Q:function(a){return R(a>>>0,Ac)},r:function(a,b,c,d,e){a>>>=0;c>>>=0;
b=T(b>>>0);e=0===e?"object":1===e?"number":"string";switch(e){case "object":function h(){}h.values={};R(a,{name:b,constructor:h,valueType:e,ya:function(k){return this.constructor.values[k]},Fa:(k,m)=>m.value,Ka:Bc(b,c,d),Ga:null});Xb(b,h);break;case "number":var g={};R(a,{name:b,ub:g,valueType:e,ya:k=>k,Fa:(k,m)=>m,Ka:Bc(b,c,d),Ga:null});Xb(b,g);delete f[b].Sa;break;case "string":g={},R(a,{name:b,Qb:{},Lb:{},ub:g,valueType:e,ya:function(k){return this.Lb[k]},Fa:function(k,m){return this.Qb[m]},Ka:Bc(b,
c,d),Ga:null}),Xb(b,g),delete f[b].Sa}},n:function(a,b,c){b>>>=0;var d=Cc(a>>>0,"enum");b=T(b);switch(d.valueType){case "object":a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Ub(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d;break;case "number":d.ub[b]=c;break;case "string":d.Qb[b]=c,d.Lb[c]=b,d.ub[b]=b}},B:function(a,b,c){b=T(b>>>0);R(a>>>0,{name:b,ya:d=>d,Fa:(d,e)=>e,Ka:Dc(b,c>>>0),Ga:null})},A:function(a,b,c,d,e,g,h){a>>>=0;d>>>=0;e>>>=0;g>>>=
0;var k=wc(b,c>>>0);a=T(a);a=xc(a);e=W(d,e);Xb(a,function(){tc(`Cannot call ${a} due to unbound types`,k)},b-1);S([],k,m=>{m=[m[0],null].concat(m.slice(1));jc(a,vc(a,m,null,e,g,h),b-1);return[]})},v:function(a,b,c,d,e){a>>>=0;c>>>=0;b=T(b>>>0);let g=k=>k;if(0===d){var h=32-8*c;g=k=>k<<h>>>h;e=g(e)}R(a,{name:b,ya:g,Fa:(k,m)=>m,Ka:Nb(b,c,0!==d),Ga:null})},t:function(a,b,c){function d(g){return new e(u.buffer,z[g+4>>>2>>>0],z[g>>>2>>>0])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,
Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=T(c>>>0);R(a>>>0,{name:c,ya:d,Ka:d},{hc:!0})},q:function(a,b,c,d,e,g,h,k,m,l,n,q){a>>>=0;b>>>=0;c>>>=0;g>>>=0;h>>>=0;k>>>=0;m>>>=0;l>>>=0;n>>>=0;q>>>=0;c=T(c);g=W(e>>>0,g);k=W(h,k);l=W(m,l);q=W(n,q);S([a],[b],r=>{r=r[0];return[new ic(c,r.xa,!1,!1,!0,r,d,g,k,l,q)]})},P:function(a,b){b=T(b>>>0);R(a>>>0,{name:b,ya(c){var d=P(c+4,z[c>>>2>>>0],!0);X(c);return d},Fa(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==
typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new U("Cannot pass non-string to std::string");var g=e?Ta(d):d.length;var h=gd(4+g+1),k=h+4;z[h>>>2>>>0]=g;e?Ua(d,w,k,g+1):w.set(d,k>>>0);null!==c&&c.push(X,h);return h},Ka:Gb,Ga(c){X(c)}})},w:function(a,b,c){b>>>=0;c>>>=0;c=T(c);if(2===b){var d=Fc;var e=Gc;var g=Hc}else d=Ic,e=Jc,g=Kc;R(a>>>0,{name:c,ya:h=>{var k=d(h+4,z[h>>>2>>>0]*b,!0);X(h);return k},Fa:(h,k)=>{if("string"!=typeof k)throw new U(`Cannot pass non-string to C++ string type ${c}`);
var m=g(k),l=gd(4+m+b);z[l>>>2>>>0]=m/b;e(k,l+4,m+b);null!==h&&h.push(X,l);return l},Ka:Gb,Ga(h){X(h)}})},o:function(a,b,c,d,e,g){e>>>=0;g>>>=0;Eb[a>>>0]={name:T(b>>>0),yb:W(c>>>0,d>>>0),Ra:W(e,g),Fb:[]}},g:function(a,b,c,d,e,g,h,k,m,l){g>>>=0;h>>>=0;k>>>=0;m>>>=0;l>>>=0;Eb[a>>>0].Fb.push({Zb:T(b>>>0),fc:c>>>0,eb:W(d>>>0,e>>>0),ec:g,tc:h,sc:W(k,m),uc:l})},O:function(a,b){b=T(b>>>0);R(a>>>0,{Ib:!0,name:b,ya:()=>{},Fa:()=>{}})},N:function(a){a=P(a>>>0);var b=Lc(a);null===b&&(b=Nc(a),null===b&&(Pc[a]?
b=Pc[a]:(b=Oc++,b="172.29."+(b&255)+"."+(b&65280),Pc[a]=b),a=b));return Lc(a)},m:function(a,b,c){var [d,...e]=Sc(a,b>>>0);b=d.Fa.bind(d);var g=e.map(m=>m.Ka.bind(m));a--;var h={toValue:Z};a=g.map((m,l)=>{var n=`argFromPtr${l}`;h[n]=m;return`${n}(args${l?"+"+8*l:""})`});switch(c){case 0:var k="toValue(handle)";break;case 2:k="new (toValue(handle))";break;case 3:k="";break;case 1:h.getStringOrSymbol=Vc,k="toValue(handle)[getStringOrSymbol(methodName)]"}k+=`(${a})`;d.Ib||(h.toReturnWire=b,h.emval_returnValue=
Tc,k=`return emval_returnValue(toReturnWire, destructorsRef, ${k})`);k=`return function (handle, methodName, destructorsRef, args) {\n${k}\n}`;c=(new Function(Object.keys(h),k))(...Object.values(h));k=`methodCaller<(${e.map(m=>m.name)}) => ${d.name}>`;return Rc(Ub(k,c))},b:zc,u:function(a){a>>>=0;if(!a)return V(globalThis);a=Vc(a);return V(globalThis[a])},c:function(a){a=Vc(a>>>0);return V(f[a])},s:function(a,b){b>>>=0;a=Z(a>>>0);b=Z(b);return V(a[b])},p:function(a){a>>>=0;9<a&&(Y[a+1]+=1)},i:function(a,
b){b>>>=0;a=Z(a>>>0);b=Z(b);return a instanceof b},l:function(a,b,c,d,e){return Qc[a>>>0](b>>>0,c>>>0,d>>>0,e>>>0)},z:function(a){return V(Vc(a>>>0))},k:function(a){a>>>=0;var b=Z(a);Fb(b);zc(a)},M:function(a,b,c){b>>>=0;c>>>=0;a=Z(a>>>0);b=Z(b);c=Z(c);a[b]=c},f:function(a){a=Z(a>>>0);return V(typeof a)},L:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);y[b>>>2>>>0]=a.getSeconds();y[b+4>>>2>>>0]=a.getMinutes();y[b+8>>>2>>>0]=a.getHours();y[b+12>>>2>>>
0]=a.getDate();y[b+16>>>2>>>0]=a.getMonth();y[b+20>>>2>>>0]=a.getFullYear()-1900;y[b+24>>>2>>>0]=a.getDay();var c=a.getFullYear();y[b+28>>>2>>>0]=(0!==c%4||0===c%100&&0!==c%400?Xc:Wc)[a.getMonth()]+a.getDate()-1|0;y[b+36>>>2>>>0]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();y[b+32>>>2>>>0]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},K:function(a,b,c,d){c>>>=0;d>>>=0;var e=(new Date).getFullYear(),g=
(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();z[a>>>0>>>2>>>0]=60*Math.max(g,e);y[b>>>0>>>2>>>0]=Number(g!=e);b=h=>{var k=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(Ua(a,w,c,17),Ua(b,w,d,17)):(Ua(a,w,d,17),Ua(b,w,c,17))},V:function(a,b,c){if(!(0<=a&&3>=a))return 28;A[c>>>0>>>3>>>0]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},J:()=>Date.now(),I:function(a,
b,c){b>>>=0;var d=Error().stack.toString(),e=d.split("\n");d="";var g=RegExp("\\s*(.*?)@(.*?):([0-9]+):([0-9]+)"),h=RegExp("\\s*at (.*?) \\((.*):(.*):(.*)\\)"),k;for(k of e){var m=h.exec(k);if(5==m?.length){e=m[1];var l=m[2];var n=m[3];m=m[4]}else if(m=g.exec(k),4<=m?.length)e=m[1],l=m[2],n=m[3],m=m[4]|0;else{d+=k+"\n";continue}"_emscripten_log"==e||"_emscripten_get_callstack"==e?d="":a&24&&(a&64&&(l=l.substring(l.replace(/\\/g,"/").lastIndexOf("/")+1)),d+=`    at ${e} (${l}:${n}:${m})\n`)}a=d=d.replace(/\s+$/,
"");return!b||0>=c?Ta(a)+1:Ua(a,w,b,c)+1},H:function(){return 4294901760},G:function(a){a>>>=0;var b=w.length;if(4294901760<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(4294901760,65536*Math.ceil(Math.max(a,d)/65536))-va.buffer.byteLength+65535)/65536|0;try{va.grow(d);ua();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},F:a=>{Ga||(f.onExit?.(a),ma=!0);da(a,new Ba(a))},x:function(a){try{var b=O(a);H.close(b);return 0}catch(c){if("undefined"==
typeof H||"ErrnoError"!==c.name)throw c;return c.Ea}},U:function(a,b,c,d){b>>>=0;c>>>=0;d>>>=0;try{a:{var e=O(a);a=b;for(var g,h=b=0;h<c;h++){var k=z[a>>>2>>>0],m=z[a+4>>>2>>>0];a+=8;var l=H.read(e,u,k,m,g);if(0>l){var n=-1;break a}b+=l;if(l<m)break;"undefined"!=typeof g&&(g+=l)}n=b}z[d>>>2>>>0]=n;return 0}catch(q){if("undefined"==typeof H||"ErrnoError"!==q.name)throw q;return q.Ea}},T:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);d>>>=0;try{if(isNaN(b))return 61;var e=
O(a);H.Ja(e,b,c);A[d>>>3>>>0]=BigInt(e.position);e.pb&&0===b&&0===c&&(e.pb=null);return 0}catch(g){if("undefined"==typeof H||"ErrnoError"!==g.name)throw g;return g.Ea}},D:function(a,b,c,d){b>>>=0;c>>>=0;d>>>=0;try{a:{var e=O(a);a=b;for(var g,h=b=0;h<c;h++){var k=z[a>>>2>>>0],m=z[a+4>>>2>>>0];a+=8;var l=H.write(e,u,k,m,g);if(0>l){var n=-1;break a}b+=l;if(l<m)break;"undefined"!=typeof g&&(g+=l)}n=b}z[d>>>2>>>0]=n;return 0}catch(q){if("undefined"==typeof H||"ErrnoError"!==q.name)throw q;return q.Ea}}};
function jd(){var a=kd;a=Object.assign({},a);var b=c=>d=>c(d)>>>0;a.ea=b(a.ea);a.ga=b(a.ga);a.ma=b(a.ma);a.na=(c=>()=>c()>>>0)(a.na);return a}
function ld(){function a(){f.calledRun=!0;if(!ma){ta=!0;f.noFSInit||H.qb||hb();kd.da();H.Hb=!1;na?.(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Da.push(b)}Ca(Da)}}if(0<eb)fb=ld;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Fa();Ca(Ea);0<eb?fb=ld:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()}}var kd;
kd=await (async function(){function a(c){kd=c.exports;c=kd=jd();qc=c.ea;gd=c.ga;X=c.ia;Mc=c.ja;wa=c.ka;fd=c.la;dd=c.ma;cd=c.na;bd=c.oa;ad=c.pa;Zc=c.qa;ed=c.ra;va=c.ca;lc=c.fa;Yc=c.ha;ua();return kd}var b={a:hd};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});xa??=f.locateFile?f.locateFile?f.locateFile("replicad_with_exceptions.wasm",fa):fa+"replicad_with_exceptions.wasm":(new URL("replicad_with_exceptions.wasm",import.meta.url)).href;return a((await Aa(b)).instance)}());
ld();ta?moduleRtn=f:moduleRtn=new Promise((a,b)=>{na=a;oa=b});
;return moduleRtn}export default Module;
