async function Module(moduleArg={}){var moduleRtn;var f=moduleArg,ba=!!globalThis.window,ca=!!globalThis.WorkerGlobalScope,da=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;if(da){const {createRequire:a}=await import("node:module");var require=a(import.meta.url)}var ea="./this.program",fa=(a,b)=>{throw b;},ha=import.meta.url,ia="",ja,ka;
if(da){var fs=require("node:fs");ha.startsWith("file:")&&(ia=require("node:path").dirname(require("node:url").fileURLToPath(ha))+"/");ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(ba||ca){try{ia=(new URL(".",ha)).href}catch{}ca&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType=
"arraybuffer";b.send(null);return new Uint8Array(b.response)});ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}
var ma=console.log.bind(console),p=console.error.bind(console),na,oa=!1,pa,la=a=>a.startsWith("file://"),qa,ra,r,v,x,sa,z,A,ta,ua,D,va,wa=!1;function xa(){var a=ya.buffer;r=new Int8Array(a);x=new Int16Array(a);v=new Uint8Array(a);sa=new Uint16Array(a);z=new Int32Array(a);A=new Uint32Array(a);ta=new Float32Array(a);ua=new Float64Array(a);D=new BigInt64Array(a);va=new BigUint64Array(a)}
function E(a){f.onAbort?.(a);a="Aborted("+a+")";p(a);oa=!0;a+=". Build with -sASSERTIONS for more info.";wa&&za();a=new WebAssembly.RuntimeError(a);ra?.(a);throw a;}var Aa;async function Ba(a){if(!na)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==Aa&&na)a=new Uint8Array(na);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Ca(a,b){try{var c=await Ba(a);return await WebAssembly.instantiate(c,b)}catch(d){p(`failed to asynchronously prepare wasm: ${d}`),E(d)}}async function Da(a){var b=Aa;if(!na&&!la(b)&&!da)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){p(`wasm streaming compile failed: ${d}`),p("falling back to ArrayBuffer instantiation")}return Ca(b,a)}
class Ea{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Fa=a=>{for(;0<a.length;)a.shift()(f)},Ga=[],Ha=[],Ia=()=>{var a=f.preRun.shift();Ha.push(a)},Ja=!0,Ka=globalThis.TextDecoder&&new TextDecoder,La=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},Ma=(a,b=0,c,d)=>{b>>>=0;c=La(a,b,c,d);if(16<c-b&&a.buffer&&Ka)return Ka.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;
65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},F=(a,b,c)=>(a>>>=0)?Ma(v,a,b,c):"",Na=[],Pa=a=>{var b=Na[a];b||(Na[a]=b=Oa.get(a));return b},Qa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ra=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Qa(a.split("/").filter(d=>!!d),!b).join("/"))||
b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Sa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},G=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Ta=(a,b)=>Ra(a+"/"+b),Ua=()=>{if(da){var a=require("node:crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Va=a=>{(Va=Ua())(a)},Wa=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:H.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");
if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Qa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Xa=(a,b)=>{function c(h){for(var k=0;k<h.length&&""===h[k];k++);for(var m=h.length-1;0<=m&&""===h[m];m--);return k>m?[]:h.slice(k,m-k+1)}a=Wa(a).slice(1);b=Wa(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Ya=[],Za=a=>{for(var b=
0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},I=(a,b,c,d)=>{c>>>=0;if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(c>=d)break;b[c++>>>0]=h}else if(2047>=h){if(c+1>=d)break;b[c++>>>0]=192|h>>6;b[c++>>>0]=128|h&63}else if(65535>=h){if(c+2>=d)break;b[c++>>>0]=224|h>>12;b[c++>>>0]=128|h>>6&63;b[c++>>>0]=128|h&63}else{if(c+3>=d)break;b[c++>>>0]=240|h>>18;b[c++>>>0]=128|h>>12&63;b[c++>>>
0]=128|h>>6&63;b[c++>>>0]=128|h&63;g++}}b[c>>>0]=0;return c-e},$a=a=>{var b=Array(Za(a)+1);a=I(a,b,0,b.length);b.length=a;return b},ab=[];function bb(a,b){ab[a]={input:[],output:[],Wa:b};cb(a,db)}
var db={open(a){var b=ab[a.node.rdev];if(!b)throw new H.ua(43);a.tty=b;a.seekable=!1},close(a){a.tty.Wa.fsync(a.tty)},fsync(a){a.tty.Wa.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Wa.Gb)throw new H.ua(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.Wa.Gb(a.tty)}catch(k){throw new H.ua(29);}if(void 0===h&&0===e)throw new H.ua(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Wa.yb)throw new H.ua(60);try{for(var e=0;e<d;e++)a.tty.Wa.yb(a.tty,
b[c+e])}catch(g){throw new H.ua(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},eb={Gb(){a:{if(!Ya.length){var a=null;if(da){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ya=$a(a)}a=Ya.shift()}return a},yb(a,b){null===b||10===b?(ma(Ma(a.output)),a.output=[]):
0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ma(Ma(a.output)),a.output=[])},hc(){return{Ac:25856,Cc:5,zc:191,Bc:35387,yc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},ic(){return 0},jc(){return[24,80]}},fb={yb(a,b){null===b||10===b?(p(Ma(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(p(Ma(a.output)),a.output=[])}},hb=a=>{a=65536*Math.ceil(a/65536);var b=gb(65536,a);b&&v.fill(0,b,b+a);return b},J={Sa:null,Ca(){return J.createNode(null,
"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||H.isFIFO(c))throw new H.ua(63);J.Sa||(J.Sa={dir:{node:{Pa:J.wa.Pa,Ra:J.wa.Ra,lookup:J.wa.lookup,Ua:J.wa.Ua,rename:J.wa.rename,unlink:J.wa.unlink,rmdir:J.wa.rmdir,readdir:J.wa.readdir,symlink:J.wa.symlink},stream:{Ka:J.xa.Ka}},file:{node:{Pa:J.wa.Pa,Ra:J.wa.Ra},stream:{Ka:J.xa.Ka,read:J.xa.read,write:J.xa.write,eb:J.xa.eb,hb:J.xa.hb}},link:{node:{Pa:J.wa.Pa,Ra:J.wa.Ra,readlink:J.wa.readlink},stream:{}},Bb:{node:{Pa:J.wa.Pa,Ra:J.wa.Ra},stream:H.Xb}});
c=H.createNode(a,b,c,d);K(c.mode)?(c.wa=J.Sa.dir.node,c.xa=J.Sa.dir.stream,c.ya={}):H.isFile(c.mode)?(c.wa=J.Sa.file.node,c.xa=J.Sa.file.stream,c.Ea=0,c.ya=null):40960===(c.mode&61440)?(c.wa=J.Sa.link.node,c.xa=J.Sa.link.stream):8192===(c.mode&61440)&&(c.wa=J.Sa.Bb.node,c.xa=J.Sa.Bb.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.ya[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Nc(a){return a.ya?a.ya.subarray?a.ya.subarray(0,a.Ea):new Uint8Array(a.ya):new Uint8Array(0)},wa:{Pa(a){var b={};b.dev=
8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;K(a.mode)?b.size=4096:H.isFile(a.mode)?b.size=a.Ea:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Ra(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Ea!=b&&(0==b?(a.ya=null,a.Ea=0):(c=a.ya,a.ya=new Uint8Array(b),
c&&a.ya.set(c.subarray(0,Math.min(b,a.Ea))),a.Ea=b)))},lookup(){J.pb||(J.pb=new H.ua(44),J.pb.stack="<generic error, no stack>");throw J.pb;},Ua(a,b,c,d){return J.createNode(a,b,c,d)},rename(a,b,c){try{var d=M(b,c)}catch(g){}if(d){if(K(a.mode))for(var e in d.ya)throw new H.ua(55);ib(d)}delete a.parent.ya[a.name];b.ya[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.ya[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=M(a,b),d;for(d in c.ya)throw new H.ua(55);
delete a.ya[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.ya)]},symlink(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new H.ua(28);return a.link}},xa:{read(a,b,c,d,e){var g=a.node.ya;if(e>=a.node.Ea)return 0;a=Math.min(a.node.Ea-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===r.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();
if(b.subarray&&(!a.ya||a.ya.subarray)){if(g)return a.ya=b.subarray(c,c+d),a.Ea=d;if(0===a.Ea&&0===e)return a.ya=b.slice(c,c+d),a.Ea=d;if(e+d<=a.Ea)return a.ya.set(b.subarray(c,c+d),e),d}g=e+d;var h=a.ya?a.ya.length:0;h>=g||(g=Math.max(g,h*(1048576>h?2:1.125)>>>0),0!=h&&(g=Math.max(g,256)),h=a.ya,a.ya=new Uint8Array(g),0<a.Ea&&a.ya.set(h.subarray(0,a.Ea),0));if(a.ya.subarray&&b.subarray)a.ya.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.ya[e+g]=b[c+g];a.Ea=Math.max(a.Ea,e+d);return d},Ka(a,b,c){1===
c?b+=a.position:2===c&&H.isFile(a.node.mode)&&(b+=a.node.Ea);if(0>b)throw new H.ua(28);return b},eb(a,b,c,d,e){if(!H.isFile(a.node.mode))throw new H.ua(43);a=a.node.ya;if(e&2||!a||a.buffer!==r.buffer){d=!0;e=hb(b);if(!e)throw new H.ua(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);r.set(a,e>>>0)}}else d=!1,e=a.byteOffset;return{Aa:e,Wb:d}},hb(a,b,c,d){J.xa.write(a,b,0,d,c,!1);return 0}}},jb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},kb=async a=>
{a=await ja(a);return new Uint8Array(a)},N=0,lb=null,mb=[],ob=async(a,b)=>{"undefined"!=typeof Browser&&nb();for(var c of mb)if(c.canHandle(b))return c.handle(a,b);return a},qb=async(a,b,c,d,e,g,h,k)=>{var m=b?Wa(Ra(a+"/"+b)):a;N++;f.monitorRunDependencies?.(N);try{var n=c;"string"==typeof c&&(n=await kb(c));n=await ob(n,m);k?.();if(!g){c=b;a&&(a="string"==typeof a?a:pb(a),c=b?Ra(a+"/"+b):a);var l=jb(d,e),q=H.create(c,l);if(n){if("string"==typeof n){var u=Array(n.length);b=0;for(var t=n.length;b<
t;++b)u[b]=n.charCodeAt(b);n=u}H.chmod(q,l|146);var w=H.open(q,577);H.write(w,n,0,n.length,0,h);H.close(w);H.chmod(q,l)}}}finally{N--,f.monitorRunDependencies?.(N),0==N&&lb&&(h=lb,lb=null,h())}};
function nb(){var a,b,c;H.rb=!0;a??=f.stdin;b??=f.stdout;c??=f.stderr;a?H.$a("/dev","stdin",a):H.symlink("/dev/tty","/dev/stdin");b?H.$a("/dev","stdout",null,b):H.symlink("/dev/tty","/dev/stdout");c?H.$a("/dev","stderr",null,c):H.symlink("/dev/tty1","/dev/stderr");H.open("/dev/stdin",0);H.open("/dev/stdout",1);H.open("/dev/stderr",1)}function cb(a,b){H.Eb[a]={xa:b}}function K(a){return 16384===(a&61440)}
function M(a,b){var c=K(a.mode)?(c=O(a,"x"))?c:a.wa.lookup?0:2:54;if(c)throw new H.ua(c);for(c=H.Va[rb(a.id,b)];c;c=c.bb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return H.lookup(a,b)}function ib(a){var b=rb(a.parent.id,a.name);if(H.Va[b]===a)H.Va[b]=a.bb;else for(b=H.Va[b];b;){if(b.bb===a){b.bb=a.bb;break}b=b.bb}}
function Q(a,b={}){if(!a)throw new H.ua(44);b.lb??(b.lb=!0);"/"===a.charAt(0)||(a=H.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=H.root,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if("."!==a[g])if(".."===a[g])if(e=Sa(e),H.ub(d)){a=e+"/"+a.slice(g+1).join("/");c--;continue a}else d=d.parent;else{e=Ra(e+"/"+a[g]);try{d=M(d,a[g])}catch(k){if(44===k?.Fa&&h&&b.mc)return{path:e};throw k;}!d.Qa||h&&!b.lb||(d=d.Qa.root);if(40960===(d.mode&61440)&&(!h||
b.La)){if(!d.wa.readlink)throw new H.ua(52);d=d.wa.readlink(d);"/"===d.charAt(0)||(d=Sa(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new H.ua(32);}function pb(a){for(var b;;){if(H.ub(a))return a=a.Ca.Jb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function rb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%H.Va.length}function sb(a){var b=rb(a.parent.id,a.name);a.bb=H.Va[b];H.Va[b]=a}
function O(a,b){return H.Hb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function tb(a,b){if(!K(a.mode))return 54;try{return M(a,b),20}catch(c){}return O(a,"wx")}function ub(a,b,c){try{var d=M(a,b)}catch(e){return e.Fa}if(a=O(a,"wx"))return a;if(c){if(!K(d.mode))return 54;if(H.ub(d)||pb(d)===H.cwd())return 10}else if(K(d.mode))return 31;return 0}function vb(a,b){if(!a)throw new H.ua(b);return a}
function R(a){a=H.ec(a);if(!a)throw new H.ua(8);return a}function wb(a,b=-1){a=Object.assign(new H.Ub,a);if(-1==b)a:{for(b=0;b<=H.Vb;b++)if(!H.streams[b])break a;throw new H.ua(33);}a.fd=b;return H.streams[b]=a}function xb(a,b=-1){a=wb(a,b);a.xa?.Hc?.(a);return a}function yb(a,b,c){var d=a?.xa.Ra;a=d?a:b;d??=b.wa.Ra;vb(d,63);d(a,c)}function zb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.gb)}return b}
function Ab(a){var b={xc:4096,Kc:4096,blocks:1E6,wc:5E5,vc:5E5,files:H.xb,Ic:H.xb-1,Lc:42,flags:2,Qc:255};a.wa.Mb&&Object.assign(b,a.wa.Mb(a.Ca.nc.root));return b}function Bb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return H.Ua(a,b|8192,c)}function Cb(a,b,c,d){yb(a,b,{mode:c&4095|b.mode&-4096,ctime:Date.now(),Fb:d})}function Db(a,b,c){if(K(b.mode))throw new H.ua(31);if(!H.isFile(b.mode))throw new H.ua(28);var d=O(b,"w");if(d)throw new H.ua(d);yb(a,b,{size:c,timestamp:Date.now()})}
function Eb(a,b,c,d){a="string"==typeof a?a:pb(a);b=Ra(a+"/"+b);return H.create(b,jb(c,d))}function Fb(a){if(!(a.kc||a.lc||a.link||a.ya))if(globalThis.XMLHttpRequest)E("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.ya=ka(a.url)}catch(b){throw new H.ua(29);}}
var H={root:null,gb:[],Eb:{},streams:[],xb:1,Va:null,Cb:"/",rb:!1,Hb:!0,ac:null,ob:0,ua:class{name="ErrnoError";constructor(a){this.Fa=a}},Ub:class{Xa={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.Xa.flags}set flags(a){this.Xa.flags=a}get position(){return this.Xa.position}set position(a){this.Xa.position=a}},Tb:class{wa={};xa={};Qa=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Ca=a.Ca;this.id=H.xb++;this.name=b;this.mode=c;this.rdev=d;this.atime=
this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get lc(){return K(this.mode)}get kc(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new H.Tb(a,b,c,d);sb(a);return a},ub(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},Vb:4096,ec:a=>H.streams[a],Xb:{open(a){a.xa=
H.cc(a.node.rdev).xa;a.xa.open?.(a)},Ka(){throw new H.ua(70);}},wb:a=>a>>8,Oc:a=>a&255,ab:(a,b)=>a<<8|b,cc:a=>H.Eb[a],Nb(a,b){function c(k){H.ob--;return b(k)}function d(k){if(k){if(!d.$b)return d.$b=!0,c(k)}else++g>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);H.ob++;1<H.ob&&p(`warning: ${H.ob} FS.syncfs operations in flight at once, probably just doing extra work`);var e=zb(H.root.Ca),g=0,h;for(h of e)h.type.Nb?h.type.Nb(h,a,d):d(null)},Ca(a,b,c){var d="/"===c;if(d&&H.root)throw new H.ua(10);
if(!d&&c){var e=Q(c,{lb:!1});c=e.path;e=e.node;if(e.Qa)throw new H.ua(10);if(!K(e.mode))throw new H.ua(54);}b={type:a,nc:b,Jb:c,gb:[]};a=a.Ca(b);a.Ca=b;b.root=a;d?H.root=a:e&&(e.Qa=b,e.Ca&&e.Ca.gb.push(b));return a},Vc(a){a=Q(a,{lb:!1});if(!a.node.Qa)throw new H.ua(28);a=a.node;var b=a.Qa,c=zb(b);for([,e]of Object.entries(H.Va))for(;e;){var d=e.bb;c.includes(e.Ca)&&ib(e);var e=d}a.Qa=null;a.Ca.gb.splice(a.Ca.gb.indexOf(b),1)},lookup(a,b){return a.wa.lookup(a,b)},Ua(a,b,c){var d=Q(a,{parent:!0}).node;
a=G(a);if(!a)throw new H.ua(28);if("."===a||".."===a)throw new H.ua(20);var e=tb(d,a);if(e)throw new H.ua(e);if(!d.wa.Ua)throw new H.ua(63);return d.wa.Ua(d,a,b,c)},Mb(a){return Ab(Q(a,{La:!0}).node)},Tc(a){return Ab(a.node)},create(a,b=438){return H.Ua(a,b&4095|32768,0)},mkdir(a,b=511){return H.Ua(a,b&1023|16384,0)},Pc(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{H.mkdir(d,b)}catch(g){if(20!=g.Fa)throw g;}}},symlink(a,b){if(!Wa(a))throw new H.ua(44);var c=
Q(b,{parent:!0}).node;if(!c)throw new H.ua(44);b=G(b);var d=tb(c,b);if(d)throw new H.ua(d);if(!c.wa.symlink)throw new H.ua(63);return c.wa.symlink(c,b,a)},rename(a,b){var c=Sa(a),d=Sa(b),e=G(a),g=G(b);var h=Q(a,{parent:!0});var k=h.node;h=Q(b,{parent:!0});h=h.node;if(!k||!h)throw new H.ua(44);if(k.Ca!==h.Ca)throw new H.ua(75);var m=M(k,e);a=Xa(a,d);if("."!==a.charAt(0))throw new H.ua(28);a=Xa(b,c);if("."!==a.charAt(0))throw new H.ua(55);try{var n=M(h,g)}catch(l){}if(m!==n){b=K(m.mode);if(e=ub(k,e,
b))throw new H.ua(e);if(e=n?ub(h,g,b):tb(h,g))throw new H.ua(e);if(!k.wa.rename)throw new H.ua(63);if(m.Qa||n&&n.Qa)throw new H.ua(10);if(h!==k&&(e=O(k,"w")))throw new H.ua(e);ib(m);try{k.wa.rename(m,h,g),m.parent=h}catch(l){throw l;}finally{sb(m)}}},rmdir(a){var b=Q(a,{parent:!0}).node;a=G(a);var c=M(b,a),d=ub(b,a,!0);if(d)throw new H.ua(d);if(!b.wa.rmdir)throw new H.ua(63);if(c.Qa)throw new H.ua(10);b.wa.rmdir(b,a);ib(c)},readdir(a){a=Q(a,{La:!0}).node;return vb(a.wa.readdir,54)(a)},unlink(a){var b=
Q(a,{parent:!0}).node;if(!b)throw new H.ua(44);a=G(a);var c=M(b,a),d=ub(b,a,!1);if(d)throw new H.ua(d);if(!b.wa.unlink)throw new H.ua(63);if(c.Qa)throw new H.ua(10);b.wa.unlink(b,a);ib(c)},readlink(a){a=Q(a).node;if(!a)throw new H.ua(44);if(!a.wa.readlink)throw new H.ua(28);return a.wa.readlink(a)},stat(a,b){a=Q(a,{La:!b}).node;return vb(a.wa.Pa,63)(a)},fstat(a){var b=R(a);a=b.node;var c=b.xa.Pa;b=c?b:a;c??=a.wa.Pa;vb(c,63);return c(b)},lstat(a){return H.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?
Q(a,{La:!c}).node:a;Cb(null,a,b,c)},lchmod(a,b){H.chmod(a,b,!0)},fchmod(a,b){a=R(a);Cb(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?Q(a,{La:!d}).node:a;yb(null,a,{timestamp:Date.now(),Fb:d})},lchown(a,b,c){H.chown(a,b,c,!0)},fchown(a){a=R(a);yb(a,a.node,{timestamp:Date.now(),Fb:!1})},truncate(a,b){if(0>b)throw new H.ua(28);a="string"==typeof a?Q(a,{La:!0}).node:a;Db(null,a,b)},Mc(a,b){a=R(a);if(0>b||0===(a.flags&2097155))throw new H.ua(28);Db(a,a.node,b)},Wc(a,b,c){a=Q(a,{La:!0}).node;vb(a.wa.Ra,
63)(a,{atime:b,mtime:c})},open(a,b,c=438){if(""===a)throw new H.ua(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");var g=Q(a,{La:!(b&131072),mc:!0});d=g.node;a=g.path}g=!1;if(b&64)if(d){if(b&128)throw new H.ua(20);}else{if(e)throw new H.ua(31);d=H.Ua(a,c|511,0);g=!0}if(!d)throw new H.ua(44);8192===(d.mode&61440)&&(b&=-513);
if(b&65536&&!K(d.mode))throw new H.ua(54);if(!g&&(d?40960===(d.mode&61440)?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=K(d.mode)&&("r"!==e||b&576)?31:O(d,e)):e=44,e))throw new H.ua(e);b&512&&!g&&H.truncate(d,0);b&=-131713;b=wb({node:d,path:pb(d),flags:b,seekable:!0,position:0,xa:d.xa,tc:[],error:!1});b.xa.open&&b.xa.open(b);g&&H.chmod(d,c&511);return b},close(a){if(null===a.fd)throw new H.ua(8);a.qb&&(a.qb=null);try{a.xa.close&&a.xa.close(a)}catch(b){throw b;}finally{H.streams[a.fd]=null}a.fd=null},
Ka(a,b,c){if(null===a.fd)throw new H.ua(8);if(!a.seekable||!a.xa.Ka)throw new H.ua(70);if(0!=c&&1!=c&&2!=c)throw new H.ua(28);a.position=a.xa.Ka(a,b,c);a.tc=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new H.ua(28);if(null===a.fd)throw new H.ua(8);if(1===(a.flags&2097155))throw new H.ua(8);if(K(a.node.mode))throw new H.ua(31);if(!a.xa.read)throw new H.ua(28);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new H.ua(70);b=a.xa.read(a,b,c,d,e);g||(a.position+=b);return b},
write(a,b,c,d,e,g){if(0>d||0>e)throw new H.ua(28);if(null===a.fd)throw new H.ua(8);if(0===(a.flags&2097155))throw new H.ua(8);if(K(a.node.mode))throw new H.ua(31);if(!a.xa.write)throw new H.ua(28);a.seekable&&a.flags&1024&&H.Ka(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new H.ua(70);b=a.xa.write(a,b,c,d,e,g);h||(a.position+=b);return b},eb(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new H.ua(2);if(1===(a.flags&2097155))throw new H.ua(2);if(!a.xa.eb)throw new H.ua(43);
if(!b)throw new H.ua(28);return a.xa.eb(a,b,c,d,e)},hb(a,b,c,d,e){return a.xa.hb?a.xa.hb(a,b,c,d,e):0},sb(a,b,c){if(!a.xa.sb)throw new H.ua(59);return a.xa.sb(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&E(`Invalid encoding type "${b.encoding}"`);var c=H.open(a,b.flags);a=H.stat(a).size;var d=new Uint8Array(a);H.read(c,d,0,a,0);"utf8"===b.encoding&&(d=Ma(d));H.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=H.open(a,
c.flags,c.mode);"string"==typeof b&&(b=new Uint8Array($a(b)));ArrayBuffer.isView(b)?H.write(a,b,0,b.byteLength,void 0,c.Dc):E("Unsupported data type");H.close(a)},cwd:()=>H.Cb,chdir(a){a=Q(a,{La:!0});if(null===a.node)throw new H.ua(44);if(!K(a.node.mode))throw new H.ua(54);var b=O(a.node,"x");if(b)throw new H.ua(b);H.Cb=a.path},Sc(){H.rb=!1;for(var a of H.streams)a&&H.close(a)},Jc(a,b){try{var c=Q(a,{La:!b});a=c.path}catch(g){}var d=!1,e=null;try{c=Q(a,{parent:!0}),G(a),c=Q(a,{La:!b}),d=!0,e=c.node}catch(g){}return d?
e:null},Fc(a,b){a="string"==typeof a?a:pb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ra(a+"/"+c);try{H.mkdir(d)}catch(e){if(20!=e.Fa)throw e;}a=d}}return d},$a(a,b,c,d){a=Ta("string"==typeof a?a:pb(a),b);b=jb(!!c,!!d);var e;(e=H.$a).wb??(e.wb=64);e=H.ab(H.$a.wb++,0);cb(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,k,m){for(var n=0,l=0;l<m;l++){try{var q=c()}catch(u){throw new H.ua(29);}if(void 0===q&&0===n)throw new H.ua(6);if(null===q||void 0===q)break;
n++;h[k+l]=q}n&&(g.node.atime=Date.now());return n},write(g,h,k,m){for(var n=0;n<m;n++)try{d(h[k+n])}catch(l){throw new H.ua(29);}m&&(g.node.mtime=g.node.ctime=Date.now());return n}});return Bb(a,b,e)},Ec(a,b,c,d,e){function g(l,q,u,t,w){l=l.node.ya;if(w>=l.length)return 0;t=Math.min(l.length-w,t);if(l.slice)for(var y=0;y<t;y++)q[u+y]=l[w+y];else for(y=0;y<t;y++)q[u+y]=l.get(w+y);return t}class h{Ab=!1;Xa=[];zb=void 0;Qb=0;Pb=0;get(l){if(!(l>this.length-1||0>l)){var q=l%this.chunkSize;return this.zb(l/
this.chunkSize|0)[q]}}Sb(l){this.zb=l}Rb(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);200<=l.status&&300>l.status||304===l.status||E("Couldn't load "+c+". Status: "+l.status);var q=Number(l.getResponseHeader("Content-length")),u,t=(u=l.getResponseHeader("Accept-Ranges"))&&"bytes"===u;l=(u=l.getResponseHeader("Content-Encoding"))&&"gzip"===u;var w=1048576;t||(w=q);var y=this;y.Sb(L=>{var P=L*w,B=(L+1)*w-1;B=Math.min(B,q-1);if("undefined"==typeof y.Xa[L]){var aa=y.Xa;P>B&&E("invalid range ("+
P+", "+B+") or no bytes requested!");B>q-1&&E("only "+q+" bytes available! programmer error!");var C=new XMLHttpRequest;C.open("GET",c,!1);q!==w&&C.setRequestHeader("Range","bytes="+P+"-"+B);C.responseType="arraybuffer";C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");C.send(null);200<=C.status&&300>C.status||304===C.status||E("Couldn't load "+c+". Status: "+C.status);P=void 0!==C.response?new Uint8Array(C.response||[]):$a(C.responseText||"");aa[L]=P}"undefined"==typeof y.Xa[L]&&
E("doXHR failed!");return y.Xa[L]});if(l||!q)w=q=1,w=q=this.zb(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.Qb=q;this.Pb=w;this.Ab=!0}get length(){this.Ab||this.Rb();return this.Qb}get chunkSize(){this.Ab||this.Rb();return this.Pb}}if(globalThis.XMLHttpRequest){ca||E("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var k=new h;var m=void 0}else m=c,k=void 0;var n=Eb(a,b,d,e);k?
n.ya=k:m&&(n.ya=null,n.url=m);Object.defineProperties(n,{Ea:{get:function(){return this.ya.length}}});a={};for(const [l,q]of Object.entries(n.xa))a[l]=(...u)=>{Fb(n);return q(...u)};a.read=(l,q,u,t,w)=>{Fb(n);return g(l,q,u,t,w)};a.eb=(l,q,u)=>{Fb(n);var t=hb(q);if(!t)throw new H.ua(48);g(l,r,t,q,u);return{Aa:t,Wb:!0}};n.xa=a;return n}};function Gb(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?H.cwd():R(a).path;if(0==b.length){if(!c)throw new H.ua(44);return a}return a+"/"+b}
function Hb(a,b){A[a>>>2>>>0]=b.dev;A[a+4>>>2>>>0]=b.mode;A[a+8>>>2>>>0]=b.nlink;A[a+12>>>2>>>0]=b.uid;A[a+16>>>2>>>0]=b.gid;A[a+20>>>2>>>0]=b.rdev;D[a+24>>>3>>>0]=BigInt(b.size);z[a+32>>>2>>>0]=4096;z[a+36>>>2>>>0]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),e=b.ctime.getTime();D[a+40>>>3>>>0]=BigInt(Math.floor(c/1E3));A[a+48>>>2>>>0]=c%1E3*1E6;D[a+56>>>3>>>0]=BigInt(Math.floor(d/1E3));A[a+64>>>2>>>0]=d%1E3*1E6;D[a+72>>>3>>>0]=BigInt(Math.floor(e/1E3));A[a+80>>>2>>>0]=e%1E3*1E6;D[a+88>>>
3>>>0]=BigInt(b.ino);return 0}var Ib=void 0,S=()=>{var a=z[+Ib>>>2>>>0];Ib+=4;return a},T=a=>{a>>>=0;for(var b="";;){var c=v[a++>>>0];if(!c)return b;b+=String.fromCharCode(c)}},Jb={},Kb={},Lb={},U=class extends Error{constructor(a){super(a);this.name="BindingError"}},Mb=a=>{throw new U(a);};
function Nb(a,b,c={}){var d=b.name;if(!a)throw new U(`type "${d}" must have a positive integer typeid pointer`);if(Kb.hasOwnProperty(a)){if(c.fc)return;throw new U(`Cannot register type '${d}' twice`);}Kb[a]=b;delete Lb[a];Jb.hasOwnProperty(a)&&(b=Jb[a],delete Jb[a],b.forEach(e=>e()))}function V(a,b,c={}){return Nb(a,b,c)}
var Ob=(a,b,c)=>{switch(b){case 1:return c?d=>r[d>>>0]:d=>v[d>>>0];case 2:return c?d=>x[d>>>1>>>0]:d=>sa[d>>>1>>>0];case 4:return c?d=>z[d>>>2>>>0]:d=>A[d>>>2>>>0];case 8:return c?d=>D[d>>>3>>>0]:d=>va[d>>>3>>>0];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Pb=a=>{throw new U(a.va.Da.za.name+" instance already deleted");},Qb=!1,Rb=()=>{},Sb=a=>{if(!globalThis.FinalizationRegistry)return Sb=b=>b,a;Qb=new FinalizationRegistry(b=>{b=b.va;--b.count.value;0===b.count.value&&(b.Ga?
b.Oa.Ya(b.Ga):b.Da.za.Ya(b.Aa))});Sb=b=>{var c=b.va;c.Ga&&Qb.register(b,{va:c},b);return b};Rb=b=>{Qb.unregister(b)};return Sb(a)},Tb=[];function Ub(){}
var Vb=(a,b)=>Object.defineProperty(b,"name",{value:a}),Wb={},Xb=(a,b,c)=>{if(void 0===a[b].Ma){var d=a[b];a[b]=function(...e){if(!a[b].Ma.hasOwnProperty(e.length))throw new U(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].Ma})!`);return a[b].Ma[e.length].apply(this,e)};a[b].Ma=[];a[b].Ma[d.Ta]=d}},Yb=(a,b)=>{if(f.hasOwnProperty(a))throw new U(`Cannot register public name '${a}' twice`);f[a]=b;f[a].Ta=void 0},Zb=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,
"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function $b(a,b,c,d,e,g,h,k){this.name=a;this.constructor=b;this.cb=c;this.Ya=d;this.Ja=e;this.bc=g;this.jb=h;this.Zb=k;this.pc=[]}var ac=(a,b,c)=>{for(;b!==c;){if(!b.jb)throw new U(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.jb(a);b=b.Ja}return a},bc=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function cc(a,b){if(null===b){if(this.tb)throw new U(`null is not a valid ${this.name}`);return 0}if(!b.va)throw new U(`Cannot pass "${bc(b)}" as a ${this.name}`);if(!b.va.Aa)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);return ac(b.va.Aa,b.va.Da.za,this.za)}
function dc(a,b){if(null===b){if(this.tb)throw new U(`null is not a valid ${this.name}`);if(this.nb){var c=this.qc();null!==a&&a.push(this.Ya,c);return c}return 0}if(!b||!b.va)throw new U(`Cannot pass "${bc(b)}" as a ${this.name}`);if(!b.va.Aa)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.mb&&b.va.Da.mb)throw new U(`Cannot convert argument of type ${b.va.Oa?b.va.Oa.name:b.va.Da.name} to parameter type ${this.name}`);c=ac(b.va.Aa,b.va.Da.za,this.za);if(this.nb){if(void 0===
b.va.Ga)throw new U("Passing raw pointer to smart pointer is illegal");switch(this.sc){case 0:if(b.va.Oa===this)c=b.va.Ga;else throw new U(`Cannot convert argument of type ${b.va.Oa?b.va.Oa.name:b.va.Da.name} to parameter type ${this.name}`);break;case 1:c=b.va.Ga;break;case 2:if(b.va.Oa===this)c=b.va.Ga;else{var d=b.clone();c=this.rc(c,W(()=>d["delete"]()));null!==a&&a.push(this.Ya,c)}break;default:throw new U("Unsupported sharing policy");}}return c}
function ec(a,b){if(null===b){if(this.tb)throw new U(`null is not a valid ${this.name}`);return 0}if(!b.va)throw new U(`Cannot pass "${bc(b)}" as a ${this.name}`);if(!b.va.Aa)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.va.Da.mb)throw new U(`Cannot convert argument of type ${b.va.Da.name} to parameter type ${this.name}`);return ac(b.va.Aa,b.va.Da.za,this.za)}function fc(a){return this.Ba(A[a>>>2>>>0])}
var gc=(a,b,c)=>{if(b===c)return a;if(void 0===c.Ja)return null;a=gc(a,b,c.Ja);return null===a?null:c.Zb(a)},hc={},ic=(a,b)=>{if(void 0===b)throw new U("ptr should not be undefined");for(;a.Ja;)b=a.jb(b),a=a.Ja;return hc[b]},jc=class extends Error{constructor(a){super(a);this.name="InternalError"}},kc=(a,b)=>{if(!b.Da||!b.Aa)throw new jc("makeClassHandle requires ptr and ptrType");if(!!b.Oa!==!!b.Ga)throw new jc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Sb(Object.create(a,
{va:{value:b,writable:!0}}))};function lc(a,b,c,d,e,g,h,k,m,n,l){this.name=a;this.za=b;this.tb=c;this.mb=d;this.nb=e;this.oc=g;this.sc=h;this.Kb=k;this.qc=m;this.rc=n;this.Ya=l;e||void 0!==b.Ja?this.Ha=dc:(this.Ha=d?cc:ec,this.Ia=null)}
var mc=(a,b)=>{if(!f.hasOwnProperty(a))throw new jc("Replacing nonexistent public symbol");f[a]=b;f[a].Ta=void 0},nc=(a,b,c=[])=>{b=Pa(b)(...c);return"p"==a[0]?b>>>0:b},oc=(a,b)=>(...c)=>nc(a,b,c),pc=(a,b)=>{a=T(a);var c=a.includes("p")?oc(a,b):Pa(b);if("function"!=typeof c)throw new U(`unknown function pointer with signature ${a}: ${b}`);return c};class qc extends Error{}
var sc=a=>{a=rc(a);var b=T(a);X(a);return b},tc=(a,b)=>{function c(g){e[g]||Kb[g]||(Lb[g]?Lb[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new qc(`${a}: `+d.map(sc).join([", "]));},uc=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new jc("Mismatched type converter count");for(var m=0;m<a.length;++m)V(a[m],k[m])}a.forEach(k=>Lb[k]=b);var e=Array(b.length),g=[],h=0;for(let [k,m]of b.entries())Kb.hasOwnProperty(m)?e[k]=Kb[m]:(g.push(m),Jb.hasOwnProperty(m)||(Jb[m]=
[]),Jb[m].push(()=>{e[k]=Kb[m];++h;h===g.length&&d(e)}));0===g.length&&d(e)},vc=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function wc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].Ia)return!0;return!1}
function xc(a,b,c,d,e,g){var h=b.length;if(2>h)throw new U("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,m=wc(b);c=!b[0].Ib;var n=b[0],l=b[1];d=[a,Mb,d,e,vc,n.Ba.bind(n),l?.Ha.bind(l)];for(e=2;e<h;++e)n=b[e],d.push(n.Ha.bind(n));if(!m)for(e=k?1:2;e<b.length;++e)null!==b[e].Ia&&d.push(b[e].Ia);m=wc(b);e=b.length-2;l=[];n=["fn"];k&&n.push("thisWired");for(h=0;h<e;++h)l.push(`arg${h}`),n.push(`arg${h}Wired`);l=l.join(",");n=n.join(",");
l=`return function (${l}) {\n`;m&&(l+="var destructors = [];\n");var q=m?"destructors":"null",u="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");k&&(l+=`var thisWired = toClassParamWire(${q}, this);\n`);for(h=0;h<e;++h){var t=`toArg${h}Wire`;l+=`var arg${h}Wired = ${t}(${q}, arg${h});\n`;u.push(t)}l+=(c||g?"var rv = ":"")+`invoker(${n});\n`;if(m)l+="runDestructors(destructors);\n";else for(h=k?1:2;h<b.length;++h)g=1===h?"thisWired":"arg"+(h-2)+"Wired",
null!==b[h].Ia&&(l+=`${g}_dtor(${g});\n`,u.push(`${g}_dtor`));c&&(l+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(u,l+"}\n"))(...d);return Vb(a,b)}var yc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(A[b+4*d>>>2>>>0]);return c},zc=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Ac=[],Y=[0,1,,1,null,1,!0,1,!1,1];function Cc(a){a>>>=0;9<a&&0===--Y[a+1]&&(Y[a]=void 0,Ac.push(a))}
var Z=a=>{if(!a)throw new U(`Cannot use deleted val. handle = ${a}`);return Y[a]},W=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Ac.pop()||Y.length;Y[b]=a;Y[b+1]=1;return b}},Dc={name:"emscripten::val",Ba:a=>{var b=Z(a);Cc(a);return b},Ha:(a,b)=>W(b),Na:fc,Ia:null},Ec=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.Ba(r[d>>>0])}:function(d){return this.Ba(v[d>>>0])};case 2:return c?function(d){return this.Ba(x[d>>>1>>>0])}:function(d){return this.Ba(sa[d>>>
1>>>0])};case 4:return c?function(d){return this.Ba(z[d>>>2>>>0])}:function(d){return this.Ba(A[d>>>2>>>0])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Fc=(a,b)=>{var c=Kb[a];if(void 0===c)throw a=`${b} has unknown type ${sc(a)}`,new U(a);return c},Gc=(a,b)=>{switch(b){case 4:return function(c){return this.Ba(ta[c>>>2>>>0])};case 8:return function(c){return this.Ba(ua[c>>>3>>>0])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Hc=globalThis.TextDecoder?
new TextDecoder("utf-16le"):void 0,Ic=(a,b,c)=>{a>>>=1;b=La(sa,a,b/2,c);if(16<b-a&&Hc)return Hc.decode(sa.subarray(a>>>0,b>>>0));for(c="";a<b;++a)c+=String.fromCharCode(sa[a>>>0]);return c},Jc=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)x[b>>>1>>>0]=a.charCodeAt(e),b+=2;x[b>>>1>>>0]=0;return b-d},Kc=a=>2*a.length,Lc=(a,b,c)=>{var d="";a>>>=2;for(var e=0;!(e>=b/4);e++){var g=A[a+e>>>0];if(!g&&!c)break;d+=String.fromCodePoint(g)}return d},Mc=
(a,b,c)=>{b>>>=0;c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.codePointAt(e);65535<g&&e++;z[b>>>2>>>0]=g;b+=4;if(b+4>c)break}z[b>>>2>>>0]=0;return b-d},Nc=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Oc=a=>{a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0},Qc=a=>{var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;
if("::"===a)return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(RegExp("[.]","g"),":"),a=a.split(":"),a[a.length-4]=Number(a[a.length-4])+256*Number(a[a.length-3]),a[a.length-3]=Number(a[a.length-2])+256*Number(a[a.length-1]),a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"==typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=Pc(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<
16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]},Rc=1,Sc={},Tc=0,Uc=[],Vc=a=>{var b=Uc.length;Uc.push(a);return b},Wc=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Fc(A[b+4*d>>>2>>>0],`parameter ${d}`);return c},Xc=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(A[b>>>2>>>0]=W(d));return a},Yc={},Zc=a=>{var b=Yc[a];return void 0===b?T(a):b},$c=[0,31,60,91,121,152,182,213,244,274,305,335],ad=[0,31,59,90,120,151,181,212,243,273,304,334],bd={},cd=a=>{pa=a;Ja||0<Tc||(f.onExit?.(a),oa=!0);fa(a,new Ea(a))},dd=
a=>{if(!oa)try{a()}catch(b){b instanceof Ea||"unwind"==b||fa(1,b)}finally{if(!(Ja||0<Tc))try{pa=a=pa,cd(a)}catch(b){b instanceof Ea||"unwind"==b||fa(1,b)}}},ed={},gd=()=>{if(!fd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in ed)void 0===ed[b]?delete a[b]:a[b]=ed[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);fd=c}return fd},fd,kd=a=>{a=a.getArg(hd,0);return jd(a)};
H.Gc=(a,b,c,d,e,g,h,k,m,n)=>{qb(a,b,c,d,e,k,m,n).then(g).catch(h)};H.Rc=qb;H.Va=Array(4096);H.Ca(J,{},"/");H.mkdir("/tmp");H.mkdir("/home");H.mkdir("/home/web_user");
(function(){H.mkdir("/dev");cb(H.ab(1,3),{read:()=>0,write:(d,e,g,h)=>h,Ka:()=>0});Bb("/dev/null",H.ab(1,3));bb(H.ab(5,0),eb);bb(H.ab(6,0),fb);Bb("/dev/tty",H.ab(5,0));Bb("/dev/tty1",H.ab(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Va(a),b=a.byteLength);return a[--b]};H.$a("/dev","random",c);H.$a("/dev","urandom",c);H.mkdir("/dev/shm");H.mkdir("/dev/shm/tmp")})();
(function(){H.mkdir("/proc");var a=H.mkdir("/proc/self");H.mkdir("/proc/self/fd");H.Ca({Ca(){var b=H.createNode(a,"fd",16895,73);b.xa={Ka:J.xa.Ka};b.wa={lookup(c,d){c=+d;var e=R(c);c={parent:null,Ca:{Jb:"fake"},wa:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(H.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();H.ac={MEMFS:J};
(()=>{let a=Ub.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof Ub&&c instanceof Ub))return!1;var d=this.va.Da.za,e=this.va.Aa;c.va=c.va;var g=c.va.Da.za;for(c=c.va.Aa;d.Ja;)e=d.jb(e),d=d.Ja;for(;g.Ja;)c=g.jb(c),g=g.Ja;return d===g&&e===c},clone:function(){this.va.Aa||Pb(this);if(this.va.ib)return this.va.count.value+=1,this;var c=Sb,d=Object,e=d.create,g=Object.getPrototypeOf(this),h=this.va;c=c(e.call(d,g,{va:{value:{count:h.count,fb:h.fb,ib:h.ib,Aa:h.Aa,Da:h.Da,Ga:h.Ga,Oa:h.Oa}}}));
c.va.count.value+=1;c.va.fb=!1;return c},["delete"](){this.va.Aa||Pb(this);if(this.va.fb&&!this.va.ib)throw new U("Object already scheduled for deletion");Rb(this);var c=this.va;--c.count.value;0===c.count.value&&(c.Ga?c.Oa.Ya(c.Ga):c.Da.za.Ya(c.Aa));this.va.ib||(this.va.Ga=void 0,this.va.Aa=void 0)},isDeleted:function(){return!this.va.Aa},deleteLater:function(){this.va.Aa||Pb(this);if(this.va.fb&&!this.va.ib)throw new U("Object already scheduled for deletion");Tb.push(this);this.va.fb=!0;return this}});
const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(lc.prototype,{dc(a){this.Kb&&(a=this.Kb(a));return a},Db(a){this.Ya?.(a)},Na:fc,Ba:function(a){function b(){return this.nb?kc(this.za.cb,{Da:this.oc,Aa:c,Oa:this,Ga:a}):kc(this.za.cb,{Da:this,Aa:a})}var c=this.dc(a);if(!c)return this.Db(a),null;var d=ic(this.za,c);if(void 0!==d){if(0===d.va.count.value)return d.va.Aa=c,d.va.Ga=a,d.clone();d=d.clone();this.Db(a);return d}d=this.za.bc(c);d=Wb[d];if(!d)return b.call(this);d=this.mb?d.Yb:d.pointerType;var e=gc(c,this.za,d.za);return null===
e?b.call(this):this.nb?kc(d.za.cb,{Da:d,Aa:e,Oa:this,Ga:a}):kc(d.za.cb,{Da:d,Aa:e})}});f.noExitRuntime&&(Ja=f.noExitRuntime);f.preloadPlugins&&(mb=f.preloadPlugins);f.print&&(ma=f.print);f.printErr&&(p=f.printErr);f.wasmBinary&&(na=f.wasmBinary);f.thisProgram&&(ea=f.thisProgram);if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();f.FS=H;f.incrementExceptionRefcount=a=>{a=kd(a);ld(a)};f.decrementExceptionRefcount=a=>{a=kd(a);md(a)};
f.getExceptionMessage=a=>{var b=kd(a);a=nd();var c=od(4),d=od(4);pd(b,c,d);b=A[c>>>2>>>0];d=A[d>>>2>>>0];c=F(b);X(b);if(d){var e=F(d);X(d)}qd(a);return[c,e]};
var rc,rd,X,Pc,gb,sd,za,qd,od,nd,md,ld,jd,pd,hd,ya,Oa,td={ba:function(){return f.uc.length},p:function(a,b,c,d){b>>>=0;d>>>=0;return E(`Assertion failed: ${F(a>>>0)}, at: `+[b?F(b):"unknown filename",c,d?F(d):"unknown function"])},aa:function(a,b){return Pa(a>>>0)(b)},$:function(a,b){a>>>=0;try{return a=F(a),H.chmod(a,b),0}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return-c.Fa}},_:function(a,b,c){b>>>=0;try{b=F(b);b=Gb(a,b);if(c&-8)return-28;var d=Q(b,{La:!0}).node;if(!d)return-44;
a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&O(d,a)?-2:0}catch(e){if("undefined"==typeof H||"ErrnoError"!==e.name)throw e;return-e.Fa}},u:function(a,b,c){Ib=c>>>0;try{var d=R(a);switch(b){case 0:var e=S();if(0>e)break;for(;H.streams[e];)e++;return xb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=S(),d.flags|=e,0;case 12:return e=S(),x[e+0>>>1>>>0]=2,0;case 13:case 14:return 0}return-28}catch(g){if("undefined"==typeof H||"ErrnoError"!==g.name)throw g;return-g.Fa}},
Z:function(a,b){try{return Hb(b>>>0,H.fstat(a))}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return-c.Fa}},Y:function(a,b,c){Ib=c>>>0;try{var d=R(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Wa.hc){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=S();z[e>>>2>>>0]=25856;z[e+4>>>2>>>0]=5;z[e+8>>>2>>>0]=191;z[e+12>>>2>>>0]=35387;for(var g=0;32>g;g++)r[e+g+17>>>0]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?
0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Wa.ic)for(e=S(),a=[],g=0;32>g;g++)a.push(r[e+g+17>>>0]);return 0;case 21519:if(!d.tty)return-59;e=S();return z[e>>>2>>>0]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:return e=S(),H.sb(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Wa.jc&&(g=[24,80],e=S(),x[e>>>1>>>0]=g[0],x[e+2>>>1>>>0]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof H||"ErrnoError"!==
h.name)throw h;return-h.Fa}},X:function(a,b){a>>>=0;b>>>=0;try{return a=F(a),Hb(b,H.lstat(a))}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return-c.Fa}},W:function(a,b,c,d){b>>>=0;c>>>=0;try{b=F(b);var e=d&256;b=Gb(a,b,d&4096);return Hb(c,e?H.lstat(b):H.stat(b))}catch(g){if("undefined"==typeof H||"ErrnoError"!==g.name)throw g;return-g.Fa}},x:function(a,b,c,d){b>>>=0;Ib=d>>>=0;try{b=F(b);b=Gb(a,b);var e=d?S():0;return H.open(b,c,e).fd}catch(g){if("undefined"==typeof H||"ErrnoError"!==
g.name)throw g;return-g.Fa}},V:function(a,b){a>>>=0;b>>>=0;try{return a=F(a),Hb(b,H.stat(a))}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return-c.Fa}},N:()=>E(""),w:function(a,b,c,d,e){a>>>=0;c>>>=0;b=T(b>>>0);d=0n===d;let g=h=>h;if(d){const h=8*c;g=k=>BigInt.asUintN(h,k);e=g(e)}V(a,{name:b,Ba:g,Ha:(h,k)=>{"number"==typeof k&&(k=BigInt(k));return k},Na:Ob(b,c,!d),Ia:null})},M:function(a,b,c,d){b=T(b>>>0);V(a>>>0,{name:b,Ba:function(e){return!!e},Ha:function(e,g){return g?c:d},
Na:function(e){return this.Ba(v[e>>>0])},Ia:null})},b:function(a,b,c,d,e,g,h,k,m,n,l,q,u){a>>>=0;b>>>=0;c>>>=0;d>>>=0;g>>>=0;h>>>=0;k>>>=0;m>>>=0;n>>>=0;l>>>=0;q>>>=0;u>>>=0;l=T(l);g=pc(e>>>0,g);k&&=pc(h,k);n&&=pc(m,n);u=pc(q,u);var t=Zb(l);Yb(t,function(){tc(`Cannot construct ${l} due to unbound types`,[d])});uc([a,b,c],d?[d]:[],w=>{w=w[0];if(d){var y=w.za;var L=y.cb}else L=Ub.prototype;w=Vb(l,function(...C){if(Object.getPrototypeOf(this)!==P)throw new U(`Use 'new' to construct ${l}`);if(void 0===
B.Za)throw new U(`${l} has no accessible constructor`);var Bc=B.Za[C.length];if(void 0===Bc)throw new U(`Tried to invoke ctor of ${l} with invalid number of parameters (${C.length}) - expected (${Object.keys(B.Za).toString()}) parameters instead!`);return Bc.apply(this,C)});var P=Object.create(L,{constructor:{value:w}});w.prototype=P;var B=new $b(l,w,P,u,y,g,k,n);if(B.Ja){var aa;(aa=B.Ja).kb??(aa.kb=[]);B.Ja.kb.push(B)}y=new lc(l,B,!0,!1,!1);aa=new lc(l+"*",B,!1,!1,!1);L=new lc(l+" const*",B,!1,!0,
!1);Wb[a]={pointerType:aa,Yb:L};mc(t,w);return[y,aa,L]})},d:function(a,b,c,d,e,g,h,k){a>>>=0;b>>>=0;e>>>=0;g>>>=0;h>>>=0;var m=yc(c,d>>>0);b=T(b);b=zc(b);g=pc(e,g);uc([],[a],n=>{function l(){tc(`Cannot call ${q} due to unbound types`,m)}n=n[0];var q=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var u=n.za.constructor;void 0===u[b]?(l.Ta=c-1,u[b]=l):(Xb(u,b,q),u[b].Ma[c-1]=l);uc([],m,t=>{t=[t[0],null].concat(t.slice(1));t=xc(q,t,null,g,h,k);void 0===u[b].Ma?(t.Ta=c-1,u[b]=t):u[b].Ma[c-
1]=t;if(n.za.kb)for(const w of n.za.kb)w.constructor.hasOwnProperty(b)||(w.constructor[b]=t);return[]});return[]})},c:function(a,b,c,d,e,g){a>>>=0;d>>>=0;e>>>=0;g>>>=0;var h=yc(b,c>>>0);e=pc(d,e);uc([],[a],k=>{k=k[0];var m=`constructor ${k.name}`;void 0===k.za.Za&&(k.za.Za=[]);if(void 0!==k.za.Za[b-1])throw new U(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
k.za.Za[b-1]=()=>{tc(`Cannot construct ${k.name} due to unbound types`,h)};uc([],h,n=>{n.splice(1,0,null);k.za.Za[b-1]=xc(m,n,null,e,g);return[]});return[]})},a:function(a,b,c,d,e,g,h,k,m){a>>>=0;b>>>=0;e>>>=0;g>>>=0;h>>>=0;var n=yc(c,d>>>0);b=T(b);b=zc(b);g=pc(e,g);uc([],[a],l=>{function q(){tc(`Cannot call ${u} due to unbound types`,n)}l=l[0];var u=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&l.za.pc.push(b);var t=l.za.cb,w=t[b];void 0===w||void 0===w.Ma&&w.className!==l.name&&
w.Ta===c-2?(q.Ta=c-2,q.className=l.name,t[b]=q):(Xb(t,b,u),t[b].Ma[c-2]=q);uc([],n,y=>{y=xc(u,y,l,g,h,m);void 0===t[b].Ma?(y.Ta=c-2,t[b]=y):t[b].Ma[c-2]=y;return[]});return[]})},L:function(a){return V(a>>>0,Dc)},g:function(a,b,c,d,e){a>>>=0;c>>>=0;b=T(b>>>0);e=0===e?"object":1===e?"number":"string";switch(e){case "object":function h(){}h.values={};V(a,{name:b,constructor:h,valueType:e,Ba:function(k){return this.constructor.values[k]},Ha:(k,m)=>m.value,Na:Ec(b,c,d),Ia:null});Yb(b,h);break;case "number":var g=
{};V(a,{name:b,vb:g,valueType:e,Ba:k=>k,Ha:(k,m)=>m,Na:Ec(b,c,d),Ia:null});Yb(b,g);delete f[b].Ta;break;case "string":g={},V(a,{name:b,Ob:{},Lb:{},vb:g,valueType:e,Ba:function(k){return this.Lb[k]},Ha:function(k,m){return this.Ob[m]},Na:Ec(b,c,d),Ia:null}),Yb(b,g),delete f[b].Ta}},f:function(a,b,c){b>>>=0;var d=Fc(a>>>0,"enum");b=T(b);switch(d.valueType){case "object":a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Vb(`${d.name}_${b}`,function(){})}});a.values[c]=
d;a[b]=d;break;case "number":d.vb[b]=c;break;case "string":d.Ob[b]=c,d.Lb[c]=b,d.vb[b]=b}},v:function(a,b,c){b=T(b>>>0);V(a>>>0,{name:b,Ba:d=>d,Ha:(d,e)=>e,Na:Gc(b,c>>>0),Ia:null})},n:function(a,b,c,d,e){a>>>=0;c>>>=0;b=T(b>>>0);let g=k=>k;if(0===d){var h=32-8*c;g=k=>k<<h>>>h;e=g(e)}V(a,{name:b,Ba:g,Ha:(k,m)=>m,Na:Ob(b,c,0!==d),Ia:null})},h:function(a,b,c){function d(g){return new e(r.buffer,A[g+4>>>2>>>0],A[g>>>2>>>0])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,
Float64Array,BigInt64Array,BigUint64Array][b];c=T(c>>>0);V(a>>>0,{name:c,Ba:d,Na:d},{fc:!0})},K:function(a,b){b=T(b>>>0);V(a>>>0,{name:b,Ba(c){var d=F(c+4,A[c>>>2>>>0],!0);X(c);return d},Ha(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new U("Cannot pass non-string to std::string");var g=e?Za(d):d.length;var h=rd(4+g+1),k=h+4;A[h>>>2>>>0]=g;e?I(d,v,k,g+1):v.set(d,k>>>0);null!==c&&c.push(X,h);return h},Na:fc,
Ia(c){X(c)}})},s:function(a,b,c){b>>>=0;c>>>=0;c=T(c);if(2===b){var d=Ic;var e=Jc;var g=Kc}else d=Lc,e=Mc,g=Nc;V(a>>>0,{name:c,Ba:h=>{var k=d(h+4,A[h>>>2>>>0]*b,!0);X(h);return k},Ha:(h,k)=>{if("string"!=typeof k)throw new U(`Cannot pass non-string to C++ string type ${c}`);var m=g(k),n=rd(4+m+b);A[n>>>2>>>0]=m/b;e(k,n+4,m+b);null!==h&&h.push(X,n);return n},Na:fc,Ia(h){X(h)}})},J:function(a,b){b=T(b>>>0);V(a>>>0,{Ib:!0,name:b,Ba:()=>{},Ha:()=>{}})},I:function(a){a=F(a>>>0);var b=Oc(a);null===b&&(b=
Qc(a),null===b&&(Sc[a]?b=Sc[a]:(b=Rc++,b="172.29."+(b&255)+"."+(b&65280),Sc[a]=b),a=b));return Oc(a)},H:()=>{Ja=!1;Tc=0},k:function(a,b,c){var [d,...e]=Wc(a,b>>>0);b=d.Ha.bind(d);var g=e.map(m=>m.Na.bind(m));a--;var h={toValue:Z};a=g.map((m,n)=>{var l=`argFromPtr${n}`;h[l]=m;return`${l}(args${n?"+"+8*n:""})`});switch(c){case 0:var k="toValue(handle)";break;case 2:k="new (toValue(handle))";break;case 3:k="";break;case 1:h.getStringOrSymbol=Zc,k="toValue(handle)[getStringOrSymbol(methodName)]"}k+=`(${a})`;
d.Ib||(h.toReturnWire=b,h.emval_returnValue=Xc,k=`return emval_returnValue(toReturnWire, destructorsRef, ${k})`);k=`return function (handle, methodName, destructorsRef, args) {\n${k}\n}`;c=(new Function(Object.keys(h),k))(...Object.values(h));k=`methodCaller<(${e.map(m=>m.name)}) => ${d.name}>`;return Vc(Vb(k,c))},e:Cc,G:function(a){a>>>=0;if(!a)return W(globalThis);a=Zc(a);return W(globalThis[a])},q:function(a,b){b>>>=0;a=Z(a>>>0);b=Z(b);return W(a[b])},o:function(a){a>>>=0;9<a&&(Y[a+1]+=1)},j:function(a,
b,c,d,e){return Uc[a>>>0](b>>>0,c>>>0,d>>>0,e>>>0)},m:function(a){return W(Zc(a>>>0))},i:function(a){a>>>=0;var b=Z(a);vc(b);Cc(a)},r:function(a,b,c){b>>>=0;c>>>=0;a=Z(a>>>0);b=Z(b);c=Z(c);a[b]=c},l:function(a){a=Z(a>>>0);return W(typeof a)},F:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);z[b>>>2>>>0]=a.getSeconds();z[b+4>>>2>>>0]=a.getMinutes();z[b+8>>>2>>>0]=a.getHours();z[b+12>>>2>>>0]=a.getDate();z[b+16>>>2>>>0]=a.getMonth();z[b+20>>>2>>>0]=a.getFullYear()-
1900;z[b+24>>>2>>>0]=a.getDay();var c=a.getFullYear();z[b+28>>>2>>>0]=(0!==c%4||0===c%100&&0!==c%400?ad:$c)[a.getMonth()]+a.getDate()-1|0;z[b+36>>>2>>>0]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();z[b+32>>>2>>>0]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},E:(a,b)=>{bd[a]&&(clearTimeout(bd[a].id),delete bd[a]);if(!b)return 0;var c=setTimeout(()=>{delete bd[a];dd(()=>sd(a,performance.now()))},b);bd[a]=
{id:c,Uc:b};return 0},D:function(a,b,c,d){c>>>=0;d>>>=0;var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();A[a>>>0>>>2>>>0]=60*Math.max(g,e);z[b>>>0>>>2>>>0]=Number(g!=e);b=h=>{var k=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(I(a,v,c,17),I(b,v,d,17)):(I(a,v,d,17),I(b,v,c,17))},U:function(a,b,c){if(!(0<=a&&3>=a))return 28;D[c>>>0>>>3>>>0]=BigInt(Math.round(1E6*
(0===a?Date.now():performance.now())));return 0},C:()=>Date.now(),B:function(a,b,c){b>>>=0;var d=Error().stack.toString(),e=d.split("\n");d="";var g=RegExp("\\s*(.*?)@(.*?):([0-9]+):([0-9]+)"),h=RegExp("\\s*at (.*?) \\((.*):(.*):(.*)\\)"),k;for(k of e){var m=h.exec(k);if(5==m?.length){e=m[1];var n=m[2];var l=m[3];m=m[4]}else if(m=g.exec(k),4<=m?.length)e=m[1],n=m[2],l=m[3],m=m[4]|0;else{d+=k+"\n";continue}"_emscripten_log"==e||"_emscripten_get_callstack"==e?d="":a&24&&(a&64&&(n=n.substring(n.replace(/\\/g,
"/").lastIndexOf("/")+1)),d+=`    at ${e} (${n}:${l}:${m})\n`)}a=d=d.replace(/\s+$/,"");return!b||0>=c?Za(a)+1:I(a,v,b,c)+1},A:function(){return 4294901760},z:function(a){a>>>=0;var b=v.length;if(4294901760<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(4294901760,65536*Math.ceil(Math.max(a,d)/65536))-ya.buffer.byteLength+65535)/65536|0;try{ya.grow(d);xa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},T:function(a,b){a>>>=0;b>>>=0;var c=0,
d=0,e;for(e of gd()){var g=b+c;A[a+d>>>2>>>0]=g;c+=I(e,v,g,Infinity)+1;d+=4}return 0},S:function(a,b){a>>>=0;b>>>=0;var c=gd();A[a>>>2>>>0]=c.length;a=0;for(var d of c)a+=Za(d)+1;A[b>>>2>>>0]=a;return 0},y:a=>{pa=a;cd(a)},t:function(a){try{var b=R(a);H.close(b);return 0}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return c.Fa}},R:function(a,b,c,d){b>>>=0;c>>>=0;d>>>=0;try{a:{var e=R(a);a=b;for(var g,h=b=0;h<c;h++){var k=A[a>>>2>>>0],m=A[a+4>>>2>>>0];a+=8;var n=H.read(e,r,k,m,g);
if(0>n){var l=-1;break a}b+=n;if(n<m)break;"undefined"!=typeof g&&(g+=n)}l=b}A[d>>>2>>>0]=l;return 0}catch(q){if("undefined"==typeof H||"ErrnoError"!==q.name)throw q;return q.Fa}},Q:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);d>>>=0;try{if(isNaN(b))return 61;var e=R(a);H.Ka(e,b,c);D[d>>>3>>>0]=BigInt(e.position);e.qb&&0===b&&0===c&&(e.qb=null);return 0}catch(g){if("undefined"==typeof H||"ErrnoError"!==g.name)throw g;return g.Fa}},P:function(a,b,c,d){b>>>=0;c>>>=0;d>>>=
0;try{a:{var e=R(a);a=b;for(var g,h=b=0;h<c;h++){var k=A[a>>>2>>>0],m=A[a+4>>>2>>>0];a+=8;var n=H.write(e,r,k,m,g);if(0>n){var l=-1;break a}b+=n;if(n<m)break;"undefined"!=typeof g&&(g+=n)}l=b}A[d>>>2>>>0]=l;return 0}catch(q){if("undefined"==typeof H||"ErrnoError"!==q.name)throw q;return q.Fa}},O:cd};function ud(){var a=vd;a=Object.assign({},a);var b=c=>d=>c(d)>>>0;a.ea=b(a.ea);a.ga=b(a.ga);a.ka=(c=>(d,e)=>c(d,e)>>>0)(a.ka);a.oa=b(a.oa);a.pa=(c=>()=>c()>>>0)(a.pa);return a}
function wd(){function a(){f.calledRun=!0;if(!oa){wa=!0;f.noFSInit||H.rb||nb();vd.da();H.Hb=!1;qa?.(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Ga.push(b)}Fa(Ga)}}if(0<N)lb=wd;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ia();Fa(Ha);0<N?lb=wd:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()}}var vd;
vd=await (async function(){function a(c){vd=c.exports;c=vd=ud();rc=c.ea;rd=c.ga;X=c.ia;Pc=c.ja;gb=c.ka;sd=c.la;za=c.ma;qd=c.na;od=c.oa;nd=c.pa;md=c.qa;ld=c.ra;jd=c.sa;pd=c.ta;ya=c.ca;Oa=c.fa;hd=c.ha;xa();return vd}var b={a:td};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});Aa??=f.locateFile?f.locateFile?f.locateFile("replicad_with_exceptions.wasm",ia):ia+"replicad_with_exceptions.wasm":(new URL("replicad_with_exceptions.wasm",import.meta.url)).href;
return a((await Da(b)).instance)}());wd();wa?moduleRtn=f:moduleRtn=new Promise((a,b)=>{qa=a;ra=b});
;return moduleRtn}export default Module;
