async function Module(moduleArg={}){var moduleRtn;var f=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;if(ca){const {createRequire:a}=await import("node:module");var require=a(import.meta.url)}var da=(a,b)=>{throw b;},ea=import.meta.url,fa="",ha,ia;
if(ca){var fs=require("node:fs");ea.startsWith("file:")&&(fa=require("node:path").dirname(require("node:url").fileURLToPath(ea))+"/");ia=a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a)};ha=async a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);da=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{fa=(new URL(".",ea)).href}catch{}ba&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ha=async a=>{if(ja(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ka=console.log.bind(console),p=console.error.bind(console),la,ma=!1,ja=a=>a.startsWith("file://"),na,oa,u,w,x,pa,y,z,qa,ra,A,sa,ta=!1;
function ua(){var a=va.buffer;u=new Int8Array(a);x=new Int16Array(a);w=new Uint8Array(a);pa=new Uint16Array(a);y=new Int32Array(a);z=new Uint32Array(a);qa=new Float32Array(a);ra=new Float64Array(a);A=new BigInt64Array(a);sa=new BigUint64Array(a)}function D(a){f.onAbort?.(a);a="Aborted("+a+")";p(a);ma=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");oa?.(a);throw a;}var wa;
async function xa(a){if(!la)try{var b=await ha(a);return new Uint8Array(b)}catch{}if(a==wa&&la)a=new Uint8Array(la);else if(ia)a=ia(a);else throw"both async and sync fetching of the wasm failed";return a}async function ya(a,b){try{var c=await xa(a);return await WebAssembly.instantiate(c,b)}catch(d){p(`failed to asynchronously prepare wasm: ${d}`),D(d)}}
async function za(a){var b=wa;if(!la&&!ja(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){p(`wasm streaming compile failed: ${d}`),p("falling back to ArrayBuffer instantiation")}return ya(b,a)}class Aa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Ba=a=>{for(;0<a.length;)a.shift()(f)},Ca=[],Da=[],Ea=()=>{var a=f.preRun.shift();Da.push(a)},Fa=!0;
class Ga{constructor(a){this.qa=a-24}cb(a,b){z[this.qa+16>>>2>>>0]=0;z[this.qa+4>>>2>>>0]=a;z[this.qa+8>>>2>>>0]=b}}
var Ha=0,Ia=0,Ja=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ka=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ja(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},La=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},E=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],
Ma=(a,b)=>Ka(a+"/"+b),Na=()=>{if(ca){var a=require("node:crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Oa=a=>{(Oa=Na())(a)},Pa=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:H.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ja(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Qa=(a,b)=>{function c(h){for(var k=0;k<h.length&&""===h[k];k++);for(var m=
h.length-1;0<=m&&""===h[m];m--);return k>m?[]:h.slice(k,m-k+1)}a=Pa(a).slice(1);b=Pa(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},Ra=globalThis.TextDecoder&&new TextDecoder,Sa=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},Ta=(a,b=0,c,d)=>{b>>>=0;c=Sa(a,b,c,d);if(16<c-b&&a.buffer&&Ra)return Ra.decode(a.subarray(b,
c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ua=[],Va=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Wa=(a,b,c,d)=>{c>>>=0;if(!(0<d))return 0;
var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(c>=d)break;b[c++>>>0]=h}else if(2047>=h){if(c+1>=d)break;b[c++>>>0]=192|h>>6;b[c++>>>0]=128|h&63}else if(65535>=h){if(c+2>=d)break;b[c++>>>0]=224|h>>12;b[c++>>>0]=128|h>>6&63;b[c++>>>0]=128|h&63}else{if(c+3>=d)break;b[c++>>>0]=240|h>>18;b[c++>>>0]=128|h>>12&63;b[c++>>>0]=128|h>>6&63;b[c++>>>0]=128|h&63;g++}}b[c>>>0]=0;return c-e},Xa=a=>{var b=Array(Va(a)+1);a=Wa(a,b,0,b.length);b.length=a;return b},Ya=[];
function Za(a,b){Ya[a]={input:[],output:[],Oa:b};$a(a,ab)}
var ab={open(a){var b=Ya[a.node.rdev];if(!b)throw new H.ka(43);a.tty=b;a.seekable=!1},close(a){a.tty.Oa.fsync(a.tty)},fsync(a){a.tty.Oa.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Oa.zb)throw new H.ka(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.Oa.zb(a.tty)}catch(k){throw new H.ka(29);}if(void 0===h&&0===e)throw new H.ka(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Oa.rb)throw new H.ka(60);try{for(var e=0;e<d;e++)a.tty.Oa.rb(a.tty,
b[c+e])}catch(g){throw new H.ka(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},bb={zb(){a:{if(!Ua.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ua=Xa(a)}a=Ua.shift()}return a},rb(a,b){null===b||10===b?(ka(Ta(a.output)),a.output=[]):
0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ka(Ta(a.output)),a.output=[])},ac(){return{yc:25856,Ac:5,xc:191,zc:35387,wc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},bc(){return 0},cc(){return[24,80]}},cb={rb(a,b){null===b||10===b?(p(Ta(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(p(Ta(a.output)),a.output=[])}},I={Ia:null,sa(){return I.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||H.isFIFO(c))throw new H.ka(63);
I.Ia||(I.Ia={dir:{node:{Fa:I.ma.Fa,Ha:I.ma.Ha,lookup:I.ma.lookup,Ma:I.ma.Ma,rename:I.ma.rename,unlink:I.ma.unlink,rmdir:I.ma.rmdir,readdir:I.ma.readdir,symlink:I.ma.symlink},stream:{Ba:I.na.Ba}},file:{node:{Fa:I.ma.Fa,Ha:I.ma.Ha},stream:{Ba:I.na.Ba,read:I.na.read,write:I.na.write,Ua:I.na.Ua,Ya:I.na.Ya}},link:{node:{Fa:I.ma.Fa,Ha:I.ma.Ha,readlink:I.ma.readlink},stream:{}},tb:{node:{Fa:I.ma.Fa,Ha:I.ma.Ha},stream:H.Ob}});c=H.createNode(a,b,c,d);J(c.mode)?(c.ma=I.Ia.dir.node,c.na=I.Ia.dir.stream,c.oa=
{}):H.isFile(c.mode)?(c.ma=I.Ia.file.node,c.na=I.Ia.file.stream,c.va=0,c.oa=null):40960===(c.mode&61440)?(c.ma=I.Ia.link.node,c.na=I.Ia.link.stream):8192===(c.mode&61440)&&(c.ma=I.Ia.tb.node,c.na=I.Ia.tb.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.oa[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Lc(a){return a.oa?a.oa.subarray?a.oa.subarray(0,a.va):new Uint8Array(a.oa):new Uint8Array(0)},ma:{Fa(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=
0;b.rdev=a.rdev;J(a.mode)?b.size=4096:H.isFile(a.mode)?b.size=a.va:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Ha(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.va!=b&&(0==b?(a.oa=null,a.va=0):(c=a.oa,a.oa=new Uint8Array(b),c&&a.oa.set(c.subarray(0,Math.min(b,a.va))),a.va=b)))},lookup(){I.hb||(I.hb=
new H.ka(44),I.hb.stack="<generic error, no stack>");throw I.hb;},Ma(a,b,c,d){return I.createNode(a,b,c,d)},rename(a,b,c){try{var d=K(b,c)}catch(g){}if(d){if(J(a.mode))for(var e in d.oa)throw new H.ka(55);db(d)}delete a.parent.oa[a.name];b.oa[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.oa[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=K(a,b),d;for(d in c.oa)throw new H.ka(55);delete a.oa[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.oa)]},
symlink(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new H.ka(28);return a.link}},na:{read(a,b,c,d,e){var g=a.node.oa;if(e>=a.node.va)return 0;a=Math.min(a.node.va-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===u.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.oa||a.oa.subarray)){if(g)return a.oa=b.subarray(c,c+d),a.va=d;if(0===a.va&&
0===e)return a.oa=b.slice(c,c+d),a.va=d;if(e+d<=a.va)return a.oa.set(b.subarray(c,c+d),e),d}g=e+d;var h=a.oa?a.oa.length:0;h>=g||(g=Math.max(g,h*(1048576>h?2:1.125)>>>0),0!=h&&(g=Math.max(g,256)),h=a.oa,a.oa=new Uint8Array(g),0<a.va&&a.oa.set(h.subarray(0,a.va),0));if(a.oa.subarray&&b.subarray)a.oa.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.oa[e+g]=b[c+g];a.va=Math.max(a.va,e+d);return d},Ba(a,b,c){1===c?b+=a.position:2===c&&H.isFile(a.node.mode)&&(b+=a.node.va);if(0>b)throw new H.ka(28);return b},
Ua(a,b,c,d,e){if(!H.isFile(a.node.mode))throw new H.ka(43);a=a.node.oa;if(e&2||!a||a.buffer!==u.buffer){d=!0;D();e=void 0;if(!e)throw new H.ka(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);u.set(a,e>>>0)}}else d=!1,e=a.byteOffset;return{qa:e,sc:d}},Ya(a,b,c,d){I.na.write(a,b,0,d,c,!1);return 0}}},eb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},fb=async a=>{a=await ha(a);return new Uint8Array(a)},gb=0,hb=null,ib=[],jb=async(a,b)=>{"undefined"!=
typeof Browser&&Browser.cb();for(var c of ib)if(c.canHandle(b))return c.handle(a,b);return a},lb=async(a,b,c,d,e,g,h,k)=>{var m=b?Pa(Ka(a+"/"+b)):a;gb++;f.monitorRunDependencies?.(gb);try{var l=c;"string"==typeof c&&(l=await fb(c));l=await jb(l,m);k?.();if(!g){c=b;a&&(a="string"==typeof a?a:kb(a),c=b?Ka(a+"/"+b):a);var n=eb(d,e),q=H.create(c,n);if(l){if("string"==typeof l){var r=Array(l.length);b=0;for(var t=l.length;b<t;++b)r[b]=l.charCodeAt(b);l=r}H.chmod(q,n|146);var v=H.open(q,577);H.write(v,
l,0,l.length,0,h);H.close(v);H.chmod(q,n)}}}finally{gb--,f.monitorRunDependencies?.(gb),0==gb&&hb&&(h=hb,hb=null,h())}};function $a(a,b){H.wb[a]={na:b}}function J(a){return 16384===(a&61440)}function K(a,b){var c=J(a.mode)?(c=M(a,"x"))?c:a.ma.lookup?0:2:54;if(c)throw new H.ka(c);for(c=H.Na[mb(a.id,b)];c;c=c.Sa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return H.lookup(a,b)}
function db(a){var b=mb(a.parent.id,a.name);if(H.Na[b]===a)H.Na[b]=a.Sa;else for(b=H.Na[b];b;){if(b.Sa===a){b.Sa=a.Sa;break}b=b.Sa}}
function N(a,b={}){if(!a)throw new H.ka(44);b.bb??(b.bb=!0);"/"===a.charAt(0)||(a=H.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=H.root,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if("."!==a[g])if(".."===a[g])if(e=La(e),H.mb(d)){a=e+"/"+a.slice(g+1).join("/");c--;continue a}else d=d.parent;else{e=Ka(e+"/"+a[g]);try{d=K(d,a[g])}catch(k){if(44===k?.wa&&h&&b.fc)return{path:e};throw k;}!d.Ga||h&&!b.bb||(d=d.Ga.root);if(40960===(d.mode&61440)&&(!h||
b.Da)){if(!d.ma.readlink)throw new H.ka(52);d=d.ma.readlink(d);"/"===d.charAt(0)||(d=La(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new H.ka(32);}function kb(a){for(var b;;){if(H.mb(a))return a=a.sa.Db,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function mb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%H.Na.length}function nb(a){var b=mb(a.parent.id,a.name);a.Sa=H.Na[b];H.Na[b]=a}
function M(a,b){return H.Ab?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function pb(a,b){if(!J(a.mode))return 54;try{return K(a,b),20}catch(c){}return M(a,"wx")}function qb(a,b,c){try{var d=K(a,b)}catch(e){return e.wa}if(a=M(a,"wx"))return a;if(c){if(!J(d.mode))return 54;if(H.mb(d)||kb(d)===H.cwd())return 10}else if(J(d.mode))return 31;return 0}function rb(a,b){if(!a)throw new H.ka(b);return a}
function O(a){a=H.Xb(a);if(!a)throw new H.ka(8);return a}function sb(a,b=-1){a=Object.assign(new H.Mb,a);if(-1==b)a:{for(b=0;b<=H.Nb;b++)if(!H.streams[b])break a;throw new H.ka(33);}a.fd=b;return H.streams[b]=a}function tb(a,b=-1){a=sb(a,b);a.na?.Fc?.(a);return a}function ub(a,b,c){var d=a?.na.Ha;a=d?a:b;d??=b.ma.Ha;rb(d,63);d(a,c)}function vb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.Xa)}return b}
function wb(a){var b={vc:4096,Ic:4096,blocks:1E6,uc:5E5,tc:5E5,files:H.qb,Gc:H.qb-1,Jc:42,flags:2,Oc:255};a.ma.Ib&&Object.assign(b,a.ma.Ib(a.sa.hc.root));return b}function xb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return H.Ma(a,b|8192,c)}function yb(a,b,c,d){ub(a,b,{mode:c&4095|b.mode&-4096,ctime:Date.now(),xb:d})}function zb(a,b,c){if(J(b.mode))throw new H.ka(31);if(!H.isFile(b.mode))throw new H.ka(28);var d=M(b,"w");if(d)throw new H.ka(d);ub(a,b,{size:c,timestamp:Date.now()})}
function Ab(a,b,c,d){a="string"==typeof a?a:kb(a);b=Ka(a+"/"+b);return H.create(b,eb(c,d))}function Bb(a){if(!(a.dc||a.ec||a.link||a.oa))if(globalThis.XMLHttpRequest)D("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.oa=ia(a.url)}catch(b){throw new H.ka(29);}}
var H={root:null,Xa:[],wb:{},streams:[],qb:1,Na:null,ub:"/",jb:!1,Ab:!0,Tb:null,gb:0,ka:class{name="ErrnoError";constructor(a){this.wa=a}},Mb:class{La={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.La.flags}set flags(a){this.La.flags=a}get position(){return this.La.position}set position(a){this.La.position=a}},Lb:class{ma={};na={};Ga=null;constructor(a,b,c,d){a||=this;this.parent=a;this.sa=a.sa;this.id=H.qb++;this.name=b;this.mode=c;this.rdev=d;this.atime=
this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get ec(){return J(this.mode)}get dc(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new H.Lb(a,b,c,d);nb(a);return a},mb(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},Nb:4096,Xb:a=>H.streams[a],Ob:{open(a){a.na=
H.Vb(a.node.rdev).na;a.na.open?.(a)},Ba(){throw new H.ka(70);}},pb:a=>a>>8,Mc:a=>a&255,Ra:(a,b)=>a<<8|b,Vb:a=>H.wb[a],Jb(a,b){function c(k){H.gb--;return b(k)}function d(k){if(k){if(!d.Rb)return d.Rb=!0,c(k)}else++g>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);H.gb++;1<H.gb&&p(`warning: ${H.gb} FS.syncfs operations in flight at once, probably just doing extra work`);var e=vb(H.root.sa),g=0,h;for(h of e)h.type.Jb?h.type.Jb(h,a,d):d(null)},sa(a,b,c){var d="/"===c;if(d&&H.root)throw new H.ka(10);
if(!d&&c){var e=N(c,{bb:!1});c=e.path;e=e.node;if(e.Ga)throw new H.ka(10);if(!J(e.mode))throw new H.ka(54);}b={type:a,hc:b,Db:c,Xa:[]};a=a.sa(b);a.sa=b;b.root=a;d?H.root=a:e&&(e.Ga=b,e.sa&&e.sa.Xa.push(b));return a},Sc(a){a=N(a,{bb:!1});if(!a.node.Ga)throw new H.ka(28);a=a.node;var b=a.Ga,c=vb(b);for([,e]of Object.entries(H.Na))for(;e;){var d=e.Sa;c.includes(e.sa)&&db(e);var e=d}a.Ga=null;a.sa.Xa.splice(a.sa.Xa.indexOf(b),1)},lookup(a,b){return a.ma.lookup(a,b)},Ma(a,b,c){var d=N(a,{parent:!0}).node;
a=E(a);if(!a)throw new H.ka(28);if("."===a||".."===a)throw new H.ka(20);var e=pb(d,a);if(e)throw new H.ka(e);if(!d.ma.Ma)throw new H.ka(63);return d.ma.Ma(d,a,b,c)},Ib(a){return wb(N(a,{Da:!0}).node)},Rc(a){return wb(a.node)},create(a,b=438){return H.Ma(a,b&4095|32768,0)},mkdir(a,b=511){return H.Ma(a,b&1023|16384,0)},Nc(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{H.mkdir(d,b)}catch(g){if(20!=g.wa)throw g;}}},symlink(a,b){if(!Pa(a))throw new H.ka(44);var c=
N(b,{parent:!0}).node;if(!c)throw new H.ka(44);b=E(b);var d=pb(c,b);if(d)throw new H.ka(d);if(!c.ma.symlink)throw new H.ka(63);return c.ma.symlink(c,b,a)},rename(a,b){var c=La(a),d=La(b),e=E(a),g=E(b);var h=N(a,{parent:!0});var k=h.node;h=N(b,{parent:!0});h=h.node;if(!k||!h)throw new H.ka(44);if(k.sa!==h.sa)throw new H.ka(75);var m=K(k,e);a=Qa(a,d);if("."!==a.charAt(0))throw new H.ka(28);a=Qa(b,c);if("."!==a.charAt(0))throw new H.ka(55);try{var l=K(h,g)}catch(n){}if(m!==l){b=J(m.mode);if(e=qb(k,e,
b))throw new H.ka(e);if(e=l?qb(h,g,b):pb(h,g))throw new H.ka(e);if(!k.ma.rename)throw new H.ka(63);if(m.Ga||l&&l.Ga)throw new H.ka(10);if(h!==k&&(e=M(k,"w")))throw new H.ka(e);db(m);try{k.ma.rename(m,h,g),m.parent=h}catch(n){throw n;}finally{nb(m)}}},rmdir(a){var b=N(a,{parent:!0}).node;a=E(a);var c=K(b,a),d=qb(b,a,!0);if(d)throw new H.ka(d);if(!b.ma.rmdir)throw new H.ka(63);if(c.Ga)throw new H.ka(10);b.ma.rmdir(b,a);db(c)},readdir(a){a=N(a,{Da:!0}).node;return rb(a.ma.readdir,54)(a)},unlink(a){var b=
N(a,{parent:!0}).node;if(!b)throw new H.ka(44);a=E(a);var c=K(b,a),d=qb(b,a,!1);if(d)throw new H.ka(d);if(!b.ma.unlink)throw new H.ka(63);if(c.Ga)throw new H.ka(10);b.ma.unlink(b,a);db(c)},readlink(a){a=N(a).node;if(!a)throw new H.ka(44);if(!a.ma.readlink)throw new H.ka(28);return a.ma.readlink(a)},stat(a,b){a=N(a,{Da:!b}).node;return rb(a.ma.Fa,63)(a)},fstat(a){var b=O(a);a=b.node;var c=b.na.Fa;b=c?b:a;c??=a.ma.Fa;rb(c,63);return c(b)},lstat(a){return H.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?
N(a,{Da:!c}).node:a;yb(null,a,b,c)},lchmod(a,b){H.chmod(a,b,!0)},fchmod(a,b){a=O(a);yb(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?N(a,{Da:!d}).node:a;ub(null,a,{timestamp:Date.now(),xb:d})},lchown(a,b,c){H.chown(a,b,c,!0)},fchown(a){a=O(a);ub(a,a.node,{timestamp:Date.now(),xb:!1})},truncate(a,b){if(0>b)throw new H.ka(28);a="string"==typeof a?N(a,{Da:!0}).node:a;zb(null,a,b)},Kc(a,b){a=O(a);if(0>b||0===(a.flags&2097155))throw new H.ka(28);zb(a,a.node,b)},Tc(a,b,c){a=N(a,{Da:!0}).node;rb(a.ma.Ha,
63)(a,{atime:b,mtime:c})},open(a,b,c=438){if(""===a)throw new H.ka(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");var g=N(a,{Da:!(b&131072),fc:!0});d=g.node;a=g.path}g=!1;if(b&64)if(d){if(b&128)throw new H.ka(20);}else{if(e)throw new H.ka(31);d=H.Ma(a,c|511,0);g=!0}if(!d)throw new H.ka(44);8192===(d.mode&61440)&&(b&=-513);
if(b&65536&&!J(d.mode))throw new H.ka(54);if(!g&&(d?40960===(d.mode&61440)?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=J(d.mode)&&("r"!==e||b&576)?31:M(d,e)):e=44,e))throw new H.ka(e);b&512&&!g&&H.truncate(d,0);b&=-131713;b=sb({node:d,path:kb(d),flags:b,seekable:!0,position:0,na:d.na,qc:[],error:!1});b.na.open&&b.na.open(b);g&&H.chmod(d,c&511);return b},close(a){if(null===a.fd)throw new H.ka(8);a.ib&&(a.ib=null);try{a.na.close&&a.na.close(a)}catch(b){throw b;}finally{H.streams[a.fd]=null}a.fd=null},
Ba(a,b,c){if(null===a.fd)throw new H.ka(8);if(!a.seekable||!a.na.Ba)throw new H.ka(70);if(0!=c&&1!=c&&2!=c)throw new H.ka(28);a.position=a.na.Ba(a,b,c);a.qc=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new H.ka(28);if(null===a.fd)throw new H.ka(8);if(1===(a.flags&2097155))throw new H.ka(8);if(J(a.node.mode))throw new H.ka(31);if(!a.na.read)throw new H.ka(28);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new H.ka(70);b=a.na.read(a,b,c,d,e);g||(a.position+=b);return b},
write(a,b,c,d,e,g){if(0>d||0>e)throw new H.ka(28);if(null===a.fd)throw new H.ka(8);if(0===(a.flags&2097155))throw new H.ka(8);if(J(a.node.mode))throw new H.ka(31);if(!a.na.write)throw new H.ka(28);a.seekable&&a.flags&1024&&H.Ba(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new H.ka(70);b=a.na.write(a,b,c,d,e,g);h||(a.position+=b);return b},Ua(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new H.ka(2);if(1===(a.flags&2097155))throw new H.ka(2);if(!a.na.Ua)throw new H.ka(43);
if(!b)throw new H.ka(28);return a.na.Ua(a,b,c,d,e)},Ya(a,b,c,d,e){return a.na.Ya?a.na.Ya(a,b,c,d,e):0},kb(a,b,c){if(!a.na.kb)throw new H.ka(59);return a.na.kb(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&D(`Invalid encoding type "${b.encoding}"`);var c=H.open(a,b.flags);a=H.stat(a).size;var d=new Uint8Array(a);H.read(c,d,0,a,0);"utf8"===b.encoding&&(d=Ta(d));H.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=H.open(a,
c.flags,c.mode);"string"==typeof b&&(b=new Uint8Array(Xa(b)));ArrayBuffer.isView(b)?H.write(a,b,0,b.byteLength,void 0,c.Bc):D("Unsupported data type");H.close(a)},cwd:()=>H.ub,chdir(a){a=N(a,{Da:!0});if(null===a.node)throw new H.ka(44);if(!J(a.node.mode))throw new H.ka(54);var b=M(a.node,"x");if(b)throw new H.ka(b);H.ub=a.path},cb(a,b,c){H.jb=!0;a??=f.stdin;b??=f.stdout;c??=f.stderr;a?H.Qa("/dev","stdin",a):H.symlink("/dev/tty","/dev/stdin");b?H.Qa("/dev","stdout",null,b):H.symlink("/dev/tty","/dev/stdout");
c?H.Qa("/dev","stderr",null,c):H.symlink("/dev/tty1","/dev/stderr");H.open("/dev/stdin",0);H.open("/dev/stdout",1);H.open("/dev/stderr",1)},Qc(){H.jb=!1;for(var a of H.streams)a&&H.close(a)},Hc(a,b){try{var c=N(a,{Da:!b});a=c.path}catch(g){}var d=!1,e=null;try{c=N(a,{parent:!0}),E(a),c=N(a,{Da:!b}),d=!0,e=c.node}catch(g){}return d?e:null},Dc(a,b){a="string"==typeof a?a:kb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ka(a+"/"+c);try{H.mkdir(d)}catch(e){if(20!=e.wa)throw e;}a=
d}}return d},Qa(a,b,c,d){a=Ma("string"==typeof a?a:kb(a),b);b=eb(!!c,!!d);var e;(e=H.Qa).pb??(e.pb=64);e=H.Ra(H.Qa.pb++,0);$a(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,k,m){for(var l=0,n=0;n<m;n++){try{var q=c()}catch(r){throw new H.ka(29);}if(void 0===q&&0===l)throw new H.ka(6);if(null===q||void 0===q)break;l++;h[k+n]=q}l&&(g.node.atime=Date.now());return l},write(g,h,k,m){for(var l=0;l<m;l++)try{d(h[k+l])}catch(n){throw new H.ka(29);}m&&(g.node.mtime=g.node.ctime=Date.now());
return l}});return xb(a,b,e)},Cc(a,b,c,d,e){class g{ob=!1;La=[];Wa=void 0;Eb=0;Cb=0;get(l){if(!(l>this.length-1||0>l)){var n=l%this.chunkSize;return this.Wa(l/this.chunkSize|0)[n]}}ic(l){this.Wa=l}Fb(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);200<=l.status&&300>l.status||304===l.status||D("Couldn't load "+c+". Status: "+l.status);var n=Number(l.getResponseHeader("Content-length")),q,r=(q=l.getResponseHeader("Accept-Ranges"))&&"bytes"===q;l=(q=l.getResponseHeader("Content-Encoding"))&&
"gzip"===q;var t=1048576;r||(t=n);var v=this;v.ic(B=>{var F=B*t,L=(B+1)*t-1;L=Math.min(L,n-1);if("undefined"==typeof v.La[B]){var G=v.La;F>L&&D("invalid range ("+F+", "+L+") or no bytes requested!");L>n-1&&D("only "+n+" bytes available! programmer error!");var C=new XMLHttpRequest;C.open("GET",c,!1);n!==t&&C.setRequestHeader("Range","bytes="+F+"-"+L);C.responseType="arraybuffer";C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");C.send(null);200<=C.status&&300>C.status||
304===C.status||D("Couldn't load "+c+". Status: "+C.status);F=void 0!==C.response?new Uint8Array(C.response||[]):Xa(C.responseText||"");G[B]=F}"undefined"==typeof v.La[B]&&D("doXHR failed!");return v.La[B]});if(l||!n)t=n=1,t=n=this.Wa(0).length,ka("LazyFiles on gzip forces download of the whole file when length is accessed");this.Eb=n;this.Cb=t;this.ob=!0}get length(){this.ob||this.Fb();return this.Eb}get chunkSize(){this.ob||this.Fb();return this.Cb}}if(globalThis.XMLHttpRequest){ba||D("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var h=new g;var k=void 0}else k=c,h=void 0;var m=Ab(a,b,d,e);h?m.oa=h:k&&(m.oa=null,m.url=k);Object.defineProperties(m,{va:{get:function(){return this.oa.length}}});a={};for(const [l,n]of Object.entries(m.na))a[l]=(...q)=>{Bb(m);return n(...q)};a.read=(l,n,q,r,t)=>{Bb(m);l=l.node.oa;if(t>=l.length)n=0;else{r=Math.min(l.length-t,r);if(l.slice)for(var v=0;v<r;v++)n[q+v]=l[t+v];else for(v=0;v<r;v++)n[q+v]=l.get(t+v);n=r}return n};a.Ua=()=>{Bb(m);D();throw new H.ka(48);};m.na=a;return m}},P=(a,b,c)=>
(a>>>=0)?Ta(w,a,b,c):"";function Cb(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?H.cwd():O(a).path;if(0==b.length){if(!c)throw new H.ka(44);return a}return a+"/"+b}
function Db(a,b){z[a>>>2>>>0]=b.dev;z[a+4>>>2>>>0]=b.mode;z[a+8>>>2>>>0]=b.nlink;z[a+12>>>2>>>0]=b.uid;z[a+16>>>2>>>0]=b.gid;z[a+20>>>2>>>0]=b.rdev;A[a+24>>>3>>>0]=BigInt(b.size);y[a+32>>>2>>>0]=4096;y[a+36>>>2>>>0]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),e=b.ctime.getTime();A[a+40>>>3>>>0]=BigInt(Math.floor(c/1E3));z[a+48>>>2>>>0]=c%1E3*1E6;A[a+56>>>3>>>0]=BigInt(Math.floor(d/1E3));z[a+64>>>2>>>0]=d%1E3*1E6;A[a+72>>>3>>>0]=BigInt(Math.floor(e/1E3));z[a+80>>>2>>>0]=e%1E3*1E6;A[a+88>>>
3>>>0]=BigInt(b.ino);return 0}var Eb=void 0,Q=()=>{var a=y[+Eb>>>2>>>0];Eb+=4;return a},Fb={},Gb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Hb(a){return this.ra(z[a>>>2>>>0])}
var Ib={},Jb={},Kb={},Lb=class extends Error{constructor(a){super(a);this.name="InternalError"}},S=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new Lb("Mismatched type converter count");for(var m=0;m<a.length;++m)R(a[m],k[m])}a.forEach(k=>Kb[k]=b);var e=Array(b.length),g=[],h=0;for(let [k,m]of b.entries())Jb.hasOwnProperty(m)?e[k]=Jb[m]:(g.push(m),Ib.hasOwnProperty(m)||(Ib[m]=[]),Ib[m].push(()=>{e[k]=Jb[m];++h;h===g.length&&d(e)}));0===g.length&&d(e)},T=a=>{a>>>=0;for(var b="";;){var c=
w[a++>>>0];if(!c)return b;b+=String.fromCharCode(c)}},U=class extends Error{constructor(a){super(a);this.name="BindingError"}},Mb=a=>{throw new U(a);};function Nb(a,b,c={}){var d=b.name;if(!a)throw new U(`type "${d}" must have a positive integer typeid pointer`);if(Jb.hasOwnProperty(a)){if(c.$b)return;throw new U(`Cannot register type '${d}' twice`);}Jb[a]=b;delete Kb[a];Ib.hasOwnProperty(a)&&(b=Ib[a],delete Ib[a],b.forEach(e=>e()))}function R(a,b,c={}){return Nb(a,b,c)}
var Ob=(a,b,c)=>{switch(b){case 1:return c?d=>u[d>>>0]:d=>w[d>>>0];case 2:return c?d=>x[d>>>1>>>0]:d=>pa[d>>>1>>>0];case 4:return c?d=>y[d>>>2>>>0]:d=>z[d>>>2>>>0];case 8:return c?d=>A[d>>>3>>>0]:d=>sa[d>>>3>>>0];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Pb=a=>{throw new U(a.la.ta.pa.name+" instance already deleted");},Qb=!1,Rb=()=>{},Sb=a=>{if(!globalThis.FinalizationRegistry)return Sb=b=>b,a;Qb=new FinalizationRegistry(b=>{b=b.la;--b.count.value;0===b.count.value&&(b.za?
b.Ea.Ja(b.za):b.ta.pa.Ja(b.qa))});Sb=b=>{var c=b.la;c.za&&Qb.register(b,{la:c},b);return b};Rb=b=>{Qb.unregister(b)};return Sb(a)},Tb=[];function Ub(){}
var Vb=(a,b)=>Object.defineProperty(b,"name",{value:a}),Wb={},Xb=(a,b,c)=>{if(void 0===a[b].ua){var d=a[b];a[b]=function(...e){if(!a[b].ua.hasOwnProperty(e.length))throw new U(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].ua})!`);return a[b].ua[e.length].apply(this,e)};a[b].ua=[];a[b].ua[d.Ka]=d}},Yb=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].ua&&void 0!==f[a].ua[c])throw new U(`Cannot register public name '${a}' twice`);Xb(f,
a,a);if(f[a].ua.hasOwnProperty(c))throw new U(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);f[a].ua[c]=b}else f[a]=b,f[a].Ka=c},Zb=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function $b(a,b,c,d,e,g,h,k){this.name=a;this.constructor=b;this.Ta=c;this.Ja=d;this.Aa=e;this.Ub=g;this.$a=h;this.Qb=k;this.kc=[]}
var ac=(a,b,c)=>{for(;b!==c;){if(!b.$a)throw new U(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.$a(a);b=b.Aa}return a},bc=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function cc(a,b){if(null===b){if(this.lb)throw new U(`null is not a valid ${this.name}`);return 0}if(!b.la)throw new U(`Cannot pass "${bc(b)}" as a ${this.name}`);if(!b.la.qa)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);return ac(b.la.qa,b.la.ta.pa,this.pa)}
function dc(a,b){if(null===b){if(this.lb)throw new U(`null is not a valid ${this.name}`);if(this.fb){var c=this.sb();null!==a&&a.push(this.Ja,c);return c}return 0}if(!b||!b.la)throw new U(`Cannot pass "${bc(b)}" as a ${this.name}`);if(!b.la.qa)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.eb&&b.la.ta.eb)throw new U(`Cannot convert argument of type ${b.la.Ea?b.la.Ea.name:b.la.ta.name} to parameter type ${this.name}`);c=ac(b.la.qa,b.la.ta.pa,this.pa);if(this.fb){if(void 0===
b.la.za)throw new U("Passing raw pointer to smart pointer is illegal");switch(this.pc){case 0:if(b.la.Ea===this)c=b.la.za;else throw new U(`Cannot convert argument of type ${b.la.Ea?b.la.Ea.name:b.la.ta.name} to parameter type ${this.name}`);break;case 1:c=b.la.za;break;case 2:if(b.la.Ea===this)c=b.la.za;else{var d=b.clone();c=this.lc(c,V(()=>d["delete"]()));null!==a&&a.push(this.Ja,c)}break;default:throw new U("Unsupported sharing policy");}}return c}
function ec(a,b){if(null===b){if(this.lb)throw new U(`null is not a valid ${this.name}`);return 0}if(!b.la)throw new U(`Cannot pass "${bc(b)}" as a ${this.name}`);if(!b.la.qa)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.la.ta.eb)throw new U(`Cannot convert argument of type ${b.la.ta.name} to parameter type ${this.name}`);return ac(b.la.qa,b.la.ta.pa,this.pa)}
var fc=(a,b,c)=>{if(b===c)return a;if(void 0===c.Aa)return null;a=fc(a,b,c.Aa);return null===a?null:c.Qb(a)},gc={},ic=(a,b)=>{if(void 0===b)throw new U("ptr should not be undefined");for(;a.Aa;)b=a.$a(b),a=a.Aa;return gc[b]},jc=(a,b)=>{if(!b.ta||!b.qa)throw new Lb("makeClassHandle requires ptr and ptrType");if(!!b.Ea!==!!b.za)throw new Lb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Sb(Object.create(a,{la:{value:b,writable:!0}}))};
function kc(a,b,c,d,e,g,h,k,m,l,n){this.name=a;this.pa=b;this.lb=c;this.eb=d;this.fb=e;this.jc=g;this.pc=h;this.Gb=k;this.sb=m;this.lc=l;this.Ja=n;e||void 0!==b.Aa?this.xa=dc:(this.xa=d?cc:ec,this.ya=null)}
var lc=(a,b,c)=>{if(!f.hasOwnProperty(a))throw new Lb("Replacing nonexistent public symbol");void 0!==f[a].ua&&void 0!==c?f[a].ua[c]=b:(f[a]=b,f[a].Ka=c)},mc=[],oc=a=>{var b=mc[a];b||(mc[a]=b=nc.get(a));return b},pc=(a,b,c=[])=>{b=oc(b)(...c);return"p"==a[0]?b>>>0:b},qc=(a,b)=>(...c)=>pc(a,b,c),W=(a,b)=>{a=T(a);var c=a.includes("p")?qc(a,b):oc(b);if("function"!=typeof c)throw new U(`unknown function pointer with signature ${a}: ${b}`);return c};class rc extends Error{}
var tc=a=>{a=sc(a);var b=T(a);X(a);return b},uc=(a,b)=>{function c(g){e[g]||Jb[g]||(Kb[g]?Kb[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new rc(`${a}: `+d.map(tc).join([", "]));};function vc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].ya)return!0;return!1}
function wc(a,b,c,d,e,g){var h=b.length;if(2>h)throw new U("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,m=vc(b);c=!b[0].Bb;var l=b[0],n=b[1];d=[a,Mb,d,e,Gb,l.ra.bind(l),n?.xa.bind(n)];for(e=2;e<h;++e)l=b[e],d.push(l.xa.bind(l));if(!m)for(e=k?1:2;e<b.length;++e)null!==b[e].ya&&d.push(b[e].ya);m=vc(b);e=b.length-2;n=[];l=["fn"];k&&l.push("thisWired");for(h=0;h<e;++h)n.push(`arg${h}`),l.push(`arg${h}Wired`);n=n.join(",");l=l.join(",");
n=`return function (${n}) {\n`;m&&(n+="var destructors = [];\n");var q=m?"destructors":"null",r="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");k&&(n+=`var thisWired = toClassParamWire(${q}, this);\n`);for(h=0;h<e;++h){var t=`toArg${h}Wire`;n+=`var arg${h}Wired = ${t}(${q}, arg${h});\n`;r.push(t)}n+=(c||g?"var rv = ":"")+`invoker(${l});\n`;if(m)n+="runDestructors(destructors);\n";else for(h=k?1:2;h<b.length;++h)g=1===h?"thisWired":"arg"+(h-2)+"Wired",
null!==b[h].ya&&(n+=`${g}_dtor(${g});\n`,r.push(`${g}_dtor`));c&&(n+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(r,n+"}\n"))(...d);return Vb(a,b)}var xc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(z[b+4*d>>>2>>>0]);return c},yc=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},zc=[],Y=[0,1,,1,null,1,!0,1,!1,1];function Ac(a){a>>>=0;9<a&&0===--Y[a+1]&&(Y[a]=void 0,zc.push(a))}
var Z=a=>{if(!a)throw new U(`Cannot use deleted val. handle = ${a}`);return Y[a]},V=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=zc.pop()||Y.length;Y[b]=a;Y[b+1]=1;return b}},Bc={name:"emscripten::val",ra:a=>{var b=Z(a);Ac(a);return b},xa:(a,b)=>V(b),Ca:Hb,ya:null},Cc=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.ra(u[d>>>0])}:function(d){return this.ra(w[d>>>0])};case 2:return c?function(d){return this.ra(x[d>>>1>>>0])}:function(d){return this.ra(pa[d>>>
1>>>0])};case 4:return c?function(d){return this.ra(y[d>>>2>>>0])}:function(d){return this.ra(z[d>>>2>>>0])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Dc=(a,b)=>{var c=Jb[a];if(void 0===c)throw a=`${b} has unknown type ${tc(a)}`,new U(a);return c},Ec=(a,b)=>{switch(b){case 4:return function(c){return this.ra(qa[c>>>2>>>0])};case 8:return function(c){return this.ra(ra[c>>>3>>>0])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Fc=globalThis.TextDecoder?
new TextDecoder("utf-16le"):void 0,Gc=(a,b,c)=>{a>>>=1;b=Sa(pa,a,b/2,c);if(16<b-a&&Fc)return Fc.decode(pa.subarray(a>>>0,b>>>0));for(c="";a<b;++a)c+=String.fromCharCode(pa[a>>>0]);return c},Hc=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)x[b>>>1>>>0]=a.charCodeAt(e),b+=2;x[b>>>1>>>0]=0;return b-d},Ic=a=>2*a.length,Jc=(a,b,c)=>{var d="";a>>>=2;for(var e=0;!(e>=b/4);e++){var g=z[a+e>>>0];if(!g&&!c)break;d+=String.fromCodePoint(g)}return d},Kc=
(a,b,c)=>{b>>>=0;c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.codePointAt(e);65535<g&&e++;y[b>>>2>>>0]=g;b+=4;if(b+4>c)break}y[b>>>2>>>0]=0;return b-d},Lc=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Mc=a=>{a=a.split(".");for(var b=0;4>b;b++){var c=Number(a[b]);if(isNaN(c))return null;a[b]=c}return(a[0]|a[1]<<8|a[2]<<16|a[3]<<24)>>>0},Oc=a=>{var b,c,d=[];if(!/^((?=.*::)(?!.*::.+::)(::)?([\dA-F]{1,4}:(:|\b)|){5}|([\dA-F]{1,4}:){6})((([\dA-F]{1,4}((?!\3)::|:\b|$))|(?!\2\3)){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})$/i.test(a))return null;
if("::"===a)return[0,0,0,0,0,0,0,0];a=a.startsWith("::")?a.replace("::","Z:"):a.replace("::",":Z:");0<a.indexOf(".")?(a=a.replace(RegExp("[.]","g"),":"),a=a.split(":"),a[a.length-4]=Number(a[a.length-4])+256*Number(a[a.length-3]),a[a.length-3]=Number(a[a.length-2])+256*Number(a[a.length-1]),a=a.slice(0,a.length-2)):a=a.split(":");for(b=c=0;b<a.length;b++)if("string"==typeof a[b])if("Z"===a[b]){for(c=0;c<8-a.length+1;c++)d[b+c]=0;--c}else d[b+c]=Nc(parseInt(a[b],16));else d[b+c]=a[b];return[d[1]<<
16|d[0],d[3]<<16|d[2],d[5]<<16|d[4],d[7]<<16|d[6]]},Pc=1,Qc={},Rc=[],Sc=a=>{var b=Rc.length;Rc.push(a);return b},Tc=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Dc(z[b+4*d>>>2>>>0],`parameter ${d}`);return c},Uc=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(z[b>>>2>>>0]=V(d));return a},Vc={},Wc=a=>{var b=Vc[a];return void 0===b?T(a):b},Xc=[0,31,60,91,121,152,182,213,244,274,305,335],Yc=[0,31,59,90,120,151,181,212,243,273,304,334];H.Ec=(a,b,c,d,e,g,h,k,m,l)=>{lb(a,b,c,d,e,k,m,l).then(g).catch(h)};H.Pc=lb;
H.Na=Array(4096);H.sa(I,{},"/");H.mkdir("/tmp");H.mkdir("/home");H.mkdir("/home/web_user");(function(){H.mkdir("/dev");$a(H.Ra(1,3),{read:()=>0,write:(d,e,g,h)=>h,Ba:()=>0});xb("/dev/null",H.Ra(1,3));Za(H.Ra(5,0),bb);Za(H.Ra(6,0),cb);xb("/dev/tty",H.Ra(5,0));xb("/dev/tty1",H.Ra(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Oa(a),b=a.byteLength);return a[--b]};H.Qa("/dev","random",c);H.Qa("/dev","urandom",c);H.mkdir("/dev/shm");H.mkdir("/dev/shm/tmp")})();
(function(){H.mkdir("/proc");var a=H.mkdir("/proc/self");H.mkdir("/proc/self/fd");H.sa({sa(){var b=H.createNode(a,"fd",16895,73);b.na={Ba:I.na.Ba};b.ma={lookup(c,d){c=+d;var e=O(c);c={parent:null,sa:{Db:"fake"},ma:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(H.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();H.Tb={MEMFS:I};
(()=>{let a=Ub.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof Ub&&c instanceof Ub))return!1;var d=this.la.ta.pa,e=this.la.qa;c.la=c.la;var g=c.la.ta.pa;for(c=c.la.qa;d.Aa;)e=d.$a(e),d=d.Aa;for(;g.Aa;)c=g.$a(c),g=g.Aa;return d===g&&e===c},clone:function(){this.la.qa||Pb(this);if(this.la.Za)return this.la.count.value+=1,this;var c=Sb,d=Object,e=d.create,g=Object.getPrototypeOf(this),h=this.la;c=c(e.call(d,g,{la:{value:{count:h.count,Va:h.Va,Za:h.Za,qa:h.qa,ta:h.ta,za:h.za,Ea:h.Ea}}}));
c.la.count.value+=1;c.la.Va=!1;return c},["delete"](){this.la.qa||Pb(this);if(this.la.Va&&!this.la.Za)throw new U("Object already scheduled for deletion");Rb(this);var c=this.la;--c.count.value;0===c.count.value&&(c.za?c.Ea.Ja(c.za):c.ta.pa.Ja(c.qa));this.la.Za||(this.la.za=void 0,this.la.qa=void 0)},isDeleted:function(){return!this.la.qa},deleteLater:function(){this.la.qa||Pb(this);if(this.la.Va&&!this.la.Za)throw new U("Object already scheduled for deletion");Tb.push(this);this.la.Va=!0;return this}});
const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(kc.prototype,{Wb(a){this.Gb&&(a=this.Gb(a));return a},vb(a){this.Ja?.(a)},Ca:Hb,ra:function(a){function b(){return this.fb?jc(this.pa.Ta,{ta:this.jc,qa:c,Ea:this,za:a}):jc(this.pa.Ta,{ta:this,qa:a})}var c=this.Wb(a);if(!c)return this.vb(a),null;var d=ic(this.pa,c);if(void 0!==d){if(0===d.la.count.value)return d.la.qa=c,d.la.za=a,d.clone();d=d.clone();this.vb(a);return d}d=this.pa.Ub(c);d=Wb[d];if(!d)return b.call(this);d=this.eb?d.Pb:d.pointerType;var e=fc(c,this.pa,d.pa);return null===
e?b.call(this):this.fb?jc(d.pa.Ta,{ta:d,qa:e,Ea:this,za:a}):jc(d.pa.Ta,{ta:d,qa:e})}});f.noExitRuntime&&(Fa=f.noExitRuntime);f.preloadPlugins&&(ib=f.preloadPlugins);f.print&&(ka=f.print);f.printErr&&(p=f.printErr);f.wasmBinary&&(la=f.wasmBinary);if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();f.FS=H;
var sc,Zc,X,Nc,va,nc,$c={ca:function(){return f.rc.length},b:function(a,b,c){a>>>=0;(new Ga(a)).cb(b>>>0,c>>>0);Ha=a;Ia++;throw Ha;},ba:function(a,b){a>>>=0;try{return a=P(a),H.chmod(a,b),0}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return-c.wa}},aa:function(a,b,c){b>>>=0;try{b=P(b);b=Cb(a,b);if(c&-8)return-28;var d=N(b,{Da:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&M(d,a)?-2:0}catch(e){if("undefined"==typeof H||"ErrnoError"!==e.name)throw e;
return-e.wa}},z:function(a,b,c){Eb=c>>>0;try{var d=O(a);switch(b){case 0:var e=Q();if(0>e)break;for(;H.streams[e];)e++;return tb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Q(),d.flags|=e,0;case 12:return e=Q(),x[e+0>>>1>>>0]=2,0;case 13:case 14:return 0}return-28}catch(g){if("undefined"==typeof H||"ErrnoError"!==g.name)throw g;return-g.wa}},$:function(a,b){try{return Db(b>>>0,H.fstat(a))}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return-c.wa}},_:function(a,
b,c){Eb=c>>>0;try{var d=O(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Oa.ac){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Q();y[e>>>2>>>0]=25856;y[e+4>>>2>>>0]=5;y[e+8>>>2>>>0]=191;y[e+12>>>2>>>0]=35387;for(var g=0;32>g;g++)u[e+g+17>>>0]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Oa.bc)for(e=Q(),a=[],g=0;32>g;g++)a.push(u[e+g+17>>>0]);
return 0;case 21519:if(!d.tty)return-59;e=Q();return y[e>>>2>>>0]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:return e=Q(),H.kb(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Oa.cc&&(g=[24,80],e=Q(),x[e>>>1>>>0]=g[0],x[e+2>>>1>>>0]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof H||"ErrnoError"!==h.name)throw h;return-h.wa}},Z:function(a,b){a>>>=0;b>>>=0;try{return a=P(a),Db(b,H.lstat(a))}catch(c){if("undefined"==
typeof H||"ErrnoError"!==c.name)throw c;return-c.wa}},Y:function(a,b,c,d){b>>>=0;c>>>=0;try{b=P(b);var e=d&256;b=Cb(a,b,d&4096);return Db(c,e?H.lstat(b):H.stat(b))}catch(g){if("undefined"==typeof H||"ErrnoError"!==g.name)throw g;return-g.wa}},F:function(a,b,c,d){b>>>=0;Eb=d>>>=0;try{b=P(b);b=Cb(a,b);var e=d?Q():0;return H.open(b,c,e).fd}catch(g){if("undefined"==typeof H||"ErrnoError"!==g.name)throw g;return-g.wa}},X:function(a,b){a>>>=0;b>>>=0;try{return a=P(a),Db(b,H.stat(a))}catch(c){if("undefined"==
typeof H||"ErrnoError"!==c.name)throw c;return-c.wa}},T:()=>D(""),q:function(a){a>>>=0;var b=Fb[a];delete Fb[a];var c=b.sb,d=b.Ja,e=b.yb,g=e.map(h=>h.Zb).concat(e.map(h=>h.nc));S([a],g,h=>{var k={},m,l;for([m,l]of e.entries()){const n=h[m],q=l.Wa,r=l.Yb,t=h[m+e.length],v=l.mc,B=l.oc;k[l.Sb]={read:F=>n.ra(q(r,F)),write:(F,L)=>{var G=[];v(B,F,t.xa(G,L));Gb(G)},optional:n.optional}}return[{name:b.name,ra:n=>{var q={},r;for(r in k)q[r]=k[r].read(n);d(n);return q},xa:(n,q)=>{for(var r in k)if(!(r in q||
k[r].optional))throw new TypeError(`Missing field: "${r}"`);var t=c();for(r in k)k[r].write(t,q[r]);null!==n&&n.push(d,t);return t},Ca:Hb,ya:d}]})},D:function(a,b,c,d,e){a>>>=0;c>>>=0;b=T(b>>>0);d=0n===d;let g=h=>h;if(d){const h=8*c;g=k=>BigInt.asUintN(h,k);e=g(e)}R(a,{name:b,ra:g,xa:(h,k)=>{"number"==typeof k&&(k=BigInt(k));return k},Ca:Ob(b,c,!d),ya:null})},S:function(a,b,c,d){b=T(b>>>0);R(a>>>0,{name:b,ra:function(e){return!!e},xa:function(e,g){return g?c:d},Ca:function(e){return this.ra(w[e>>>
0])},ya:null})},n:function(a,b,c,d,e,g,h,k,m,l,n,q,r){a>>>=0;b>>>=0;c>>>=0;d>>>=0;g>>>=0;h>>>=0;k>>>=0;m>>>=0;l>>>=0;n>>>=0;q>>>=0;r>>>=0;n=T(n);g=W(e>>>0,g);k&&=W(h,k);l&&=W(m,l);r=W(q,r);var t=Zb(n);Yb(t,function(){uc(`Cannot construct ${n} due to unbound types`,[d])});S([a,b,c],d?[d]:[],v=>{v=v[0];if(d){var B=v.pa;var F=B.Ta}else F=Ub.prototype;v=Vb(n,function(...ob){if(Object.getPrototypeOf(this)!==L)throw new U(`Use 'new' to construct ${n}`);if(void 0===G.Pa)throw new U(`${n} has no accessible constructor`);
var hc=G.Pa[ob.length];if(void 0===hc)throw new U(`Tried to invoke ctor of ${n} with invalid number of parameters (${ob.length}) - expected (${Object.keys(G.Pa).toString()}) parameters instead!`);return hc.apply(this,ob)});var L=Object.create(F,{constructor:{value:v}});v.prototype=L;var G=new $b(n,v,L,r,B,g,k,l);if(G.Aa){var C;(C=G.Aa).ab??(C.ab=[]);G.Aa.ab.push(G)}B=new kc(n,G,!0,!1,!1);C=new kc(n+"*",G,!1,!1,!1);F=new kc(n+" const*",G,!1,!0,!1);Wb[a]={pointerType:C,Pb:F};lc(t,v);return[B,C,F]})},
j:function(a,b,c,d,e,g,h,k){a>>>=0;b>>>=0;e>>>=0;g>>>=0;h>>>=0;var m=xc(c,d>>>0);b=T(b);b=yc(b);g=W(e,g);S([],[a],l=>{function n(){uc(`Cannot call ${q} due to unbound types`,m)}l=l[0];var q=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var r=l.pa.constructor;void 0===r[b]?(n.Ka=c-1,r[b]=n):(Xb(r,b,q),r[b].ua[c-1]=n);S([],m,t=>{t=[t[0],null].concat(t.slice(1));t=wc(q,t,null,g,h,k);void 0===r[b].ua?(t.Ka=c-1,r[b]=t):r[b].ua[c-1]=t;if(l.pa.ab)for(const v of l.pa.ab)v.constructor.hasOwnProperty(b)||
(v.constructor[b]=t);return[]});return[]})},i:function(a,b,c,d,e,g){a>>>=0;d>>>=0;e>>>=0;g>>>=0;var h=xc(b,c>>>0);e=W(d,e);S([],[a],k=>{k=k[0];var m=`constructor ${k.name}`;void 0===k.pa.Pa&&(k.pa.Pa=[]);if(void 0!==k.pa.Pa[b-1])throw new U(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);k.pa.Pa[b-1]=()=>{uc(`Cannot construct ${k.name} due to unbound types`,
h)};S([],h,l=>{l.splice(1,0,null);k.pa.Pa[b-1]=wc(m,l,null,e,g);return[]});return[]})},a:function(a,b,c,d,e,g,h,k,m){a>>>=0;b>>>=0;e>>>=0;g>>>=0;h>>>=0;var l=xc(c,d>>>0);b=T(b);b=yc(b);g=W(e,g);S([],[a],n=>{function q(){uc(`Cannot call ${r} due to unbound types`,l)}n=n[0];var r=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&n.pa.kc.push(b);var t=n.pa.Ta,v=t[b];void 0===v||void 0===v.ua&&v.className!==n.name&&v.Ka===c-2?(q.Ka=c-2,q.className=n.name,t[b]=q):(Xb(t,b,r),t[b].ua[c-
2]=q);S([],l,B=>{B=wc(r,B,n,g,h,m);void 0===t[b].ua?(B.Ka=c-2,t[b]=B):t[b].ua[c-2]=B;return[]});return[]})},R:function(a){return R(a>>>0,Bc)},s:function(a,b,c,d,e){a>>>=0;c>>>=0;b=T(b>>>0);e=0===e?"object":1===e?"number":"string";switch(e){case "object":function h(){}h.values={};R(a,{name:b,constructor:h,valueType:e,ra:function(k){return this.constructor.values[k]},xa:(k,m)=>m.value,Ca:Cc(b,c,d),ya:null});Yb(b,h);break;case "number":var g={};R(a,{name:b,nb:g,valueType:e,ra:k=>k,xa:(k,m)=>m,Ca:Cc(b,
c,d),ya:null});Yb(b,g);delete f[b].Ka;break;case "string":g={},R(a,{name:b,Kb:{},Hb:{},nb:g,valueType:e,ra:function(k){return this.Hb[k]},xa:function(k,m){return this.Kb[m]},Ca:Cc(b,c,d),ya:null}),Yb(b,g),delete f[b].Ka}},o:function(a,b,c){b>>>=0;var d=Dc(a>>>0,"enum");b=T(b);switch(d.valueType){case "object":a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Vb(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d;break;case "number":d.nb[b]=c;break;case "string":d.Kb[b]=
c,d.Hb[c]=b,d.nb[b]=b}},C:function(a,b,c){b=T(b>>>0);R(a>>>0,{name:b,ra:d=>d,xa:(d,e)=>e,Ca:Ec(b,c>>>0),ya:null})},B:function(a,b,c,d,e,g,h){a>>>=0;d>>>=0;e>>>=0;g>>>=0;var k=xc(b,c>>>0);a=T(a);a=yc(a);e=W(d,e);Yb(a,function(){uc(`Cannot call ${a} due to unbound types`,k)},b-1);S([],k,m=>{m=[m[0],null].concat(m.slice(1));lc(a,wc(a,m,null,e,g,h),b-1);return[]})},w:function(a,b,c,d,e){a>>>=0;c>>>=0;b=T(b>>>0);let g=k=>k;if(0===d){var h=32-8*c;g=k=>k<<h>>>h;e=g(e)}R(a,{name:b,ra:g,xa:(k,m)=>m,Ca:Ob(b,
c,0!==d),ya:null})},u:function(a,b,c){function d(g){return new e(u.buffer,z[g+4>>>2>>>0],z[g>>>2>>>0])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=T(c>>>0);R(a>>>0,{name:c,ra:d,Ca:d},{$b:!0})},r:function(a,b,c,d,e,g,h,k,m,l,n,q){a>>>=0;b>>>=0;c>>>=0;g>>>=0;h>>>=0;k>>>=0;m>>>=0;l>>>=0;n>>>=0;q>>>=0;c=T(c);g=W(e>>>0,g);k=W(h,k);l=W(m,l);q=W(n,q);S([a],[b],r=>{r=r[0];return[new kc(c,r.pa,!1,!1,!0,r,d,g,k,l,q)]})},
Q:function(a,b){b=T(b>>>0);R(a>>>0,{name:b,ra(c){var d=P(c+4,z[c>>>2>>>0],!0);X(c);return d},xa(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new U("Cannot pass non-string to std::string");var g=e?Va(d):d.length;var h=Zc(4+g+1),k=h+4;z[h>>>2>>>0]=g;e?Wa(d,w,k,g+1):w.set(d,k>>>0);null!==c&&c.push(X,h);return h},Ca:Hb,ya(c){X(c)}})},x:function(a,b,c){b>>>=0;c>>>=0;c=T(c);if(2===b){var d=Gc;var e=Hc;var g=Ic}else d=
Jc,e=Kc,g=Lc;R(a>>>0,{name:c,ra:h=>{var k=d(h+4,z[h>>>2>>>0]*b,!0);X(h);return k},xa:(h,k)=>{if("string"!=typeof k)throw new U(`Cannot pass non-string to C++ string type ${c}`);var m=g(k),l=Zc(4+m+b);z[l>>>2>>>0]=m/b;e(k,l+4,m+b);null!==h&&h.push(X,l);return l},Ca:Hb,ya(h){X(h)}})},p:function(a,b,c,d,e,g){e>>>=0;g>>>=0;Fb[a>>>0]={name:T(b>>>0),sb:W(c>>>0,d>>>0),Ja:W(e,g),yb:[]}},l:function(a,b,c,d,e,g,h,k,m,l){g>>>=0;h>>>=0;k>>>=0;m>>>=0;l>>>=0;Fb[a>>>0].yb.push({Sb:T(b>>>0),Zb:c>>>0,Wa:W(d>>>0,e>>>
0),Yb:g,nc:h,mc:W(k,m),oc:l})},P:function(a,b){b=T(b>>>0);R(a>>>0,{Bb:!0,name:b,ra:()=>{},xa:()=>{}})},O:function(a){a=P(a>>>0);var b=Mc(a);null===b&&(b=Oc(a),null===b&&(Qc[a]?b=Qc[a]:(b=Pc++,b="172.29."+(b&255)+"."+(b&65280),Qc[a]=b),a=b));return Mc(a)},d:function(a,b,c){var [d,...e]=Tc(a,b>>>0);b=d.xa.bind(d);var g=e.map(m=>m.Ca.bind(m));a--;var h={toValue:Z};a=g.map((m,l)=>{var n=`argFromPtr${l}`;h[n]=m;return`${n}(args${l?"+"+8*l:""})`});switch(c){case 0:var k="toValue(handle)";break;case 2:k=
"new (toValue(handle))";break;case 3:k="";break;case 1:h.getStringOrSymbol=Wc,k="toValue(handle)[getStringOrSymbol(methodName)]"}k+=`(${a})`;d.Bb||(h.toReturnWire=b,h.emval_returnValue=Uc,k=`return emval_returnValue(toReturnWire, destructorsRef, ${k})`);k=`return function (handle, methodName, destructorsRef, args) {\n${k}\n}`;c=(new Function(Object.keys(h),k))(...Object.values(h));k=`methodCaller<(${e.map(m=>m.name)}) => ${d.name}>`;return Sc(Vb(k,c))},g:Ac,v:function(a){a>>>=0;if(!a)return V(globalThis);
a=Wc(a);return V(globalThis[a])},h:function(a){a=Wc(a>>>0);return V(f[a])},t:function(a,b){b>>>=0;a=Z(a>>>0);b=Z(b);return V(a[b])},f:function(a){a>>>=0;9<a&&(Y[a+1]+=1)},m:function(a,b){b>>>=0;a=Z(a>>>0);b=Z(b);return a instanceof b},c:function(a,b,c,d,e){return Rc[a>>>0](b>>>0,c>>>0,d>>>0,e>>>0)},A:function(a){return V(Wc(a>>>0))},e:function(a){a>>>=0;var b=Z(a);Gb(b);Ac(a)},N:function(a,b,c){b>>>=0;c>>>=0;a=Z(a>>>0);b=Z(b);c=Z(c);a[b]=c},k:function(a){a=Z(a>>>0);return V(typeof a)},M:function(a,
b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);y[b>>>2>>>0]=a.getSeconds();y[b+4>>>2>>>0]=a.getMinutes();y[b+8>>>2>>>0]=a.getHours();y[b+12>>>2>>>0]=a.getDate();y[b+16>>>2>>>0]=a.getMonth();y[b+20>>>2>>>0]=a.getFullYear()-1900;y[b+24>>>2>>>0]=a.getDay();var c=a.getFullYear();y[b+28>>>2>>>0]=(0!==c%4||0===c%100&&0!==c%400?Yc:Xc)[a.getMonth()]+a.getDate()-1|0;y[b+36>>>2>>>0]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=
(new Date(a.getFullYear(),0,1)).getTimezoneOffset();y[b+32>>>2>>>0]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},L:function(a,b,c,d){c>>>=0;d>>>=0;var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();z[a>>>0>>>2>>>0]=60*Math.max(g,e);y[b>>>0>>>2>>>0]=Number(g!=e);b=h=>{var k=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(Wa(a,w,c,17),Wa(b,w,d,17)):(Wa(a,
w,d,17),Wa(b,w,c,17))},W:function(a,b,c){if(!(0<=a&&3>=a))return 28;A[c>>>0>>>3>>>0]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},K:()=>Date.now(),J:function(a,b,c){b>>>=0;var d=Error().stack.toString(),e=d.split("\n");d="";var g=RegExp("\\s*(.*?)@(.*?):([0-9]+):([0-9]+)"),h=RegExp("\\s*at (.*?) \\((.*):(.*):(.*)\\)"),k;for(k of e){var m=h.exec(k);if(5==m?.length){e=m[1];var l=m[2];var n=m[3];m=m[4]}else if(m=g.exec(k),4<=m?.length)e=m[1],l=m[2],n=m[3],m=m[4]|0;else{d+=k+
"\n";continue}"_emscripten_log"==e||"_emscripten_get_callstack"==e?d="":a&24&&(a&64&&(l=l.substring(l.replace(/\\/g,"/").lastIndexOf("/")+1)),d+=`    at ${e} (${l}:${n}:${m})\n`)}a=d=d.replace(/\s+$/,"");return!b||0>=c?Va(a)+1:Wa(a,w,b,c)+1},I:function(){return 4294901760},H:function(a){a>>>=0;var b=w.length;if(4294901760<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(4294901760,65536*Math.ceil(Math.max(a,d)/65536))-va.buffer.byteLength+65535)/65536|0;
try{va.grow(d);ua();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},G:a=>{Fa||(f.onExit?.(a),ma=!0);da(a,new Aa(a))},y:function(a){try{var b=O(a);H.close(b);return 0}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return c.wa}},V:function(a,b,c,d){b>>>=0;c>>>=0;d>>>=0;try{a:{var e=O(a);a=b;for(var g,h=b=0;h<c;h++){var k=z[a>>>2>>>0],m=z[a+4>>>2>>>0];a+=8;var l=H.read(e,u,k,m,g);if(0>l){var n=-1;break a}b+=l;if(l<m)break;"undefined"!=typeof g&&(g+=l)}n=b}z[d>>>2>>>0]=n;
return 0}catch(q){if("undefined"==typeof H||"ErrnoError"!==q.name)throw q;return q.wa}},U:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);d>>>=0;try{if(isNaN(b))return 61;var e=O(a);H.Ba(e,b,c);A[d>>>3>>>0]=BigInt(e.position);e.ib&&0===b&&0===c&&(e.ib=null);return 0}catch(g){if("undefined"==typeof H||"ErrnoError"!==g.name)throw g;return g.wa}},E:function(a,b,c,d){b>>>=0;c>>>=0;d>>>=0;try{a:{var e=O(a);a=b;for(var g,h=b=0;h<c;h++){var k=z[a>>>2>>>0],m=z[a+4>>>2>>>0];a+=8;
var l=H.write(e,u,k,m,g);if(0>l){var n=-1;break a}b+=l;if(l<m)break;"undefined"!=typeof g&&(g+=l)}n=b}z[d>>>2>>>0]=n;return 0}catch(q){if("undefined"==typeof H||"ErrnoError"!==q.name)throw q;return q.wa}}};function ad(){var a=bd;a=Object.assign({},a);var b=c=>d=>c(d)>>>0;a.fa=b(a.fa);a.ha=b(a.ha);a._emscripten_stack_alloc=b(a._emscripten_stack_alloc);return a}
function cd(){function a(){f.calledRun=!0;if(!ma){ta=!0;f.noFSInit||H.jb||H.cb();bd.ea();H.Ab=!1;na?.(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Ca.push(b)}Ba(Ca)}}if(0<gb)hb=cd;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ea();Ba(Da);0<gb?hb=cd:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()}}var bd;
bd=await (async function(){function a(c){bd=c.exports;c=bd=ad();sc=c.fa;Zc=c.ha;X=c.ia;Nc=c.ja;va=c.da;nc=c.ga;ua();return bd}var b={a:$c};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});wa??=f.locateFile?f.locateFile?f.locateFile("replicad_single.wasm",fa):fa+"replicad_single.wasm":(new URL("replicad_single.wasm",import.meta.url)).href;return a((await za(b)).instance)}());cd();ta?moduleRtn=f:moduleRtn=new Promise((a,b)=>{na=a;oa=b});
;return moduleRtn}export default Module;
