/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  typedocSidebar: [
    "intro",
    {
      "Getting Started": [
        { type: "autogenerated", dirName: "tutorial-overview" },
      ],
    },
    {
      "Making a watering can": [
        { type: "autogenerated", dirName: "tutorial-making-a-watering-can" },
      ],
    },
    {
      "Advanced topics": [
        { type: "autogenerated", dirName: "advanced-topics" },
      ],
    },
    { Recipes: [{ type: "autogenerated", dirName: "recipes" }] },
    { Examples: [{ type: "autogenerated", dirName: "examples" }] },
    "use-as-a-library",
    "other-ressources",
    {
      type: "category",
      label: "Replicad API",
      link: {
        type: "doc",
        id: "api/index",
      },
      items: require("./docs/api/typedoc-sidebar.cjs"),
    },
  ],
};

module.exports = sidebars;
